### ISSUE TITLE
Improving handling of guards

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#105]
The LFE compiler handles guards correctly but not as efficiently as possible. One reason is that optimisation passes in the erlang compiler assume that things look exactly like they do from the erlang compiler otherwise they can sometimes do something wrong or even crash. For this reason I have turned off some optimisation passes.

What I plan to do now is rewrite some of the LFE compiler code generation pass to output more erlang compiler like code so I can, hopefully, turn on the optimisation again.

**Comment by oubiwann** [comment]
A note from the sidelines: This is insanely cool :-)

**Comment by rvirding** [comment]
This was fixed in this commit 5e6dc259d5bdccbc02c2aa271e30b04021e81bfd when we went over to the LFE compiler generating Erlang AST.
