### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#106]
Would it be better if the tags did not have a 'v' prefix? If they were just '0.9'?

**Comment by oubiwann** [comment]
Hrm. I don't know. Most projects tend to just use the version number
itself... though some prefix the version number with the project name (or
even a "release name" like "eager badger" or whatever).

For my own projects, I just keep it simple and use the version number. If I
do release candidates, or any other permutations of semantic versioning, I
do that in the tags...

**Comment by arpunk** [comment]
The `v` prefix works fine I think. Most of the projects I've seen prepend the `v` before tagging. This helps us use tags for other purposes.

**Comment by yurrriq** [comment]
I think we should continue to do both, for backward compatibility and maximum appeasement. This issue can be closed.

**Comment by rvirding** [comment]
I now tag with both to get around the issue.
