### ISSUE TITLE
help/1 in the REPL?

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#115]
Do you think it would be possible to, in addition to the already-supported help/0 in the REPL, to have a help/1 for displaying module man pages?

``` lisp
> (help io_lib)
```

**Comment by rvirding** [comment]
It would be possible if the man pages are downloaded into the "right places", otherwise not.

**Comment by arpunk** [comment]
What about being able to printing out the docstring of a function via `help/1`?

EDIT: Nevermind, I just saw the referenced issues: #87 and #67

**Comment by oubiwann** [comment]
I think I like the idea of `help/2` and `help/3` as names, instead of describe. `help/1` could even be used to get the help of REPL functions. This last would require that the help text for each REPL function be stored somewhere (perhaps in `lfe_shell` using the `docstring` module attributes, as proposed in the other ticket?). It would also mean that the output for `help/0` could be generated automatically ...

**Comment by oubiwann** [comment]
Lots of good work has gone into a solution for this problem; with LFE 2.0 we're even going to have support for Elixir docs metadata, etc.
