### ISSUE TITLE
Lispify Erlang functions automatically

### ISSUE THREAD

**Issue by arpunk** [lfe/lfe#120]
I've seen [kla](https://github.com/billosys/kla) and [Joxa](http://docs.joxa.org/en/latest/language.html#making-erlang-modules-appear-like-joxa-namespaces-joxification) doing this in order to avoid the underscores in the Erlang functions.

Would it be possible to have such a thing in LFE as an option?

**Comment by rvirding** [comment]
There have been suggestions to about this before.

One has been to translate '-' in LFE symbols to '_' in the atom in the tokeniser and fix the printer so it changes it back. Pretty easy to do but can cause confusion as wys is not quite wyg.

It easier for Joxa to do this type of translation as it forces you to do a 'require' on other modules you wish to use inside a module. I don't quite know how this is processed if the required modules must already be defined so it knows the functions or just blindly converts. I mean when I require that_module joxified and I call that-module/the-func it just translates it to that_module/the_func. A quick look implies it only works on modules which have been explicitly joxified.

**Comment by AeroNotix** [comment]
Kebab-case is much nicer to use than underscores in lisp functions.

Not to mention that some LFE functions/wrappers themselves use kebab-case, such as `include-lib`.

**Comment by oubiwann** [comment]
Closing ...

**Comment by AeroNotix** [comment]
Cool! Did this get fixed?
