### ISSUE TITLE
erl and lfe handle unicode strings differently

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#124]
The following works as expected using the Erlang shell:

``` bash
$ erl
```

``` erl
1> "\xdcML\xc4\xdcTS!".
"ÜMLÄÜTS!"
2> "\xdcML\xe4\xdcTS!".
"ÜMLäÜTS!"
```

However, `lfe` doesn't have the same behaviour:

``` bash
$ lfe
```

or

``` bash
$ lfe +pc unicode
```

``` cl
> "\xdcML\xc4\xdcTS!"
"xdcMLxc4xdcTS!"
> "\xdcML\xe4\xdcTS!"
"xdcMLxe4xdcTS!"
```

This was noticed when attempting to run the same unit tests in Erlang and LFE (the Erlang ones passed, but the LFE ones failed; for full context, see this discussion: https://github.com/lfex/xlfe/commit/9914a4bc268049a14a1b0f88a7b7c034bb27a59c#commitcomment-12121320)

**Comment by yurrriq** [comment]
:+1:

**Comment by rvirding** [comment]
The reason for this is that the LFE string syntax is different from erlang's. In LFE in a string the \x sequence must end with a ; so it would should be:

```
> "\xdc;ML\xe4;\xdc;TS!"
"ÜMLäÜTS!"
> "\xdc;ML\xc4;\xdc;TS!"
"ÜMLÄÜTS!"
```

This, and the #\x character syntax comes from R6RS scheme. I haven't really found a CL equivalent.

**Comment by oubiwann** [comment]
Perfect! Thanks for this, Robert ... really good to know. (It's going in the book for sure :-))

**Comment by yurrriq** [comment]
[`CL-INTERPOL`](https://github.com/edicl/cl-interpol) might be of interest. See also: http://weitz.de/cl-interpol/
