### ISSUE TITLE
lfec expects lfe to be in the PATH

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#132]
`lfec` now has the following script header:

```
#! /usr/bin/env lfe
```

I sometimes don't have `lfe` in my `$PATH`, in which case this fails. This is a different behaviour from `lfe` (necessarily, since `lfec` is now written in LFE).

If we are making the installation of LFE a requirement, we should document this. And put it on the project `README`.

**Comment by rvirding** [comment]
Well LFE has to be there. How else could it find it? I suppose one option that may occur is if LFE is a dependency so it should search in a deps directory but even then it would have to find an `lfec` which can find itself or perhaps try and call the compiler directly. In either we couldn't write `lfec` in LFE, it would have to be a shell script or a C program.

We should document it.

**Comment by arpunk** [comment]
This is related to a bootstrapping problem on machines that rely on the `erlc` and `lfec` make targets. In that special case I ended up tweaking the `$PATH` in the Makefile: 

``` diff
@@ -65,7 +65,7 @@ $(EBINDIR)/%.beam: $(SRCDIR)/%.erl
        $(ERLC) -o $(SRCDIR) $<

 $(EBINDIR)/%.beam: $(LSRCDIR)/%.lfe
-       $(LFEC) -I $(INCDIR) -o $(EBINDIR) $(LFECFLAGS) $<
+       PATH=$(PWD)/bin:$(PATH) $(LFEC) -I $(INCDIR) -o $(EBINDIR) $(LFECFLAGS) $<
```

This is needed to find `lfec` and compile `cl.lfe`. I've only seen this on FreeBSD using gmake.

**Comment by yurrriq** [comment]
Is this fixed now?

**Comment by rvirding** [comment]
I have another fix for this which seems to work:

```
LFECFLAGS = -pa ../lfe
LFEC = $(BINDIR)/lfe $(BINDIR)/lfec

$(EBINDIR)/%.beam: $(LSRCDIR)/%.lfe
        $(LFEC) -I $(INCDIR) -o $(EBINDIR) $(LFECFLAGS) $<
```

It is in the current versions.

**Comment by yurrriq** [comment]
This has worked for me for some time now. Unless @oubiwann or @arpunk disagree, I think this can be closed.

**Comment by oubiwann** [comment]
Fixed; closing.
