### ISSUE TITLE
Allow non-ASCII non-letters in symbols?

### ISSUE THREAD

**Issue by hdurer** [lfe/lfe#133]
I assume lfe source files are assumed to be UTF-8 and you can now write `#"Smörgåsbord"` and `'Smörgåsbord` which is great.
I can also use `foo->bar` as a symbol and thus as a function name.

However, I cannot use `foo→bar` as a symbol or function name.

**Comment by hdurer** [comment]
hmmm... I see that it's not a letter vs symbol problem.  
This symbol is also invalid: `'ＬＦＥ` 
Even latin-3 letters are invalid, e.g. `'ĉiutaĵo` 

So, is it only latin-1 characters that are explicitly allowed?

**Comment by oubiwann** [comment]
iirc, when I asked something similar, the limitation is in Erlang -- and that when they get it, we'll get it.

@rvirding, is that correct, or is my memory failing me?

**Comment by rvirding** [comment]
There are two problems here: what the scanner accepts as symbol/atom characters; and what the underlying erlang accepts. Erlang currently only accepts Latin-1 characters in atoms, they are moving towards full unicode atoms but have not officially said when. The LFE scanner also accepts the full Latin-1 one range **except** for the control characters 00-20 and 7f-9f and []{}";#`'| and space.

**Comment by rvirding** [comment]
We can close this for the time-being until the BEAM can handle full utf-8 atoms.
