### ISSUE TITLE
Allow guard expression on single-pattern defun form?

### ISSUE THREAD

**Issue by hdurer** [lfe/lfe#134]
I can use guards with the multi-pattern defun form:

```
(defun foo
    "Doc string"
    ([x] (when (is_integer(x))) 'integer)
    ([x] (when (is_list(x))) 'list))  
```

But I cannot use a guard expression with the single-pattern defun form:

```
(defun foo [x]
    "This is invalid"
    (when (is_integer(x)))
    ;; Here it's save to assume is an integer and other invocations fail cleanly and early
    ;; ....
    x)
```

Obviously guard expressions are far more useful with the multi-pattern defun but it seems surprising that they are not supported in the simpler form.

**Comment by useronym** [comment]
> ```
> (defun foo [x]
>     "This is invalid"
>     (when (is_integer(x)))
>     ;; Here it's save to assume is an integer and other invocations fail cleanly and early
>     ;; ....
>     x)
> ```

As I have said in #lfe, the issue here is that '(when ...' will be
interpreted as the function body. I suppose you could add a special
parser rule that would correctly parse it as a guard sequence, but I'm
not sure the fairly minor use case here is worth the added complexity.

For me, this doesn't seem like an idiomatic way to write code, but I
suppose there would be no harm in allowing such a defun form.

**Comment by oubiwann** [comment]
@osense is correct -- that's the reason.

**Comment by rvirding** [comment]
Yes, the reason is that it very rarely occurs, at least in my code, so I didn't bother with it. It would be no problem to add it.

**Comment by yurrriq** [comment]
I vote mildly against adding the special parser rule.

The explicitness of `(defun foo ([x] (when (is_integer x)) x))` is preferable to me. Though `when/1` is not a function, so there's no ambiguity..

PS I get a `function_clause` error on `(is_integer(x))`.

**Comment by rvirding** [comment]
Do you mean when you use `(is_integer x)` or `(is_integer(x))`? And in a `when` guard or in the body? If it is the first in a guard then that is what it is supposed to do. A guard never generates an exception it just fails that clause and if not clause matches you get a `function_clause` error. So doing:

```
> (defun f ([x] (when (is_integer x)) x))
f
> (f 'a)
exception error: function_clause
```

just meant that the guard failed and no clause matched.

**Comment by yurrriq** [comment]
I meant `(is_integer(x))` in a guard as in the original post, even when passing the function an integer. I'm assuming it was just a typo and meant to be `(is_integer x)`.

**Comment by rvirding** [comment]
It is a typo, if I try to compile the original functions I get:

```
./f.lfe:2: illegal guard
```

as `x` is not a legal guard function. I agree with you and will leave it as it is for the time-being until someone really complains about it not being there.
