### ISSUE TITLE
mref should evaluate the key argument

### ISSUE THREAD

**Issue by hdurer** [lfe/lfe#136]
This came up in https://gist.github.com/yurrriq/747b6195b43755da4aec 

It seems that `mref` doesn't evaluate the argument `Key`and I don't see why this would be a useful feature.

The same seems to be true about `mset` and `mupd`

**Comment by rvirding** [comment]
OK, to start, with the longer `map-get`, `map-set` and `map-update` forms have short alternative forms `mref`, `mset` and `mupd` respectively which are **exactly equivalent** and behave in exactly the same way. The short forms are loosely based on the CL array referencing forms. You can use either. The emacs LFE mode recognises both sets.

In Erlang 17 when using the **map syntax** the key had to be a literal value. This was not just syntax but an implementation issue which there was no way around so I had to mirror this in LFE. I did this by having a syntax which in principle would allow any type of key, even those containing variables, but for now only allowing literal values. So some values have to be quoted, like the atoms `b` and `c` in your example.

The function `maps:get/2` is an explicit function call which allows any keys containing variables and LFE does the same, which why you could call `maps:get` the way you did in your example.

It seems like in Erlang 18 keys no longer have to be literals in expressions but they still must be literals in patterns. I will check this and if so adjust the system. At least when running 18.

One issue would be whether to change the forms so the map comes as the last argument and not first as it is now. It would be cleaner and more consistent but it is probably too late to change.

Robert

**Comment by hdurer** [comment]
I don't understand how this comment relates to the issue raised, so I am not sure if I am missing something  in my understanding of the problem context or if I just badly worded the issue.

In case it is the latter, let me try to rephrase this.  All this bug is meant to say is that this:

```
(let* ((map #m("a" 1))
       (key "a"))
  (list
   (maps:get "a" map)
   (maps:get key map)
   (mref map "a")
   (mref map key)))
```

be a valid expression which returns a list of four identical values (1).

At the moment this is not valid, and fails with `exception error: illegal_mapkey` because of the last list item where the `mref`macro doesn't evaluate the `key` argument.

**Comment by yurrriq** [comment]
Ah, thanks, Robert.

> It seems like in Erlang 18 keys no longer have to be literals in expressions but they still must be literals in patterns.

My gist is based on my experience running 18.

``` bash
$ erl -noshell -eval 'erlang:display(erlang:system_info(otp_release)).' -s erlang halt
"18"
```

However, when I activate 17.5 via [kerl](https://github.com/yrashk/kerl),

``` bash
$ erl -noshell -eval 'erlang:display(erlang:system_info(otp_release)).' -s erlang halt
"17"
```

I'm still seeing the same behaviour, i.e.

``` lfe
> (set m #m(a 1 b (2 3 4) c #(a b)))
#M(a 1 b (2 3 4) c #(a b))
> (set x 'a)
a
> (mref m 'a)
1
> (map-get m 'b)
(2 3 4)
> (mref m x)
exception error: illegal_mapkey

> (map-get m x)
exception error: illegal_mapkey

> (maps:get x m)
1
> (maps:get 'c m)
#(a b)
```

What's more, it looks like 17.5 is ok with non-literal map keys too. :confused:

> One issue would be whether to change the forms so the map comes as the last argument and not first as it is now. It would be cleaner and more consistent but it is probably too late to change.

Personally, I like the options and actually prefer `(fun map key)` over `(fun key map)`, almost undoubtedly due to Clojure's tendency to order arguments that way.

**Comment by yurrriq** [comment]
On 17.3, since I have it on my system:

``` lfe
> (set m (map "testing" 123))
#M("testing" 123)
> (mref m "testing")
123
> (set k "testing")
"testing"
> (mref m k)
exception error: illegal_mapkey

> (maps:get k m)
123
```

Maybe I don't understand the issue as well as I thought I did...

**Comment by oubiwann** [comment]
@hdurer I'm not sure what to say that Robert didn't already -- his explanation really did answer your question. Perhaps if you let us know how each part of his answer doesn't relate to the question? Maybe walking through it like that will make things more clear ...

In the mean time, I can give a summary a go:

In Erlang 17 with LFE, you can't use a key that that you expect to be evaluated when calling with the various map macros:

``` cl
$ . /opt/erlang/17.5/activate
$ ~/lab/lfe/lfe/bin/lfe
> (set my-var 'a)
a
> (map my-var 123)
exception error: illegal_mapkey
```

This had to do with limitations in Erlang 17.x:

``` erlang
1> MyVar = a.
a
2> #{MyVar => 123}.
* 1: illegal use of variable 'MyVar' in map
```

In Erlang 18, this limitation is no longer present:

``` erlang
1> MyVar = a.
a
2> #{MyVar => 123}.
#{a => 123}
```

In order to use a key which you would expect to be evaluated with the `map` macro, Robert will need to make some changes to LFE when combined with Erlang 18. At that point, you will see the same results when using the various map macros, the raw map syntax, and the functions in `maps:*`.

**Comment by hdurer** [comment]
I think my problem in understanding is grokking what  `mref` is supposed to do.
To me it is just the same as `maps:get`.  Give it a map and a key and it looks up that key in the map.  In fact, that seems to basically be what lfe will expand its use into.

I don't see how accessing an element in a map is affected by questions how maps can be constructed which is why the whole excursion into map literals restrictions seemed to bizarre to me.

**Comment by rvirding** [comment]
`mref` (and `map-get`) are slightly different from `maps:get` in that they are, or are supposed to be, native operations in the same way as `map`, `mset` and `mupd` are native operations. They are not calls to functions but are implemented natively in the machine. As such in 17 they had the limitation that the keys must be literal values. This limitation has been lifted in 18 for constructing and updating so I will do that as well. For matching the keys must still be literals.

I will fix it soon. Must check how it is done in 18 and sure we don't get any strange effects in 17.

**Comment by yurrriq** [comment]
Assume `(set k "testing")` for each example below.

I'm able to use `k` as a key in `maps:from_list/1` on 18.0:

``` lfe
> (erlang:system_info 'otp_release)
"18" ; 18.0
> (maps:get k (maps:from_list `(#(,k 123))))
123
> (mref (maps:from_list `(#(,k 123))) k)
exception error: illegal_mapkey
```

Similarly, I have no trouble using `k` as a key with `maps:from_list/1` on 17.5. Maybe it only works because of the backquoting. I'm getting more confused.

``` lfe
> (erlang:system_info 'otp_release)
"17" ; 17.5
> (is_map `(map ,k 123))
false
> (is_map `#m(,k 123))
true
> (maps:get k `#m(,k 123)))
exception error: bad_key
  in (: maps get "testing" #M(,k 123))
> (maps:get k (maps:from_list `(#(,k 123))))
123
```

If I understood correctly, the following shouldn't work on 17.x, but it seems to.

``` lfe
> (erlang:system_info 'otp_release)
"17" ; 17.3
> (maps:get k (maps:put k 123 (maps:new)))
123
```

``` erlang
1> erlang:system_info(otp_release).
"17" % 17.3
2> Key = "testing".
"testing"
3> maps:get(Key, maps:put(Key, 123, maps:new())).
123
4> X = "example".
"example"
5> Key2 = X.
"example"
6> maps:get(Key2, maps:put(Key2, 123, maps:new())).
123
```

Can someone help me understand what's going on here? Is 17.3 "too new" to exhibit the map key restriction?

**Comment by mqsoh** [comment]
Erlang 17 had this limitation:

```
1> Key = "foo".
"foo"
2> #{"foo" => "bar"}.
#{"foo" => "bar"}
3> #{Key => "bar"}.  
* 1: illegal use of variable 'Key' in map
```

There are _other_ ways variable keys are a problem, but let us just say that maps were incomplete in Erlang 17.

LFE's map macros were coded with this limitation in mind.

Erlang 18 fixed maps. Robert needs to update the LFE macros and said he'll do that soon. After he fixes it, maps will work how you want.

**Comment by yurrriq** [comment]
So in Erlang 17, the limitation was in map literals? Why do the examples in my previous comment work, even on 17.3?

**Comment by mqsoh** [comment]
I don't think it was just map literals -- I can't quite remember what it was. All I know is the I wrote code that had to use `maps:get` when it was inconvenient and annoying.

Your previous example works because all the **functions** in the maps module are good. Other stuff was bad.

(Sorry about the lack of detail. I don't feel like looking up the issue because it's fixed in Erlang 18 and Robert will fix LFE soon and we can forget about the halfway map implementation.)

**Comment by yurrriq** [comment]
👍 Makes sense. Thanks, @mqsoh!

**Comment by mqsoh** [comment]
You're welcome, @yurrriq. :)

**Comment by rvirding** [comment]
I am working on this and should have the first version out Real Soon Now. They have changed how the calls are handled internally which took a little bit of figuring out and I need to make sure it still works with R16, 17 and 18.

Robert

**Comment by yurrriq** [comment]
After a few cursory tests, it looks good to me.

#### a1b327e01ca223d213fc1ad29e6b2fd77858ba5d

``` lfe
> (let ((x "testing")) (map x 123))
#M("testing" 123)
> (let ((x "testing")) `#m(,x 123))
#M("testing" 123)
> (let ((x "testing")) (mref `#m(,x 123) x))
123
```

#### v0.9.2

``` lfe
> (let ((x "testing")) (map x 123))
exception error: illegal_mapkey

> (let ((x "testing")) `#m(,x 123))
#M(,x 123)
> (let ((x "testing")) (mref `#m(,x 123) x))
exception error: illegal_mapkey

```

**Comment by yurrriq** [comment]
I'm having a similar issue with `#b(some-var ...)`. Will make a gist/writeup. Possibly tomorrow. Getting sleepy.

**Comment by yurrriq** [comment]
Cursory example:

``` lfe
> (binary "test" "ing")
#"testing"
> #b("test" "ing")
#"testing"
```

``` lfe
> (set s "test")
"test"
> (binary s "ing")
exception error: badarg
  in lfe_eval:eval_int_bitseg/4 (src/lfe_eval.erl, line 290)
  in lfe_eval:-eval_bitsegs/2-fun-0-/3 (src/lfe_eval.erl, line 251)
  in lists:foldl/3 (lists.erl, line 1262)

> #b(s "ing")
1: bad binary
> `(binary ,s)
(binary "test")
> `#b(,s)
1: bad binary
```

``` lfe
> (binary (#"test" binary) "ing")
#"testing"
> #b((#"test" binary) "ing")
#"testing"
```

``` lfe
> (set b #"test")
#"test"
> (binary (b binary) "ing")       ; This is the general form of my solution for now.
#"testing"
> #b((b binary) "ing")
1: bad binary
> `#b((,b binary) "ing")
1: bad binary
> `(binary (,b binary) "ing")
(binary (#"test" binary) "ing")
```

Seems like a combination of my misunderstanding and perhaps a quoting issue similar to one we ended up fixing wrt maps here.

**Comment by rvirding** [comment]
Two things here:
- The `#b( ... )` syntax is for **literal** binaries so if you want to include values in there you must either use `(binary ... )` or the backquote which evaluates to the same thing. (how do get a ` into md?)
- If you want to include values when building a binary, either literal or "imported" then you must explicitly tag it with its type.
- List strings are specially handled but binary strings are just binaries and need to tagged.
- Backquote doesn't work for `#b( ... )`. For the macro expansion to work you must first be able to create the literal which you then transform.

```
> #b(1 2 3)
#B(1 2 3)
> #b(1 (2.2 float) 3)
#B(1 64 1 153 153 153 153 153 154 3)
> (set f 1.2345)
1.2345
> (set b #"foo")
#"foo"
> (binary (b binary) (f float))
#B(102 111 111 63 243 192 131 18 110 151 141)
> (binary (b binary) (f float (size 32)))
#B(102 111 111 63 158 4 25)
> (binary (b binary) "123")
#"foo123"
(binary (b binary) #"123")             
exception error: badarg
  in lfe_eval:eval_int_bitseg/4 (src/lfe_eval.erl, line 290)
  in lfe_eval:-eval_bitsegs/2-fun-0-/3 (src/lfe_eval.erl, line 251)
  in lists:foldl/3 (lists.erl, line 1262)
> (binary (b binary) "123")
#"foo123"
```

**Comment by yurrriq** [comment]
I see. So for pattern-matching do I need to use `(binary ...)` instead of `#b(...)` too?

**Comment by rvirding** [comment]
Yes, currently anyway.

**Comment by yurrriq** [comment]
:+1: For backquoted `#b(...)` in patterns!

**Comment by yurrriq** [comment]
I'm pretty sure this can be closed.
