### ISSUE TITLE
Support writing command history to disk

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#139]
Right now, if you would like to later re-run a REPL session (prototyping, writing tutorials, teaching a class, a student taking notes, etc.), you need to copy each command you executed in the REPL and paste it into a file. It would be nice if a single command could replace all that labor-intensive copying/pasting.

This would be the inverse operation of `(run)`, essentially.

Needed:
- Tracking previous commands (ets or dets) (see issue #140)
- Name: maybe `dump`? (`spew` would be the inverse of `slurp` ... but we're not creating modules with this command, so that wouldn't be a good fit -- though that would be a cool feature, too!)

Proposed usage:

``` cl
> (dump "my-session.lfe")
#(ok "my-session.lfe")
```

**Comment by yurrriq** [comment]
`spit`

**Comment by yurrriq** [comment]
Checking in on this. Just thought of `barf` to mimic the paredit commands.

**Comment by oubiwann** [comment]
Erlang supports this now (enabled with an env var). It's been a godsend.
