### ISSUE TITLE
Write command history to (D)ETS

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#140]
In support of issue #139, it would be nice to regularly write the command history to either memory or disk. `lfe` could even take a new option to indicate either DETS (probably good for the default) or ETS (if you don't care about persisting between sessions).

This would require:
- identifying a place on the filesystem to store the data (e.g., `~/.lfe/repl.history`)
- naming the table (e.g., `lfe_repl_history`)
- creating convenience functions/a history API for internal use by LFE

**Comment by yurrriq** [comment]
👍👍 for this.

**Comment by oubiwann** [comment]
No need for this anymore, with Erlang's support for readline history.
