### ISSUE TITLE
Use lfeexec when starting instead of lfe script

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#143]
This is a follow-on to issue #138. Fix `lfeexec.c` so that it works on both Unixes and Windows and then use it to start erlang instead of doing the work in the `lfe` bash script. If we did it this way then we only need very simple scripts which set some shell variables and then call `lfeexec`. Doing it this should make it easy to start from windows as well as all you would need would be a simple `lfe.cmd` or `lfe.bat`.

**Comment by oubiwann** [comment]
:+1:

**Comment by oubiwann** [comment]
Lots of amazing changes since then, and the `lfe` executable has gone through several excellent iterations :-) 

Closing ... 

(we can re-open if I'm wrong)
