### ISSUE TITLE
Deprecated pattern warning on empty string

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#144]
I'm pretty sure I have a scenario where I'm getting an invalid deprecated pattern warning: it happens when pattern matching on an empty string in function heads.  

I'm guessing the code that's checking for the deprecated use doesn't take into account that an unquoted`""` is a valid expression, even though it will be rendered as `()` (a deprecated one).

**Comment by rvirding** [comment]
I thought I had fixed that. Which version are you using? I will check it out and fix it.

**Comment by rvirding** [comment]
This should not be a problem anymore. I am closing the issue, reopen it if the problem arises again.

**Comment by oubiwann** [comment]
Ah, sorry -- I meant to reply. I ran into this in 0.9.2. I'll try against develop ...

**Comment by oubiwann** [comment]
Hurray!

I just confirmed that this issue is addressed in develop. Thanks!

**Comment by rvirding** [comment]
No worries. This just shows I need to make a new commit to master and a new
release as well.

**Comment by oubiwann** [comment]
:+1:  -- I'll do a new release of lfetool after that. Really looking forward to having new `lfetool`-generated projects pull in the latest :-)
