### ISSUE TITLE
Support for headless LFE REPL/shell servers

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#153]
I have two separate needs for an LFE server: 
1. as part of the try.lfe.io project, and
2. as a backend for IPython/Jupyter

Having an LFE server I could start up and then send code to, with the server tracking the LFE environment (state), would make my life much easier :-)

I have a first draft implementation of this done and I will submit a PR for review.

**Comment by rvirding** [comment]
You are duplicating part of the interface to the existing shell process. Let me look at it a bit and see if I can integrate them. It also depends how you want to handle errors. I think.

**Comment by jjl** [comment]
Hi folks, I'm just checking in to see how these changes are going. I'm building an integrated build tool for lfe and an nrepl-alike would be very handy. Is anything currently usable? Where would I pick up to contribute to it?

**Comment by oubiwann** [comment]
There's an open PR for this here: #154, but it needs more discussing with Robert. I'm going to mark this as blocked for now ...

**Comment by oubiwann** [comment]
I closed that PR, due to its age and the on-going development Robert has put into the LFE REPL.

Keeping this ticket open to rethink an approach that takes that work into consideration.

**Comment by oubiwann** [comment]
This has come up several times (from other community members) since this ticket was created. In fact, it comes up every time we get a Clojure dev interested in LFE :-D 

In a conversation on the LFE Discord today, it became clear that we just needed to do like the Clojure community has done and maintain something outside of LFE proper where we can experiment, explore use cases, and if we come up with anything good or useful for LFE itself, we can open tickets/PRs on a case-by-case basis. 

There are a lot of ideas explored in the past that were always going to be a bit too heavy/radical for LFE itself, so this direction really makes sense. I'm honestly confused as to why we didn't do this sooner?! 😆 

The new project is linked above, but I'll put one here, too:
* https://github.com/lfe/xrepl

Given all this, I think we can finally close this ticket! (it's one of the oldest still-open LFE tickets ...)
