### ISSUE TITLE
Makefile $PATH issue

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#171]
On b0921aacf954e68689c181ec1c4651b02dc51855, I'm getting:

```
Makefile:14: *** Recursive variable `PATH' references itself (eventually).  Stop.
```

**Comment by yurrriq** [comment]
Looks like it was introduced [here](https://github.com/rvirding/lfe/commit/93c1d33de3c5971e891a91769715b097efd243b3#diff-b67911656ef5d18c4ae36cb6741b7965R14) in 93c1d33de3c5971e891a91769715b097efd243b3.

**Comment by oubiwann** [comment]
Yeah, I've run into that in other projects; curious that testing didn't reveal the issue :-/

Easy enough fix: I'll submit a PR.

P.S.: Like the new profile pic :-) :+1:

**Comment by yurrriq** [comment]
Without testing, I'm reasonably certain #172 solves this, so I'm closing it until proven wrong.
