### ISSUE TITLE
Scoping is rather peculiar...

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#187]
In a shell, define a silly function, `f/1`, that takes an `x` and returns the free variable, `y`.

``` lfe
> (defun f (x) y)
f
```

Bind local variables `x` and `y` to `'undefined` and `42`, respectively.

``` lfe
> (let ((x 'undefined)
        (y 42))
    (f x))
```

The result of the previous form is unexpected...

``` lfe
42
```

---

When I try to compile a module (say `example.lfe`) with the `f/1` above, I get an error and it preventing me from experiencing this peculiar scoping.

``` lfe
> (c "example.lfe")
./example.lfe:4: unbound symbol: y
error
```

Perhaps we should check for free variables and prevent functions referring to them from being defined in a shell.

**Comment by rvirding** [comment]
Perhaps. I tend to view it that the functions are all defined inside an environment containing function and macro definitions, and variable values. Like they were all defined in a dynamic fletrec. It needs to be dynamic otherwise the shell would be too static to be useful.

Currently all checking is done at run-time and the evaluator in lfe_eval doesn't trim away variables when calling a function. It is a bit inconsistent with functions in modules but rather practical.

**Comment by yurrriq** [comment]
Cool. I support that and also the fact the such functions don't compile when written in files is good enough for me. Cheers.

**Comment by wobh** [comment]
Sort of off-topic but in Common Lisp the first `let` statement raises an error even in the shell, but you could `(declare (special y))` either in the function or in the `let` body and then it outputs `42` just as here. I don't know what LFE or Erlang will allow for what Common Lisp calls "dynamic extent/lexical scope" but I'm coming to appreciate it as one of CL's most profound features. I wouldn't feel comfortable suggesting that LFE do exactly what CL does here (even if possible), but whatever LFE can do about regulating and documenting the dynamic and lexical effects would help LFE programmers immensely in the long haul.

**Comment by rvirding** [comment]
The problem in LFE that having a `(declare (special y))` form would only work in the REPL. In compiled LFE code there is no provision for dynamically scoped variables and there is no support for it in Erlang. It would be a significant modification to LFE to add it and it would make interfacing Erlang much more complex.

One thing we could do however is to support `defparameter` and `defvar` at the top module level. I know of a cunning sneaky way to do this. However it is actually adding global variables to LFE which Erlang doesn't really support.

Erlang doesn't do global or sharing.
