### ISSUE TITLE
Possible regression for Erlang 17.x

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#191]
I've been seeing the following errors during compile tonight when using Erlang 17:

```
$ make compile
```

```
...
Compiled src/lfe_user_macros.erl
src/lfe_env.erl:154: illegal use of variable 'N' in map
src/lfe_env.erl:157: illegal use of variable 'N' in map
src/lfe_env.erl:187: illegal use of variable 'N' in map
src/lfe_env.erl:187: illegal use of variable 'N' in map
src/lfe_env.erl:264: illegal use of variable 'N' in map
src/lfe_env.erl:267: illegal use of variable 'N' in map
Makefile:78: recipe for target 'compile' failed
make: *** [compile] Error 1
```

The last commit that doesn't fail on Erlang 17 (for me) is db084eab6da293655a2dc3fb092fd5829c1ea3bd, indicating that the commit which introduced the regression was d19bf474b8b4a8f397581e0ba8c68f59dbb2eb40.

**Comment by yurrriq** [comment]
There were some improvements in 17.3 or 5 I think. Which version are you running?

**Comment by oubiwann** [comment]
I have many different versions of Erlang installed -- most managed with kerl. The version of 17 that I experienced this problem was erts 6.2 (17.2).  I can't remember where I got it ... I'm running Ubuntu 15.04, but the version of Erlang that comes with that is 17.3, according to Launchpad ...

**Comment by yurrriq** [comment]
It might have been 17.5 where they started evaluating map keys..

**Comment by yurrriq** [comment]
Related: https://github.com/rvirding/lfe/issues/136

**Comment by rvirding** [comment]
Yes, sorry this is my fault. I don't make the necessary distinction of whether you are running Erlang 17 or 18. I will fix that today or tomorrow and commit a fix in develop.

Officially evaluating map keys came in 18, which is at least what I assume.
