### ISSUE TITLE
Docker install fails on Windows

### ISSUE THREAD

**Issue by nubunto** [lfe/lfe#192]
```
$ docker run -i -t lfex/opensuse lfe
Erlang/OTP 18 [erts-7.2] [source-e6dd627] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

{error_logger,{{2016,3,4},{13,7,43}},"Error in process ~p with exit value:~n~p~n",[<0.28.0>,{{badmatch,{error,enoent}},[{lfe_shell,get_lfe_version,0,[{file,"src/lfe_shell.erl"},{line,222}]},{lfe_shell,get_banner,0,[{file,"src/lfe_shell.erl"},{line,211}]},{lfe_shell,server,1,[{file,"src/lfe_shell.erl"},{line,99}]}]}]}
*** ERROR: Shell process terminated! (^G to start new job) ***

=ERROR REPORT==== 4-Mar-2016::13:07:43 ===
Error in process <0.28.0> with exit value:
{{badmatch,{error,enoent}},
 [{lfe_shell,get_lfe_version,0,[{file,"src/lfe_shell.erl"},{line,222}]},
  {lfe_shell,get_banner,0,[{file,"src/lfe_shell.erl"},{line,211}]},
  {lfe_shell,server,1,[{file,"src/lfe_shell.erl"},{line,99}]}]}
```

Followed instructions from [the quick start](https://lfe.gitbooks.io/quick-start/content/1.html).
What am I missing?

**Comment by nubunto** [comment]
Oops. My bad.
Running `docker pull lfex/lfe` works.

**Comment by oubiwann** [comment]
Actually, I was seeing this locally last night on certain builds under as-yet undetermined circumstances. I'm going to keep this open and make it a bit more general.

Good timing ;-)

**Comment by nubunto** [comment]
Thanks!

**Comment by oubiwann** [comment]
Once the PR that fixes this gets merged, I'll regenerate all the Docker images and we will be golden.

**Comment by oubiwann** [comment]
Okay! v1.0 is out, and I'll be building new Docker images tonight! 

I'll test out the new images and update this ticket with the results.

**Comment by oubiwann** [comment]
This is working for me, now -- not getting these errors any more, due to the Docker updates and rebar removal.

@rvirding or @nubunto: feel free to close this ticket :-)

**Comment by nubunto** [comment]
Great! Thanks for the support!
