### ISSUE TITLE
Touch up new banner

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#193]
In terminals without the classic green on black, the new LFE banner has a non-green mug. Let's make it green.

Though it's not easy, Kermit would approve.

This is a follow-up to #116.

**Comment by oubiwann** [comment]
I'm working on this now (and after lunch :-)) I will test on normal black text/white background as well as the dark terminals. I'll use green bold ANSI for the mug.

**Comment by yurrriq** [comment]
:+1: :frog: :+1:

**Comment by oubiwann** [comment]
![kermit-quote](https://cloud.githubusercontent.com/assets/894251/13550405/a85accce-e2e2-11e5-9c8a-85af78affd1e.jpg)

**Comment by oubiwann** [comment]
Alrighty, I've got two different branches for this -- one that just makes the outline bold green (I think I prefer this one), and the other that uses a green background color on the mug (except for the borders). 

The latter is a little too blocky for my taste, but if everyone else liked it, I could live with it :-)

Here are some screenshots of the first branch results (more notes after the screenshots):
![screen-1](https://cloud.githubusercontent.com/assets/894251/13550441/4cf03594-e2e3-11e5-935c-35731016bce0.png)

![screen-2](https://cloud.githubusercontent.com/assets/894251/13550443/61e970be-e2e3-11e5-93bb-f3a791623e9d.png)

Here are some screenshots of the second branch results:

![screen3](https://cloud.githubusercontent.com/assets/894251/13550464/0f668916-e2e4-11e5-8798-9ed2e39b4557.png)

![screen4](https://cloud.githubusercontent.com/assets/894251/13550469/19bd6830-e2e4-11e5-95bb-d46acf61ea69.png)

I tried multiple configurations of the background green ... none of them turned out too well. The corner characters `.` and `'` made it too blocky, and if the top-most and bottom-most bits _didn't_ have the background, there were biggish gaps that looked much worse. What I've shown above is the best result I was able to come up with :-/

**Comment by yurrriq** [comment]
My preference is the former with bold outlines.

**Comment by rvirding** [comment]
I also definitely prefer the bold green outline with the default background. The background green did not turn out well.

**Comment by oubiwann** [comment]
Okay, will submit a PR. If the bold green outline is too light against the white terminal, we could always keep the one that is currently merged to `develop` (a non-coloured outline).

**Comment by oubiwann** [comment]
Closing this, now that the related branch was merged.
