### ISSUE TITLE
Bug in version-getting function

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#195]
The new version-getting function currently only works when LFE is run from the same directory where it is built. If LFE gets installed on the system, the following error occurs:

```
$ lfe
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:2:2] ...
```

``` erlang
*** ERROR: Shell process terminated! (^G to start new job) ***
{error_logger,{{2016,3,10},{14,35,39}},
 "Error in process ~p with exit value:~n~p~n",
 [<0.28.0>,
  {{badmatch,{error,enoent}},
  [{lfe_shell,get_lfe_version,0,[{file,"src/lfe_shell.erl"},{line,215}]},
   {lfe_shell,get_banner,0,[{file,"src/lfe_shell.erl"},{line,206}]},
   {lfe_shell,server,1,[{file,"src/lfe_shell.erl"},{line,98}]}]}]}

=ERROR REPORT==== 10-Mar-2016::08:35:39 ===
Error in process <0.28.0> with exit value:
{{badmatch,{error,enoent}},
 [{lfe_shell,get_lfe_version,0,[{file,"src/lfe_shell.erl"},{line,215}]},
  {lfe_shell,get_banner,0,[{file,"src/lfe_shell.erl"},{line,206}]},
  {lfe_shell,server,1,[{file,"src/lfe_shell.erl"},{line,98}]}]}

```

I've just run into this on a brand-new build on CentOS and I think it is the source of the error I was seeing on Docker builds that I mentioned in  issue #192.

When commenting out the code in `lfe_shell:get_lfe_version` and instead returning a simple atom, a rebuild, re-install, and start-up of LFE succeeds. Then, running the function in question from LFE shows the problem (or symptom):

``` lisp
> (code:where_is_file "lfe.app")
non_existing
```

I was under the mistaken assumption that, since the libs are available to the LFE executable, the `app(.src)` file would be too. Currently looking into this.

**Comment by oubiwann** [comment]
Hrm:

```
> (application:load 'lfe)
#(error #("no such file or directory" "lfe.app"))
```

**Comment by oubiwann** [comment]
Ah -- this system doesn't have `rebar` on it, so it uses the `make`-only build process. It seems that the `make`-based build doesn't copy the `.app.src` file over. Submitting branch ...

**Comment by rvirding** [comment]
No, the src/lfe.app.src ==> ebin/lfe.app is a rebar thing which erlang.mk also fixes. We need a good way of handling that, or at least make sure the shell doesn't crash if it can't find the file.

**Comment by arpunk** [comment]
I was going to report this same bug. It's currently bitting me on FreeBSD. Surprisingly, my local GNU/Linux installation doesn't show this error.

**Comment by rvirding** [comment]
It depends on which version you are running and how you built it. If you built LFE with rebar then it will create the right file for you, ebin/lfe.app, or if you are using a version of LFE from before 4 Feb then it works. We are fixing this at the same time as making it all not use rebar by default.

**Comment by oubiwann** [comment]
Done and DONE! LFE v1.0 is out! :heart:  :fireworks: 

Ponies and rainbows for everyone!!!

 :horse: :horse: :horse: :rainbow:  :rainbow:  :rainbow:
