### ISSUE TITLE
Fix build errors on Travis CI

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#199]
I run Travis CI for my LFE branches in order to check on whether LFE builds on various versions.

For a long while, LFE has been failing its builds and I'd like to get these addressed before the v1.0 release of LFE.

**Comment by oubiwann** [comment]
Branch for this is here:
- https://github.com/oubiwann/lfe/tree/fix-travis-errors

**Comment by oubiwann** [comment]
R15B03 and R16B03 are failing on the same thing:
- https://travis-ci.org/oubiwann/lfe/jobs/115453520
- https://travis-ci.org/oubiwann/lfe/jobs/115453521

```
erlc -I include -o ebin  -W1 src/lfe_io_pretty.erl
src/lfe_io_pretty.erl:56: syntax error before: '('
src/lfe_io_pretty.erl:21: function term/4 undefined
src/lfe_io_pretty.erl:39: function term/4 undefined
src/lfe_io_pretty.erl:41: function term/4 undefined
src/lfe_io_pretty.erl:43: function term/4 undefined
src/lfe_io_pretty.erl:114: function term/4 undefined
src/lfe_io_pretty.erl:159: function term/4 undefined
src/lfe_io_pretty.erl:172: function term/4 undefined
src/lfe_io_pretty.erl:175: function term/4 undefined
src/lfe_io_pretty.erl:238: function term/4 undefined
src/lfe_io_pretty.erl:319: function term/4 undefined
src/lfe_io_pretty.erl:349: function term/4 undefined
src/lfe_io_pretty.erl:351: function term/4 undefined
src/lfe_io_pretty.erl:360: function term/4 undefined
src/lfe_io_pretty.erl:363: function term/4 undefined
```

Possibly related to the fact that this supports maps?

**Comment by oubiwann** [comment]
18.2, 18, 17.5, and 17.2 are all passing now.

**Comment by oubiwann** [comment]
Okay, I finally demolished rebar on the Travis CI server which allowed the R14B04 build to get to the point where it could compile LFE. Very similar to the issue with R15 and R16:

```
src/lfe_io_pretty.erl:56: syntax error before: F
src/lfe_io_pretty.erl:21: function term/4 undefined
src/lfe_io_pretty.erl:39: function term/4 undefined
src/lfe_io_pretty.erl:41: function term/4 undefined
src/lfe_io_pretty.erl:43: function term/4 undefined
src/lfe_io_pretty.erl:114: function term/4 undefined
src/lfe_io_pretty.erl:159: function term/4 undefined
src/lfe_io_pretty.erl:172: function term/4 undefined
src/lfe_io_pretty.erl:175: function term/4 undefined
src/lfe_io_pretty.erl:238: function term/4 undefined
src/lfe_io_pretty.erl:319: function term/4 undefined
src/lfe_io_pretty.erl:349: function term/4 undefined
src/lfe_io_pretty.erl:351: function term/4 undefined
src/lfe_io_pretty.erl:360: function term/4 undefined
src/lfe_io_pretty.erl:363: function term/4 undefined
```

@rvirding and @yurrriq: what do you guys think about doing something in the `Makefile` to copy a file into the `src` dir with and without map support for this module? (depending upon the version ...)

Looking for ideas ...

**Comment by rvirding** [comment]
I am a bit sceptical of having multiple versions of files, mainly from the maintenance point of view. In this case the easiest would be to rewrite that function so it doesn't use named funs.

I am very pleased to see that LFE can still be compiled back to R14B, I don't have that old erlangs on my machine to test with.

**Comment by rvirding** [comment]
I have just pushed a commit to develop which should fix this issue. Please test it and tell me if all is ok.

**Comment by oubiwann** [comment]
Beautiful! Look at all this green:
- https://travis-ci.org/oubiwann/lfe/builds/115873746

:-)

Thanks, Robert!

I'll submit a PR for the Travis CI config changes.
