### ISSUE TITLE
LFE v1.0 Support

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#201]
There are a bunch of tasks that various LFE projects need to do in order to support the latest release of LFE. These will be tracked here for ease-of-reporting:
- [x] Update the LFE wikipedia page
- [x] Update main LFE Docker image
- [x] Update lfex/dockerfiles Docker images
- [ ] Update all the major libraries in the lfex github org
  - [x] kla
  - [x] clj
  - [x] lutil
  - [x] ltest
  - [x] lcfg
  - [x] logjam
  - [x] ljson
  - [x] exemplar
  - [x] lhc
  - [x] lxml
  - [x] lfest
  - [x] lmug
  - [x] barista
  - [x] dragon
  - [x] moneta
  - [ ] lsci
  - [x] py
  - [ ] Draft Github releases for all of these when completed
- [x] Update all the rebar3 plugins in the lfe-rebar3 github org
  - [x] compile
  - [x] clean
  - [x] version
  - [x] test
  - [x] repl
  - [x] ltool
  - [x] Draft Github releases for all of these when completed
- [x] Update the lfe repo in the lfe github org
- [x] Submit PR for bumping the version in `VERSION` and `src/lfe.app.src`

**Comment by oubiwann** [comment]
@rvirding: Starting to hit some snags with building some of the libraries using v1.0 (looks like the macro stuff) will file bugs (even though they may not be ... I might just have to change what I'm doing).

Calling it a night, though -- will continue tomorrow as I get time.

**Comment by yurrriq** [comment]
You're stronger than I am.. My night hacking is just getting started.

**Comment by oubiwann** [comment]
Heheh. All the strength is with my wife. I'd probably been here still, drooling pooling at my feet if it wasn't for her!

**Comment by yurrriq** [comment]
Builds are working now! Once ltest is updated and we update every libs ltest dependency, tests should work too! Thanks, @oubiwann.

**Comment by oubiwann** [comment]
just finished lfe-rebar3/clean ... ltest is in the queue now ...

**Comment by yurrriq** [comment]
You're on :fire:!

**Comment by oubiwann** [comment]
:-D

Yeah, but you were the master :bug: :mag: -er! It was upon that that all of this hinged! 

Also: ltest done.

**Comment by yurrriq** [comment]
:blush::tada:

**Comment by oubiwann** [comment]
Time for a :coffee: break.

**Comment by yurrriq** [comment]
A well-earned one, too. I can confirm (if I haven't already) that all these fixes made my work code compile again :grinning:!

**Comment by oubiwann** [comment]
Woo-hoo!

Maybe next time we can talk @rvirding into doing an LFE RC, go through this process with less panic, and ensure that significant bugs get fixed before the full release. Though, to be honest, I kinda liked it this way -- it reminded me of Release Day at Canonical when we worked on Ubuntu :-)

I'm also giving thought to scripting project updates ... a job for lcfg and lcli :-)

**Comment by yurrriq** [comment]
:+1: for a RC, but also for the fun panic.

**Comment by oubiwann** [comment]
_laughs_

I'm glad it was fun for you -- last thing I'd want is to cause you trouble at work with these updates ...

**Comment by yurrriq** [comment]
It did block me for a couple hours, but the LFE system is still very much in development so there was no user-facing impact.

**Comment by logbitp** [comment]
On Ubuntu 14.04.4 LTS, the following packages need to be installed:
sudo apt-get install erlang-parsetools erlang-dev

before make compile will work.

Thanks for all for the hard work.

**Comment by rvirding** [comment]
What are you guys doing that is causing problems with 1.0? The changes I have made should only affect the new handling of macros. You must going in and hacking the internals in some way.

**Comment by oubiwann** [comment]
@logbitp Indeed! Thanks for the reminder. (These dependencies might have changed sometime in the last year ... I ran into this when debugging something for a Fedora user, actually. Didn't remember having to do that before, but who knows ...)

I need to update the quick starts/install guides.

And you are _very_ welcome for the hard work -- hopefully it leads to lots of hard play :smile:

**Comment by oubiwann** [comment]
@rvirding Yeah, it's a little bit of the internals -- see the kla project, in particular `kla.lfe`:
- https://github.com/lfex/kla/blob/master/src/kla.lfe

Basically, when generating wrapped functions (using macros) we don't want to wrapp _all_ the functions from a given module; we want to skip the stuff that Erlang adds automatically (e.g.,  `module_info`) and now the stuff that LFE adds.

When the new LFE exports were not skipped, it was causing problems -- this is the bug that Eric found so quickly last night that I wasn't having any luck with.

**Comment by yurrriq** [comment]
I feel like we took different shifts, @oubiwann. You went to bed, I found the bug, I went to bed, you fixed the bug. We make a great team :laughing:

Between all our different time zones and sleep schedules, we could almost advertise 24/7 LFE support :wink:

**Comment by oubiwann** [comment]
@yurrriq: I've updated Exemplar now, so you should be able to update Lodox. I'll regen the Exemplar project docs once you've got Lodox (and all its deps) updated to use LFE v1.0.

**Comment by yurrriq** [comment]
Sweet! I should be able to do that tonight.

**Comment by yurrriq** [comment]
@oubiwann, I'm getting the same error:

```
exception error: undef
  in (: exemplar-html-util make-html "meta" (charset "UTF-8"))
```

with exemplar 0.4.0

**Comment by yurrriq** [comment]
Putting the lodox dep in a profile in exemplar (and everywhere) should solve the issue:

``` erlang
{profiles,
 [{doc,
   [{plugins,
     [{lodox,
       {git, "git://github.com/quasiquoting/lodox.git",
        {tag, "0.12.10"}}}]},
    {lodox,
     [{apps,
       [{'my-app',
         [{'source-uri',
           "https://github.com/username/my-app/blob/{version}"
           "/{filepath}#L{line}"}]}]}]}]}]}
```

Then to generate docs, you do:

``` sh
rebar3 as doc lfe lodox
```

I think I described this poorly on the exemplar issue.

**Comment by oubiwann** [comment]
@yurrriq 0.12.9 didn't work for me, but 0.12.10 did -- thanks!

**Comment by oubiwann** [comment]
I'm going to go ahead and close this now -- most projects have been updated. the py and lsci projects may require more work, but the level of urgency there is pretty low.
