### ISSUE TITLE
InfoQ interview about LFE?

### ISSUE THREAD

**Issue by sdesimone** [lfe/lfe#208]
Sorry to use this means to get in touch. My name is Sergio De Simone and I am about to cover LFE for InfoQ. It would be great if you could answer the questions at the end of this message for inclusion within my post. You can get in touch with me directly at sergyo@gmail.com.

Please, read further down for the questions.

Thanks in advance,
Sergio

Sergio De Simone
http://www.infoq.com/author/Sergio-De-Simone

QUESTIONS:

**LFE has recently reached version 1.0, after several years of
  development. What does that mean and how would you evaluate LFE's
  stability or readyness for use in production?**

**What are the advantages of using a Lisp-like language on the Erlang
  virtual machine?** (This question also bears on the motivations that
  led to create LFE)

**Could you share some insights about LFE's roadmap? What is the pace
  of development of LFE SICP?**

**Comment by oubiwann** [comment]
Thanks, @sdesimone! We'll get back to you soon...

**Comment by sdesimone** [comment]
Thanks Duncan,
looking forward to it!

Best,
Sergio

**Comment by yurrriq** [comment]
Bump, in case this hasn't been handled privately.

**Comment by sdesimone** [comment]
Eric, thanks for getting in touch.
I have never heard back since the initial response. Still interested,
though, to cover this...
Sergio

**Comment by oubiwann** [comment]
Oh dear! @sdesimone I sent you an email from @rvirding and I to your infoq address ... did you not get it? Maybe a week or so ago?

**Comment by sdesimone** [comment]
In fact, I cannot find it anywhere... Could you please send it again? you
could send it directly to zergyo@gmail.com, which is where the InfoQ
address is forwarded to...
Thanks,
Sergio
