### ISSUE TITLE
Emacs LFE mode doesn't indent

### ISSUE THREAD

**Issue by ahjones** [lfe/lfe#209]
I've just installed lfe-mode from Melpa, opened an LFE file and tried to write some code, but the indentation doesn't work. I get the error `calculate-lisp-indent: Symbol's function definition is void: lfe-indent-function` when I press tab.

(There's a separate issue that the Melpa version of lfe-mode doesn't include `emacs/lfe-indent.el`, but I've submitted a pull request to fix that).

If I use the source of lfe-mode then I can use `(require 'lfe-indent)` to get indentation working.

I see that `lfe-indent` has recently been separated from `lfe-mode` but I'm not experienced enough with Elisp to know the idiomatic fix.

**Comment by yurrriq** [comment]
This has been patched in 168f9d05793dc67935dd75a7d721059e2ab849fa.

**Comment by yurrriq** [comment]
The commit message says it's to appease Flycheck, but the addition of `(provide 'lfe-indent)` is really to solve the error you mentioned above.

**Comment by ahjones** [comment]
Thanks for your response. I had included the patch that you referred to in the `lfe-mode` that I was using, but I now see that because the Melpa package doesn't include `lfe-start.el` the`(autoload 'lfe-indent-function)` doesn't run.

Pull request #50 added some `;;;###autoload` stanzas; I'll create a pull request that does the same for the indentation function.

**Comment by yurrriq** [comment]
Since I tend to hack on it from time to time, I don't use the MELPA package, but rather add `/path/to/lfe/emacs` to my load path. Maybe @rvirding can chime in re: pushing to MELPA.

I think before too long we'll push a 1.0.1 that will include the `lfe-indent` patch, so maybe we just wait a bit.

**Comment by rvirding** [comment]
I'm not a melpa user, as far as I know anyway. Yes, we will push it soon, there are a few small fixes I would like to add first. But the docs I am saving for 1.1 :-)
