### ISSUE TITLE
Saving documentation in the .beam file

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#211]
We are now working towards saving the module, function and macro documentation strings in the .beam file. As a first step along the way the `define-function` and `define-macro` core forms not have an extra element for the documentation strings. The macro expander now saves the documentation string from the `defun` and `defmacro` in the forms when they are expanded. The doc strings are then passed through the compiler where they are ignored except in the lint pass where they are checked that they are either list character strings or binaries.

It is @yurrriq who is doing the actual work around this.

I think the based place to get these strings is after the split pass and before the expand pass in the compiler because between these two the macro definitions are still in the code forms. After the expand pass all macros have been expanded and their definitions are no longer saved. Then they have to be saved of course which is where it starts getting interesting. :-)

You can actually comment local function and macro definitions:

```
(flet ((sune (a b)
         "The sune function."
         (* a b)))
  ...)
```

However, these comments are lost, mainly because I don't know what to do with them.

**Comment by yurrriq** [comment]
The commit has since been rebased away, but there's some discussion [here](https://github.com/yurrriq/lfe/commit/b6e72b00a57d84278bf69f518525d993b1fd0804).

**Comment by rvirding** [comment]
Yes, I made a mistake and managed to delete the initial commit :-( That is why I made an issue of it so it won't be in any commit and that won't happen again. I don't trust myself.

**Comment by yurrriq** [comment]
I think it was me aggressively rebasing :smile:

**Comment by yurrriq** [comment]
Ok, I'm getting close to resolving all the conflicts. I'm going to rework the doc parsing s.t. it only happens in a `do_docs` pass when you mentioned above. Will likely pull out the helper functions into a new module, `lfe_doc`.

**Comment by rvirding** [comment]
Would you like me to wait with Duncan's doc PR? It shouldn't affect you but who knows.

**Comment by yurrriq** [comment]
It looks safe to me.

**Comment by rvirding** [comment]
I have been thinking about the compiler. One problem with doing it after split and before the expand passes is just the expansion. The reason is that the split pass **only** expands the forms at the top-level so it can detect define-module and partition the forms into modules. Everything before the first module is copied into every module. The expand pass, however, expands everything all the way down but it removes the macro definitions.

So what could happen is that in a function defined by a `match-lambda` there might be macros in the arguments which will only be expanded in the expand pass. This will mean that your argument descriptions may be off. This does not happen if the functions is a `lambda`.

I don't know if this is a problem but if it is we can fix it later.

**Comment by yurrriq** [comment]
After [my latest efforts](https://github.com/yurrriq/lfe/tree/feature/lfe_comp-doc) (and some more rebasing :smiling_imp:), the output of [test/docs.lfe](https://github.com/yurrriq/lfe/blob/feature/lfe_comp-doc/test/docs.lfe) looks like:

``` erlang
#(lfe_docs_v1
  (#(doc macro false MODULE 0 (()) #"")
   #(doc macro true add 2 ((x y)) #"Add `x` and `y`.")
   #(doc macro true varargs 255 (args) #"This is a varags macro.")
   #(doc macro false forty-two? 1
     ((x (when (=:= x 42))) (x (when (< x 42))) (x (when (> x 42))))
     #"Return `'true` iff `x` is 42.")
   #(doc macro false tricky 255
     ((x) (x y) (x y . z))
     #"This is a tricky varargs macro.")
   #(doc function true subtract 2 ((x y)) #"Subtract `y` from `x`.")
   #(doc function true matchfun 3
     ((x y z (when (< x y) (< y z)))
      (x y z (when (> x y) (> y z)))
      (x y z (when (=:= x y) (=:= y z)))
      (_ _ _))
     #"This is a function with pattern clauses.")
   #(doc function true LFE-EXPAND-EXPORTED-MACRO 3
     ((|\|- MACRO NAME -\|| |\|- CALL ARGS -\|| $ENV))
     #"")))
```

Note the `patterns` and `exported` booleans. For convenience, here's the `#doc{}` definition, which now lives in [src/lfe_doc.hrl](https://github.com/yurrriq/lfe/blob/feature/lfe_comp-doc/src/lfe_doc.hrl):

``` erlang
-record(doc, {type     = error(missing_type)  :: function | macro,
              exported = false                :: boolean(),
              name     = error(missing_name)  :: atom(),
              arity    = error(missing_arity) :: non_neg_integer(),
              patterns = [[]]                 :: [pattern()],
              doc      = <<"">>               :: binary()
             }).
```

**Comment by yurrriq** [comment]
I'm pretty satisfied at this point, but the question is: do we want to do anything analogous to Elixir's `moduledoc`, `callback_docs` and `type_docs`?

_My thoughts_: `type_docs` probably doesn't make much sense for us ([for now](https://github.com/mankyKitty/typed-lfe)), nor does `callback_docs`. It could be quite nice, however, to put a module's docstring in `moduledoc`. I'm not sure what Elixir stores there, but it's probably worth looking into that too.

OTOH...

``` erlang
> (iolist_to_binary (proplists:get_value 'doc (example:module_info 'attributes) []))
#"This is an example module."
```

**Comment by yurrriq** [comment]
One more thing, do we want to prune `LFE-EXPAND-EXPORTED-MACRO/3` and `MODULE/0`, or leave them there for accuracy?

**Comment by rvirding** [comment]
Nice. Some answers to your questions:
- Yes I would have a `module-doc` similar to elixir's and I would (will) remove that attribute from the module attributes when generating the .beam file. The reason being that I want **all** the documentation in the separate LDoc chunk as it can become very large and you can easily remove it when you want to. For example with `beam_lib:strip_release/1`.
- I would prune `LFE-EXPAND-EXPORTED-MACRO/3` and `MODULE/0` and some other predefined stuff as well. In one sense they don't really exist.

**Comment by yurrriq** [comment]
I've pushed some hacks to those ends.

Current output of `lfe test/docs.lfe`:

``` erlang
#(lfe_docs_v1
  (#(doc macro true add 2 ((x y)) #"Add `x` and `y`.")
   #(doc macro true varargs 255 (args) #"This is a varags macro.")
   #(doc macro false forty-two? 1
     ((x (when (=:= x 42))) (x (when (< x 42))) (x (when (> x 42))))
     #"Return `'true` iff `x` is 42.")
   #(doc macro false tricky 255
     ((x) (x y) (x y . z))
     #"This is a tricky varargs macro.")
   #(doc function true subtract 2 ((x y)) #"Subtract `y` from `x`.")
   #(doc function true matchfun 3
     ((x y z (when (< x y) (< y z)))
      (x y z (when (> x y) (> y z)))
      (x y z (when (=:= x y) (=:= y z)))
      (_ _ _))
     #"This is a function with pattern clauses."))
  #"This is an example module.")
```

**Comment by yurrriq** [comment]
Note that `doc` is removed from `attributes` now:

``` lfe
> (set `#(ok [#(ok example ,beam)]) (lfe_comp:file "test/example.lfe" '[binary]))
#(ok
  (#(ok example
     #B(70 79 82 49 0 0 8 116 66 69 65 77 76 68 111 99 0 0 3 149 131 104 3 100 0 11 ...))))
> (beam_lib:chunks beam '[attributes])
#(ok
  #(example
    (#(attributes
       (#(export-macro (add varargs))
        #(vsn (317309562976526214531974017463898375168)))))))
```

**Comment by yurrriq** [comment]
@rvirding, shall I remove `export-macro` too?

**Comment by rvirding** [comment]
No, I think we should leave export-macro, as it is not being saved anywhere
else.

What happens if use the no-docs option? Is your compiler pass not called at
all then inwhcih case the docs is left in the attributes? It might be
better to leave them there and remove them when we call the codegen pass.
And that is when the function docs could be removed as well.

Robert

**Comment by yurrriq** [comment]
Right now:
```
exception error: badarg
  in (: erlang binary_to_term undefined)
  in lists:map/2 (lists.erl, line 1238)
  in lists:map/2 (lists.erl, line 1238)
  in lfe_eval:eval_call/2 (src/lfe_eval.erl, line 676)
  in lfe_shell:eval_form_1/2 (src/lfe_shell.erl, line 390)
  in lfe_shell:foldl/3 (src/lfe_shell.erl, line 60)
  in lfe_shell:run_loop/3 (src/lfe_shell.erl, line 629)
  in lfe_init:run_script/1 (src/lfe_init.erl, line 67)
```

**Comment by yurrriq** [comment]
``` lfe
> (set `#(ok [#(ok example ,beam)]) (lfe_comp:file "test/example.lfe" '[binary no-docs]))
#(ok
  (#(ok example
     #B(70 79 82 49 0 0 5 12 66 69 65 77 65 116 111 109 0 0 0 233 0 0 0 29 7 101 ...))))
> (beam_lib:chunks beam '[attributes])
#(ok
  #(example
    (#(attributes
       (#(doc ("This is an example module."))
        #(export-macro (add varargs))
        #(vsn (317309562976526214531974017463898375168)))))))
```

**Comment by yurrriq** [comment]
FWIW `export-macro` is reflected in `lfe_docs_v1`, e.g.

``` erlang
#(doc macro true add 2 ((x y)) #"Add `x` and `y`.")
```

**Comment by yurrriq** [comment]
I've pushed an update that leaves `attributes` alone. I'll leave it to you to clean up in the `codegen` pass. :smile:

**Comment by rvirding** [comment]
Where was the startup error coming from? The one with

exception error: badarg
  in (: erlang binary_to_term undefined)
  in lists:map/2 (lists.erl, line 1238)
  in lists:map/2 (lists.erl, line 1238)
  ...

**Comment by yurrriq** [comment]
That was in `test/docs.lfe`. I've since updated it to be a more general shell script and to account for a missing `"LDoc"` chunk.

**Comment by yurrriq** [comment]
Should we handle other fields, like `author`, `date` and `version`? I really ought to look at what Elixir does..

**Comment by rvirding** [comment]
In this case I think we can ignore what elixir does. :-) I would leave all
other attributes as they are now and get them from the attributes chunk. I
see them as part of the code more than the docs are.

Robert

**Comment by yurrriq** [comment]
Sounds good. I might like to pull in (and modify) my property tests from Lodox, but other than that I think we're good to merge. I'll give the changes another read and see if there are any other spots to do some error handling. Along the way I made some questionable matches that rely perhaps too heavily on the correct behaviour of the prior steps. While that's probably ok, it seems like the best practice would be for the docs passes to gracefully handle problems.

**Comment by yurrriq** [comment]
What about adding `line` to `#doc{}`?

**Comment by rvirding** [comment]
Yes, if you want.to.

**Comment by yurrriq** [comment]
Done. I'm adding and modifying the property tests now.

**Comment by yurrriq** [comment]
:tada:

``` fish
$ rebar3 eunit --module lfe_doc
```

``` erlang
===> Verifying dependencies...
===> Compiling lfe
===> Performing EUnit tests...
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
OK: Passed 1000 test(s).
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
OK: Passed 1000 test(s).
.

Top 2 slowest tests (3.188 seconds, 99.7% of total time):
  lfe_doc:parse_test_/0:235: A match-lambda definition is parsed correctly.
    2.958 seconds
  lfe_doc:parse_test_/0:233: A lambda definition is parsed correctly.
    0.230 seconds

Finished in 3.198 seconds
2 tests, 0 failures
```

**Comment by yurrriq** [comment]
I should be able to give it a final once over and make a PR before I go to sleep tonight.

**Comment by rvirding** [comment]
No rush, I won't to try and fix docs first and make a 1.0.2 of them first.

Unfortunately I got the docs mixed up with the bug fixes so I can't merge
them in separately into master, at least not without rebasing which will
ruin things for your commits. At least I don't think I can, at least not
easily.

I suppose I could merge into master, then remove commits there with rebase
-i but I hate to think of the mess that will create. Ah well, nothing to do
about it.

I can't rebase your PR can I? I know that if I pull then do a rebase your
commits will no longer be pulled and they will pop up in your repo again.
That happened once before. :-(

Or I just pull your stuff into a separate branch which I keep parallel and
then merge into develop after I fixed the docs.

Problems, problems,

Robert

**Comment by yurrriq** [comment]
I've been periodically rebasing on `develop` and can do it again whenever you're ready to merge.

**Comment by yurrriq** [comment]
I can try to take a look at the PDF issues tonight too.

**Comment by rvirding** [comment]
No, I will fix the PDF stuff, almost got it working. Then I will clean up
develop and merge it into master as 1.0.2, then you can rebase your stuff
and I will pull it.

Robert

**Comment by rvirding** [comment]
Do you know if you can comment a line in MD?

**Comment by yurrriq** [comment]
You do it HTML style: `<!-- this is a comment -->`

**Comment by rvirding** [comment]
Yes, that works, thank you.

The problem is the latin1 characters and two unicode codepoints in the
source. And you get different problems depending on what you are generating:
- The pdf can't handle 2 latin1 chars and no unicode codepoints at all, but
  everything goes fine. Maybe there is a switch which can fix this.
- The man page doesn't seem to be able to handle anything above 128. Well
  it can handle it but the output is unintelligible.
- The textfile works ok except for a few latin1 chars.

Do you know of any options which may help me then let me know. My plan is
to rewrite those sections and just mention the char ranges, not explicitly
show them.

Robert

**Comment by yurrriq** [comment]
I'm not sure about those issues, but I've pushed a crucial fix for the `to_*` steps, as well as some general cleanup and tooling improvements. I won't link to commits, since they'll likely get rebased soon, but you can look at the log of my branch.

**Comment by yurrriq** [comment]
XeLaTeX might be of use here. /cc @jgm

**Comment by rvirding** [comment]
What I have done now is to quite simply remove all the unicode and upper
latin-1 characters. I just have to shift some bits to the left and I am
done.

Robert

**Comment by yurrriq** [comment]
Based on #216, I've started writing `doc/1` and similar. You can find a snapshot [here](https://gist.github.com/yurrriq/ba4d5f40f268513e7834a84f2e0a41f3) or [here](https://github.com/yurrriq/ldoc).

**Comment by yurrriq** [comment]
The process has exposed a bug/feature of `lfe_doc` that may need correcting:

``` lfe
(defmodule example
  (export (drop-prefix 2)))

(defun drop-prefix
  "Drop a matching prefix of `xs` from `ys`."
  ([`(,x . ,xs) `(,y . ,ys)] (when (=:= x y))
   (drop-prefix xs ys))
  ([_xs ys]
   ys))
```

``` lfe
> (let ((`#(ok ,docs) (exports 'example))) (lists:keyfind 'drop-prefix 4 docs))
#(doc function true drop-prefix 2
  ((`(,x comma xs) `(,y comma ys) (when (=:= x y))) (xs ys))
  #"Drop a matching prefix of `xs` from `ys`."
  4)
```

**Edit**: Check out the workaround I adopted from Lodox, [`format-patterns/1`](https://github.com/yurrriq/ldoc/blob/7c3ab70e2041f1c90b294c4720cccdf446717901/ldoc.lfe#L111-L116).

The question remains: Do we want to handle this in `lfe_doc` or let/force consumers to handle it?

**Comment by rvirding** [comment]
Do you mean not expanding the backspace macro?

We could solve that by moving the comment pass until after the macro
expansion. Currently that would mean the macros are gone but that would be
easily fixed by leaving them and ignoring them later.

Robert

**Comment by yurrriq** [comment]
I mean when you use quasiquoting in function clauses, the show up as `(,x comma xs)` in `patterns`.

**Comment by yurrriq** [comment]
I think we should leave the `do_docs` pass where it is and add a function that sanitizes patterns.

**Comment by yurrriq** [comment]
The question is: is the LDoc chunk going to be used for more than just display purposes, i.e. do we need to ensure `(length pattern)` remains accurate? Or can we use a hack to make sure it "looks right" and tell users to use the `arity` field if they need to, rather than `(length pattern)`?
