### ISSUE TITLE
Evaluating user input from Erlang

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [lfe/lfe#217]
I have an Erlang application in which I want to evaluate LFE code (user is itself responsible for not breaking the system, so security isn't an issue). However I have a hard time finding documentation on parsing and compiling/evaluating a sequence of forms. Does this documentation exist somewhere?

**Comment by yurrriq** [comment]
Check out the new [`lfe_comp` docs](https://github.com/rvirding/lfe/blob/develop/doc/source/lfe_comp.3.md).

**Comment by no-longer-on-githu-b** [comment]
Ah yes, that seems like a high-level API. Thanks.

**Comment by yurrriq** [comment]
If you looking for something more interactive, there's also `lfe_shell:start/0` or similar. I may have the name wrong.
