### ISSUE TITLE
Consider publishing to Hex

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#218]
While I've not used Hex much, I noticed it caches packages nicely. Since I often rebuild projects from scratch (developing/debugging tooling, etc), I find myself downloading the the same packages over and over again. For that reason, it'd be nice to have an LFE package on Hex.

As far as I can tell, I'm set up locally to publish, but wanted to see if you, @rvirding, want to be the maintainer or if I should. I'm happy to maintain.

**Comment by rvirding** [comment]
How would this work, and what we would need to do?

**Comment by yurrriq** [comment]
I think we already have the metadata in place and all that's left is essentially to call `rebar3 hex publish`, I think. See instructions [here](https://hex.pm/docs/rebar3_publish).

**Comment by yurrriq** [comment]
Done. Maybe we should add a badge to the README. https://hex.pm/packages/lfe
