### ISSUE TITLE
Add Hex badge to README

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#221]
I'll make a PR for this today.

**Comment by rvirding** [comment]
Badges? We don't need no stinking badges.

Sorry couldn't help myself. What is a Hex badge, and a Travis badge for that matter?

**Comment by yurrriq** [comment]
A hex badges is a little SVG that shows the current package version and provides a link to the package page. A Travis badge shows the current test status and links to the results. We definitely don't need them, but they're fun.

**Comment by yurrriq** [comment]
Hold off on this for now, while we sort out tooling issues.

**Comment by yurrriq** [comment]
So, it looks like we're not gonna be using Hex after all. A Travis badge could be good though. It could look good to newcomers if the tests are shown to be passing :smile:

**Comment by rvirding** [comment]
Why not use Hex? I managed to include the Hex LFE package and call it.

**Comment by yurrriq** [comment]
Check out the lengthy discussion in #tooling. You'll have to scroll back quite a bit. I think it's cool to provide LFE as a package if people want to use it, but we won't be publishing packages for lfex libs or the plugins any time soon.

**Comment by rvirding** [comment]
I saw that there was a long discussion but I signed off after the hyphens, which as you may have guessed doesn't really worry me. Are there other significant issues? One reason I am asking is that Hex is becoming a much used package manager and it wouldn't surprise me if it ends up being the default erlang one as well. If so it would be a good place for the LFE packages.

**Comment by yurrriq** [comment]
[![Hex.pm](https://img.shields.io/hexpm/v/lfe.svg)]() [![Hex.pm](https://img.shields.io/hexpm/dt/lfe.svg)]() [![Hex.pm](https://img.shields.io/hexpm/dw/lfe.svg)]() [![Hex.pm](https://img.shields.io/hexpm/dd/lfe.svg)]()

``` markdown
[![Hex.pm](https://img.shields.io/hexpm/v/lfe.svg)]()
[![Hex.pm](https://img.shields.io/hexpm/dt/lfe.svg)]()
[![Hex.pm](https://img.shields.io/hexpm/dw/lfe.svg)]()
[![Hex.pm](https://img.shields.io/hexpm/dd/lfe.svg)]()
```

**Comment by yurrriq** [comment]
I'll let @oubiwann chime in. I'm into it, but he has some reservations.
