### ISSUE TITLE
Tuple literals

### ISSUE THREAD

**Issue by AeroNotix** [lfe/lfe#225]
Using `(tuple ...)` seems a bit much, what about literal `{}`?

**Comment by skovsgaard** [comment]
While it's not `{}`, we already have a literal.

`#('ok "I'm a tuple")` will work.

If you need to match on or represent values in a tuple literal, you backquote it and unquote the individual values, e.g.:

```
(let ((value "I'm a tuple"))
  `#(ok ,value))
```

However, `(tuple ...)` is required for some matching situations, if I recall correctly.

**Comment by rvirding** [comment]
Yes, literal tuples are written with `#(ok 1 2 3)`. It  is a literal tuple so nothing in it is evaluated, it is just itself. If I use it in the "right-hand-side" in an expression it will just return itself exactly as it is, no need to quote anything. If I use it in the "left-hand-side" in a pattern then it will match exactly that tuple.

To build a tuple you use the `(tuple 'ok (+ 100 23))` form which dynamically evaluates its arguments and builds the tuple. This form _evaluates_ to the tuple `#(ok 123)`. If I want to match against a tuple and extract values the I need this form. So the pattern `(tuple 'ok value)` will match a tuple of 2 elements whose first element is the atom `ok` and bind the variable `value` to the second element.

Using the backquote macro ``` together with `,` allows me to write a literal tuple with `#(...)` which expands into a `tuple` form. So ``#(ok ,value)` expands into `(tuple 'ok value)`. This is very practical and can make things easier to read.

There have been suggestions to use `{ }` as syntax for _literal_ tuples, so `{ok 123}` would be equivalent to `#(ok 123)`. Or perhaps as alternative to `(tuple ...)` form, so then `{'ok value}` would be equivalent to `(tuple 'ok value)`. We would have to pick one or the other as they are not equivalent, or none of the above.

So far it has been non of the above.

**Comment by AeroNotix** [comment]
@rvirding all the forms which evaluate the forms inside the syntax seem a bit verbose. E.g to get a neat form which evaluates its terms you need to syntax-quote and syntax-unquote. Often people do this in Common Lisp with literal assoc lists and it's always a smelly bit of code when you see this. What's the cons for adding a form like `{}` to do the same thing?

**Comment by yurrriq** [comment]
The smell is definitely subjective.

I can think of a couple reasons not to want `{...}`:
1. Comma means `unquote`, which could lead to unnecessary confusion wrt `{a, b, c}` vs ``{,a b ,c}`.
2. We borrow from Clojure a bit (libs more than lfe proper for now) and `{...}` is a map there.
3. We already have `#(...)`.

**Comment by rvirding** [comment]
The quote/unquote you see in CL actually expand to forms which evaluate internal forms. You have the two versions there as well: the literal form and the evaluating form. For example in SBCL:

``` lisp
* (setq a 42 b 84)
84
* (vector 'a a 'b b)

#(A 42 B 84)
* `#(a ,a b ,b)

#(A 42 B 84)
* (macroexpand '`#(a ,a ,b b))

(SB-IMPL::|Vector| 'A A 'B B)
T
```

The `SB-IMPL::|Vector|` is just an implementation level form for constructing a vector. Here `#( ... )` is the literal and `(vector ... )` is the evaluating form. The ``` is a quote which allows unquoting inside using the `,` prefix. They exist for all composite types. This is how lisp works.

The only question is whether to use `{ ... }` for the literal.

**Comment by yurrriq** [comment]
Cool, I didn't know that about SBCL. I vote :-1: for `{ ... }`, I'm pretty sure. I don't feel strongly, though.

**Comment by deadtrickster** [comment]
My 2 cents.
While I fully understand LFE isn't common lisp #() is somewhat confusing because as we all now this is standard syntax for vectors in CL. Probably can source many annoying errors for people coming from CL. 
and {} syntax is for tuples in erlang already.

**Comment by yurrriq** [comment]
> We would have to pick one or the other...

I'd prefer `{'ok value}` => `(tuple 'ok value)` over `{ok value}` => `#(ok value)` => `(tuple 'ok 'value)`

**Comment by rvirding** [comment]
I chose the #( ) syntax for tuples just because it is used for CL vectors
and tuples and vectors are pretty much the same thing. :-)

**Comment by rvirding** [comment]
If we go with using `{ }` it would be as a replacement/alternative to `#( )`. Otherwise it would be inconsistent with the other types for which we have a special literal syntax, binaries and maps, which have a constructor to build them, `binary` and `map`.

**Comment by AeroNotix** [comment]
Even in Lisp, datastructures having literals is always a win. See: clojure.

**Comment by rvirding** [comment]
The problem is not whether they have literals or not, `#(...)` is a literal, but that you also need constructors. So you need `(tuple ...)` (or its equivalent) when you build a tuple which is not just a literal value, for example it contains the values of variables or expressions. Then you cannot write them as literals. Yes, you can use the ``` macro and `,` to make it look more like a literal but it is not a literal. So doing ``#(ok ,a)` actually expands to `(tuple 'ok a)`.

In clojure you have `[1 2 3]` but they are just literal vectors. To create a vector you use `(vector a b c)`. See http://clojuredocs.org/clojure.core/vector.

A suggestion is that we use `{ ... }` for literal vectors in the same way as closure uses `[ ... ]`. We can't use the brackets as they are already in use as alternatives to parentheses in lists.

**Comment by yurrriq** [comment]
Clojure's sugar works a bit differently from the way `#(...)` works now, e.g. `[a b c]` is analogous to ``#(,a ,b ,c)` not `#(a b c)`. I agree introducing a `{ ... }` syntax that works as I described above would be incongruous.

**Comment by rvirding** [comment]
Ah ok, because in the doc page you get the impression that `vector` works like `tuple` and `[ ]` like `#( )`. Have to download and test it properly I see.

**Comment by rvirding** [comment]
Just tested, it correct. But in that case why have two ways of writing the same thing? I do prefer having a literal and a constructor instead of just a constructor. Also a bit inconsistent:

```
user=> (list 1)
(1)
user=> (1)
ClassCastException java.lang.Long cannot be cast to clojure.lang.IFn  user/eval45 (NO_SOURCE_FILE:31)
```

Vectors only have constructors no real literals while lists need an explicit constructor.

**Comment by yurrriq** [comment]
Yeah.. I'm fine with the quasiquoting and mostly indifferent to the addition of `{ ... }`.

FWIW, in practice I rarely use `(vector ...)` in Clojure.

One interesting bit too is that Clojure uses `:keywords` far more often than `'symbols`, which I think alleviates some of the issues we have in LFE wrt `,var` vs `'var`.

**Comment by lpil** [comment]
I like the idea of having the `{}` literal syntax for tuples as it's one less thing to remember when switching between LFE and other popular BEAM languages.

**Comment by oubiwann** [comment]
I'm actually not a fan of special syntax for litteral forms. One of the nice things I like about Lisps in general, is their syntaxlessness. Admittedly without reader macros, LFE is less open to language customization than other Lisps.

Although I do enjoy Clojure a great deal, one of the ways in which it is not classically Lisp-like is all the custom syntax. I wiould vote for staying closer to LFE's Lisp roots and not trying to do many things like Clojure.

What I would propose instead would be to add a mechanism to LFE (whether that be reader macros or something else) which allowss users, devs, library maintainers, etc., to more easily augment LFE with their own syntaxes. At which point we could then bring alternate, Clojure-like syntaxes for literals into the clj library (once it gets merged into LFE-proper).

This would help keep the core language itself lighter and less prone to feature accretion and subsequently, exponential maintenance burdens.

**Comment by rvirding** [comment]
The problem is whether {...} should be equivalent to the existing #(...) or (tuple ...).  We could not agree. LFE follows the CL and scheme conventions here which I feel are more lispy, at least more what I am used to.

If you write a clj library with some special syntax and merge it into LFE proper then you will have extended the core syntax. Or did you mean the ability to extend the syntax? The LFE parsing does not work int the same way as classic lisp parsets do.

**Comment by oubiwann** [comment]
I mean that we'd first have to add to LFE the ability to support special syntaxes generically (e.g. reader macros), and then at that point we could add Clojure-inspired syntax to the clj module in LFE.

We've talked a little about reader macros in the past, and that they might be a bad fit for LFE/BEAM ... but even if we couldn't support them fully in LFE, we might be able to do a little with a workaround.

For instance, assuming that, as part of that work, LFE supported a `#` literal marker (excepting the ones that already exist), the clj library could add macros to support `#{...}` ... not as nice as having complete control over new syntax, but perhaps better than nothing?

**Comment by yurrriq** [comment]
:+1: to reader macros in general. Seems like a good way to please many people too. Maybe we could even do something per file like `#lang clj`.

**Comment by AeroNotix** [comment]
I don't understand this POV. Reader macros and custom syntaxes not included in the base language are always tried to be avoided in Common Lisp. How can you be for this when all it brings is incompatibility between codebases which use reader macros and those which don't?

On one hand you say you aim for making things simple but then advocate using reader macros for people wanting additional simplification? When the common opinion is reader macros make codebases much more complex by adding special rules to individual files rather than having a common language used between them.

**Comment by deadtrickster** [comment]
> When the common opinion

I'm sorry but I don't think there a such thing as "a common opinion" in CL community. 
Particularly on this topic: lots of libs provide their reader macros. Never had any problem with that.

**Comment by AeroNotix** [comment]
@deadtrickster I'm not sure where you interact with the community but definitely the consensus is that reader macros are for very unique situations.

**Comment by AeroNotix** [comment]
this will never be resolved.
