### ISSUE TITLE
Add deftest{skip,gen} et al. to keywords in lfe-mode

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#226]
I can prepare a PR if no one beats me to it.

**Comment by rvirding** [comment]
I have a few similar changes I want to make so maybe we can do them all in one go. Which ones do you want and what do you want the first symbol to be coloured as?

**Comment by yurrriq** [comment]
[ltest/include/ltest-macros.lfe:41-112](https://github.com/lfex/ltest/blob/master/include/ltest-macros.lfe#L41-L112)
- [x] `deftest`
- [ ] `deftestgen`
- [ ] `deftestskip`
- [ ] `defsetup`
- [ ] `defteardown`
- [ ] `deftestcase`
- [ ] `deftestcases`

Same as `lfe-font-lock-new-function-keywords`, I think. There's a pattern in there for `deftest` right now, but maybe we ought to do something like:

``` elisp
(defconst lfe-font-lock-test-keywords
  ...
  "ltest test defintion macros.")
```

**Comment by rvirding** [comment]
Should that also be `deftestsetup` and `deftestteardown` as well? But they are a bit long so perhaps not. :-) I have a fix and will push later tonight.

**Comment by rvirding** [comment]
I will add these now but I think we must decide exactly which keywords we are going to handle in this way.

**Comment by yurrriq** [comment]
I just added all the def macros from ltest-macros. I rally only want the ones that start with deftest., but the others are nice too.

**Comment by rvirding** [comment]
I was unclear. This wasn't about which of the deftest macros to handle, doing them all is fine and logical, it was about which sets of keywords we handle. So now we have the all the basic LFE forms and macros, 2 flavors ( yay) and the test macros. We should just decide which sets do we do, what criteria do we have? Just basics? From standard packages, if so which ones? Etc, etc.

This is mainly so we don't get so many that it becomes pointless.

**Comment by yurrriq** [comment]
Ah, I think we've got all we need now, or rather we should only do the basic forms and macros, flavors and tests. Although I think `clojure-mode` does something like `def*`, which is nice for user-generated macros too.
