### ISSUE TITLE
`defmodule` extension proposition

### ISSUE THREAD

**Issue by rodentrabies** [lfe/lfe#233]
As far as I understand, there is no way to include docstrings in the module definition, similar to how it can be done in Clojure for example:

``` Clojure
(defmodule mod
  "Module docstring."  ; proposal syntax
  (export ...)
  ...)
```

 Is such a design intentional, or it could be extended in future? Sorry if I am missing something, just started exploring LFE.

**Comment by yurrriq** [comment]
The way to add a doc string in the module definition in LFE is like this:

``` clojure
(defmodule mod
  (doc "Module docstring.")
  (export ...)
  ...)
```

**Comment by rodentrabies** [comment]
Oh, thanks. Probably missed it in reference. Will pay more attention next time. So this is closed in less than 2 minutes :)

**Comment by yurrriq** [comment]
In 1.0.2, it's simply handled as a module attribute:

``` lfe
> (proplists:get_value 'doc (mod:module_info 'attributes))
("Module docstring.")
```

but in the develop branch, it's baked into the LDoc chunk (and removed from module attributes iirc).

**Comment by rodentrabies** [comment]
Great. I appreciate such details, as they are sometimes very important, but rarely included in documentation.

**Comment by yurrriq** [comment]
In general, anything other than `export`, `import`, etc, you add to the `defmodule` form will end up as an attribute:

``` clojure
(defmodule mod
  (silly yes)
  (arbitrary but of course))
```

``` lfe
> (proplists:get_value 'silly (mod:module_info 'attributes))
(yes)
> (proplists:get_value 'arbitrary (mod:module_info 'attributes))
(but of course)
```

**Comment by rodentrabies** [comment]
And are those attributes planned to be used anywhere besides documentation?

**Comment by yurrriq** [comment]
Only a `doc` attribute is treated as documentation, the rest are simply added the to the `"Attr"` chunk. As a user, you can assign your own meaning to other values. Note that in `develop`, the `doc` attribute is removed and put instead in the `"LDoc"` chunk.

**Comment by rvirding** [comment]
Some other attributes like `export`, `import` and `export-macro` have special meaning for the compiler. Any others the compiler will just save and they can be accessed through the `module_info` function (which is automatically generated by the compiler).

**Comment by rodentrabies** [comment]
So, as far as I understand, `defmodule` declarations serve as depositories for module metadata. Any implications of that, or is it just a liberal design? And also, are function docstrings handled similarly? I have never worked with Erlang before, as I come from Common Lisp background, so it is hard for me to read Erlang code (for now, I hope), thus so many questions:)

**Comment by yurrriq** [comment]
I'll let Robert speak to design choices. Reading Erlang definitely gets easier. Docstrings are currently ignored in 1.0.2 but will be added to the `"LDoc"` chunk in 1.1. We're still working out some details, but if you're feeling adventurous, you can check out the develop branch now. There's some minimal documentation under [`lfe_doc`](https://github.com/rvirding/lfe/blob/develop/doc/src/lfe_doc.3.md) and a tool to pretty print the chunk at [`bin/lfedoc`](https://github.com/rvirding/lfe/blob/develop/bin/lfedoc/). There's some more discussion in #220.

**Comment by yurrriq** [comment]
For general questions (of which we're very supportive) you can use the mailing list or IRC. More info [here](http://docs.lfe.io/community.html).

**Comment by rvirding** [comment]
The declarations in the `defmodule` are module metadata, some of which is directly relevant for LFE. Some of the relevant metadata is: `export` which declare which functions are exported and visible outside the module; `export-macro` declares which macros are exported; `import` for importing functions names from other modules (seldom used). The other metadata is not interesting to the system but it saves it and it is accessible through the predefined `module_info` function.

The doc strings, both module and function, are specially handled and accessible in the compiled module but are not reached through the `module_info` function. They are, as @yurrriq described, in a special chunk in the compiled file and are reached differently.

The handling of the module metadata is LFE is directly taken from Erlang, which is not surprising as LFE runs "on top of" Erlang and can use all of its features and libraries. Erlang, however, does not have doc strings, these are part of LFE.

LFE has a CL feel in many ways but it definitely is not CL. This is impossible to do efficiently on top of Erlang. LFE does, however, have full access to all the system building properties of Erlang and its libraries.

**Comment by rvirding** [comment]
I gave a talk about LFE at the LambdaDays conference which you find here http://www.lambdadays.org/lambdadays2016/robert-virding . It explains some of the features of LFE and its relationship with Erlang.
