### ISSUE TITLE
An LFE prompt

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#236]
This may seem a bit odd, but one of the things that I've found confusing when having REPLs from multiple languages open in different terminals and trying to remember which one is LFE is the absence of an LFE-specific prompt. Erlang has `n>`, Clojure has `user=>`, SBCL has `*`, Python has `>>>`, etc.

The first confusion that could occur is that the continuation prompt (second-level prompt for Bash is `>`, the same as LFE's.

What I'd like to do is propose `lfe>` for the LFE prompt when no node is defined (keeping the current behaviour for when a node name is defined).  If some found this objectionable, we could make it optional.

**Comment by oubiwann** [comment]
Branch is here:
- https://github.com/oubiwann/lfe/tree/new-prompt

**Comment by oubiwann** [comment]
Example usage:

```
$ lfe
```

Gives 

```
lfe>
```

```
$ lfe -prompt LFE!
```

Gives

```
LFE!>
```

```
$ lfe -prompt lfe.user=
```

Gives

```
lfe.user=>
```

And 

```
$ lfe -prompt classic
```

Gives the original 

```
>
```

**Comment by yurrriq** [comment]
It'd be cool to be able to change the prompt from within the REPL too, as in GHCi.

**Comment by oubiwann** [comment]
@yurrriq Huh. That's a really good idea.

**Comment by rvirding** [comment]
Of course if you are setting the prompt should the `>` always be included? It would be more logical to just use exactly what was given. But then you do run into a problem if LFE is alive and you wish to include node-name in the prompt. Maybe something like

```
$ lfe -prompt bert
bert 'a
a
```

and 

```
lfe -sname sune -prompt bert
(sune@my-node)bert 'a
a
```

The default would be `lfe>`. We do include the space after the prompt, bash doesn't.

**Comment by oubiwann** [comment]
Ah, yes -- you're right of course. Had just assumed the primacy of the bracket :-)

I'll update the PR with your suggestions/use cases.

**Comment by yurrriq** [comment]
GHCI doesn't append a space automatically either, which I think is cool wrt two line prompts, for example.

**Comment by oubiwann** [comment]
Okay, I've updated so that if a user provides a prompt, it is understood to be the entire prompt. Adding a bracket is therefore up to the user.

No prompt:

```
$ ./bin/lfe -prompt ''
```

and

```
$ ./bin/lfe -prompt
```

Prompt with special characters:

```
$ ./bin/lfe -prompt 'LFE!> '
```

```
LFE!>
```

This also works when in distribution mode:

```
$ ./bin/lfe -sname lfenode -prompt 'LFE!> '
```

```
(lfenode@mndltl01)LFE!>
```

Furthermore, there is now also support for formatting the node name in the prompt: if `~node` is found in the user-supplied prompt, it will be substituted with the actual node name of the server:

```
$ ./bin/lfe -sname lfenode -prompt '#~node::LFE!> '
```

```
#lfenode@mndltl01::LFE!>
```

With long names as well:

```
$  ./bin/lfe -name lfenode@robot.party -prompt '[~node] [-,-] [`;`] [-.-]> '
```

```
[lfenode@robot.party] [-,-] [`;`] [-.-]> 
```

**Comment by oubiwann** [comment]
Per @rvirding's suggestion on Slack, if a user supplies a node-formatting string, but the node isn't alive, remove it:

```
$ ./bin/lfe -prompt '[~node] [-,-] [`;`] [-.-]> '
```

```
[] [-,-] [`;`] [-.-]>
```

**Comment by oubiwann** [comment]
Thanks for the merge!

**Comment by yurrriq** [comment]
Awesome!
