### ISSUE TITLE
Literal syntax for maps

### ISSUE THREAD

**Issue by lpil** [lfe/lfe#240]
Most my Lisp experience has been with Clojure, so coming to LFE I find myself wanting a literal syntax for maps.

Clojure uses `{:name "Clojure"}` for maps, though I feel that would be confusing in LFE as we're used to `{}` being the tuple syntax for other languages on the BEAM.

**Comment by oubiwann** [comment]
There is a literal syntax for maps in LFE (which you can also use in pattern matching): `#m(k1 v1 ...)`.
