### ISSUE TITLE
Compile-time metadata

### ISSUE THREAD

**Issue by jjl** [lfe/lfe#241]
I would like to be able to insert metadata into my code that will be discarded at runtime but returned as extra information when calling the compiler programmatically with some code.

Elixir uses metadata in order to provide certain language features at build time. I would like to experiment with providing some of these, preferably in an elixir-integrated way. Metadata enables these experiments to take place without modifying the core compiler too much.

**Comment by oubiwann** [comment]
Yeah, we've been talking about this for a couple weeks now, inspired by both Clojure metadata as well as the recent docs data addition to LFE. The path that we're exploring (@yurrriq is prototyping this work) is to essentially update the latest docs efforts with a generalized data structure that will incorporate docs (thus not break this new feature) while allowing developers to add support for all sorts of additional features, as you indicate above.

I'm pretty excited about this approach -- in particular, I'm looking forward to using it to enable type annotations. But there's soooo much more that can be done, as you know.

**Comment by jjl** [comment]
Yeah, I'd like to have at least the capability to have some of the shiny feature elixir added. Or to experiment with them at least :)

**Comment by rvirding** [comment]
What we have currently is that basic forms for defining things `define-module`, `extend-module`, `define-function` and `define-macro` all have an extra field for meta data. The format of the meta data is defined to be a list of key-value lists, a classic CL association list. The idea is that you can add any meta data you wish here and compiler passes will only look at what is relevant for them. So far all we have is the documentation data which has the form `(doc doc-string-1 doc-string-2 ...)`. There can be multiple docs. These are now used by the doc building pass of the compiler which extracts them and saves them in a separate chunk in the beam file. Any pass is free to add anything there as long as it obeys the general format.

The code generating parts of the compiler now happily completely ignore the meta data.

The current macros `defmodule`, `defun` and `defmacro` don't as yet support a general mechanism for including meta data and can only handle documentation strings which become the `doc` meta-data. You are of course free to use the basic forms directly in the file.

The basic forms are described in lfe_guide. To see an example of this look at the files `dev/example.lfe` and `dev/meta_atts.lfe`. To see how these expand try compiling them in the repl with `(c "dev/example.lfe" '(binary to-lint))` which will return the expanded code forms. You will see what I mean.

**Comment by rvirding** [comment]
I am not a fan of super specific syntax for stuff, and don't really see the need here. :-)

**Comment by rvirding** [comment]
One thing we probably need to which would help using meta-data is to introduce a way to "add" extra passes to the compiler. You have macros today of course but there is no way to work on the whole file/module in one go.

To cover all options we would actually need it in 2 places: at the very beginning before we have done any macro expansion or splitting of the file, and separate.y for each module after all macros have been expanded. This might be overkill. Adding one of them first will not stop us adding the other later.

**Comment by oubiwann** [comment]
> I am not a fan of super specific syntax for stuff, and don't really see the need here. :-)

But! Adding support for metadata would mean that you wouldn't have to field many of the requests that LFE now gets -- instead, you could just point people to the docs that show how to use it to get what they want via metadata in their own projects/libraries :-)

**Comment by yurrriq** [comment]
I think `lfe_meta` will be my next major effort in LFE.

**Comment by oubiwann** [comment]
I think Robert's answer above (https://github.com/rvirding/lfe/issues/241#issuecomment-220376184) takes care of this :-)

Closing ...
