### ISSUE TITLE
Pandoc dependency when installing.

### ISSUE THREAD

**Issue by mqsoh** [lfe/lfe#244]
The Makefile depends on Pandoc now.

```
$ docker run -it --rm erlang:18 bash -c 'cd /usr/local/lib/erlang/lib && git clone https://github.com/rvirding/lfe.git && cd lfe && git checkout v1.0.2 && make compile install'
...
bin/lfe bin/lfec -I include -o ebin -pa ../lfe src/cl.lfe
ecp: #(cl ())
cp src/lfe.app.src ebin/lfe.app
rm src/lfe_scan.erl
make[1]: Leaving directory '/usr/local/lib/erlang/lib/lfe'
pandoc -f markdown -s -t man -o doc/man/lfe.1 doc/src/lfe.1.md
make: pandoc: Command not found
Makefile:159: recipe for target 'doc/man/lfe.1' failed
make: *** [doc/man/lfe.1] Error 127
```

**Comment by yurrriq** [comment]
Pandoc is only necessary for generating the docs, so we should separate that from `compile` and `install`.

**Comment by yurrriq** [comment]
The `install` target depends on `install-man`, which adds the dependency on pandoc.

**Comment by rvirding** [comment]
I have checked and in the distribution all the man docs and .txt docs have been generated and should be newer than the source files so there should be no need to generate them.

But we can easily separate compiling and installing the files from generating and installing the docs.

**Comment by yurrriq** [comment]
I have some other `Makefile` improvements to make and can fold this separation into that effort.

**Comment by yurrriq** [comment]
Basically I plan to decouple `install-man` from `install`, thus obviating the need for `pandoc` to compile LFE, and to fold in some of the Elixir Makefile-inspired changes from the LFE Nix package too make installing a little cleaner and more portable.

**Comment by oubiwann** [comment]
I've submitted a PR that addresses this particular issue.

@yurrriq the other fixes you have in mind might warrant their own ticket ...

**Comment by yurrriq** [comment]
:+1: I'll gather my thoughts and write out a plan in a separate ticket.
