### ISSUE TITLE
lfescript execution error

### ISSUE THREAD

**Issue by fooflare** [lfe/lfe#246]
Each time I execute a lfescript, I get:
`bad module definition: attribute`
I tried with the factorial example from the repo (for being sure I had not any mistake I was not seeing) and I got the same error.

**Comment by rvirding** [comment]
Which version are you running?

**Comment by rvirding** [comment]
And could you show your file as well, if it is not too big?

**Comment by fooflare** [comment]
I am running the master branch version.
Of course, it is just a hello world script. I was just making some tests but I didn't get too far :)

```
#!/usr/bin/env lfescript
;;! -smp enable -sname hello_world -mnesia debug verbose

(defun main (_args)
  (lfe_io:format "Hello world!" ()))
```

**Comment by yurrriq** [comment]
FWIW I `s/lfe/lfescript/` in the shebang.

**Comment by rvirding** [comment]
You have exposed an error! I made some changes to internal forms, the `define-module` form, and got it wrong in `lfescript`. I will push a fix tomorrow, it will be version 1.1.1.

Thank you for finding it.

**Comment by fooflare** [comment]
Thanks to you for a so great work.

**Comment by yurrriq** [comment]
We should write a test for this case.
