### ISSUE TITLE
No defmodule keyword found

### ISSUE THREAD

**Issue by fooflare** [lfe/lfe#247]
Hi,
today I realized that if at the beginning of a module, `defmodule` is not defined, for example:

```
(foo
  (export (fun-name 1)))
```

the compiler just ends, the file is not compiled (of course, because no module is defined) and no message is shown, just like if the compilation process was fine. I don't know if this is done on purpose but I think it should show a message, what do you think?

**Comment by yurrriq** [comment]
Perhaps the trouble is that not all LFE source is destined to be a module, e.g. include files. Not sure how best to address this.

**Comment by rvirding** [comment]
it just returns `()` or `#(ok ())` indicating that no modules were generated. Seeing there were no modules then nothing was really compiled, hence no errors.

Compiling has 2 phases: first the file is split into separate modules; and then each module is compiled separately. Macros before the fir st module are global to the whole file, while macros defined "inside" each module is local to it.

Anything else defined before the first module is copied into each module, so any function defs and other forms go into the modules are processed there. 

In this case as there are no modules then nothing happens and everything is just discarded. It is not an error to have an "empty" file.

I wrote a bit about it in a blog on lfe.io http://blog.lfe.io/tutorials/2016/03/03/0104-lfe-v10-multi-module-files/

**Comment by fooflare** [comment]
Interesting thing, thanks for this detailed explanation.
