### ISSUE TITLE
lfe does not build with Erlang 19

### ISSUE THREAD

**Issue by erlanger** [lfe/lfe#248]
The latest commit on the develop branch has problems building with Erlang 19:
[...]
erlc -I include -o ebin -DHAS_MAPS=true -DHAS_FULL_KEYS=true -W1 src/lfe_scan.erl
src/lfe_eval.erl:128: Warning: variable 'M' shadowed in 'fun'
src/lfe_eval.erl:132: Warning: variable 'M' shadowed in 'fun'
src/lfe_eval.erl:462: Warning: function init_letrec_env/1 is unused
src/lfe_eval.erl:468: Warning: function extend_letrec_env/3 is unused
src/lfe_eval.erl:468: Warning: variable 'Fbs0' is unused
src/lfe_eval.erl:737: Warning: variable 'M' shadowed in 'fun'
src/lfe_eval.erl:741: Warning: variable 'M' shadowed in 'fun'

=ERROR REPORT==== 27-Jun-2016::23:12:36 ===
Error in process <0.50.0> with exit value:
{undef,[{lfe_scan,start_symbol_char,"c",[]},
        {lfe_io_write,quote_symbol,2,
                      [{file,"src/lfe_io_write.erl"},{line,127}]},
        {lfe_io_write,symbol,1,[{file,"src/lfe_io_write.erl"},{line,59}]},
        {lfe_io_pretty,list_max,4,[{file,"src/lfe_io_pretty.erl"},{line,161}]},
        {lfe_io_pretty,term,4,[{file,"src/lfe_io_pretty.erl"},{line,81}]},
        {lfe_lib,format_exception,6,[{file,"src/lfe_lib.erl"},{line,383}]},
        {lfe_init,run_script,1,[{file,"src/lfe_init.erl"},{line,74}]}]}

---

If we run 'make' again, it seems to build.

**Comment by erlanger** [comment]
I had MAKEFLAGS="-j3", it builds without problems without the parallel makes running.

**Comment by yurrriq** [comment]
There are some known issues with records in LFE on 19.0 too. @rvirding is working on it.

**Comment by rvirding** [comment]
In this case I think the problem is the parallel compilation. There is one LFE file in the sources, `src/cl.lfe`, which needs the LFE core system and compiler to be already compiled before it can be compiled. Sequentially this is no problem but if everything is compiled in parallel then it would be.

There will probably be more core source files in LFE in the future so the problem won't go away. Is there a simple option/flag we could put in `Makefile` so it won't attempt parallel compilation?

**Comment by oubiwann** [comment]
"You can inhibit parallelism in a particular makefile with the .NOTPARALLEL pseudo-target (see Special Built-in Target Names).

On MS-DOS, the ‘-j’ option has no effect, since that system doesn’t support multi-processing."

https://www.gnu.org/software/make/manual/html_node/Parallel.html

**Comment by yurrriq** [comment]
I believe [lfe-1.2.0](https://hex.pm/packages/lfe/1.2.0) resolves this issue.

**Comment by erlanger** [comment]
I am closing this since this is solved by #260 and also by setting MAKEFLAGS="-j1"
