### ISSUE TITLE
Binary standalone lfescripts

### ISSUE THREAD

**Issue by fooflare** [lfe/lfe#249]
Hi,

I have pushed a branch (https://github.com/fooflare/lfe/tree/binary) to my fork with the changes needed to have an API to generate binary scripts from beam files of a project and run them with lfescript. It is a simplified code based on the escript.erl file. I pushed also a very simple test repo (https://github.com/fooflare/test_lfebin.git). What I would like to know if this would be interesting to be included in the lfescript features.

**Comment by rvirding** [comment]
Thanks I will take a look at it. I am holidays now so don't expect it to go too quickly :-) , but I will look.

**Comment by fooflare** [comment]
Don't worry, this is no hurry :-) . Happy holidays!

**Comment by yurrriq** [comment]
Fwiw I use `#!/usr/bin/env lfe` and then do `lfe script.lfe`.

**Comment by oubiwann** [comment]
Looks like that branch has been deleted.

Closing ...
