### ISSUE TITLE
`make install` can be problematic

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#250]
I know we've had some issues before, and in preparing a (finally) [working Nix package](https://github.com/yurrriq/nixpkgs/blob/lfe-1.1.1/pkgs/development/interpreters/lfe/default.nix), I ended up [borrowing](https://github.com/yurrriq/nixpkgs/commit/e7ad8375a3295e4444e5a6a4abc8c895775c5bf0) from [Elixir's `Makefile`](https://github.com/elixir-lang/elixir/blob/master/Makefile).

Is there a compelling reason not to use `install` like Elixir does?

**Comment by arpunk** [comment]
Long time ago I was also looking at Elixir's Makefile in order to clean up our own but I got nowhere far. I can't recall if there were issues or not.

IMO having a clean experience for building the codebase and getting it installed is gold.

**Comment by rvirding** [comment]
How does elixir do `install`?

**Comment by yurrriq** [comment]
They use the command `install` in the make target. I realize now how ambiguous that was.

**Comment by rvirding** [comment]
What do we think install should do? Now it just creates some links into the existing structure. This is so we only need to have one structure. We could change that and have install build a separate system with only necessary binaries, like elixir does it.
