### ISSUE TITLE
Regression: fun vs function

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#255]
218fc12dec75af53707913c520a86eeb5c18eabf introduced a regression wrt the `#'f/a` sugar:
#### 0e30930ac40ae407b43c024fe67a44db2a800ffd (before)

``` lfe
> (macroexpand '#'+/3 $ENV)
(lambda (|\|-2-\|| |\|-1-\|| |\|-0-\||) (+ |\|-2-\|| |\|-1-\|| |\|-0-\||))
> (funcall #'+/3 1 2 3)
6
```
#### 218fc12dec75af53707913c520a86eeb5c18eabf (after)

``` lfe
> (macroexpand '#'+/3 $ENV)
(function + 3)
> (funcall #'+/3 1 2 3)
exception error: #(unbound_func #(+ 3))
```

**Comment by rvirding** [comment]
The `#'` is not a macro in itself but a syntactic construct. Originally it expanded to `fun` which is a macro but now it expands to a `function` form which is much closer to the original CL construct. It was the `fun` macro which expanded to the lambda you saw so it would work with a macro while the `function` form can only refer to a function. You can see this if you compile code with `function` which refers to an undefined function or bif. There is also `(function mod fun arity)` which refers to a (exported) function in another module.

The `fun` macro still exists and behaves as before. I hope this makes sense.

**Comment by yurrriq** [comment]
The `fun` vs `function` bit makes sense, and as I understand the commit message and your comment here, I think I prefer `function`, but is it intentional to break e.g. `(funcall #'+/3 1 2 3)`?

IIRC it still works as before for `#'+/2`, which feels even more strange to me.

**Comment by rvirding** [comment]
It wasn't intentional to break it as such. The reason it breaks for `#'+/3` is because `+` is a macro which expands into a set of nested `#'+\2`, which is the BIF. Trouble is we don't really have variable arity functions but use macros for that.

**Comment by yurrriq** [comment]
This is fixed now. Well, `#'+/3` still behaves as above, but I get it now. Feel free to reopen if you want, @rvirding.
