### ISSUE TITLE
Lisp-1?

### ISSUE THREAD

**Issue by trans** [lfe/lfe#256]
Out of curiosity, how hard would it convert LFE into a Lisp-1 instead of a Lisp-2?

I really like the idea of LFE -- a LISP on top of the BEAM VM. But after reading about the deference, I realize that I am of much the same sentiment as Eric Merritt, a Lisp-1 is more my cup of tea.

**Comment by skovsgaard** [comment]
[Here](http://rvirding.blogspot.dk/2014/01/lfe-lisp-and-erlang_14.html) is a really good explanation of why LFE is the kind of LISP it is. If you want to check out an approach to building a LISP-1 on the BEAM, there's [Joxa](https://github.com/joxa/joxa) to look into.

I don't disagree at all that LISP-1 is the more pleasant, simple option, but it doesn't feel in tune with what Erlang does and how BEAM thinks of functions.

**Comment by rvirding** [comment]
The first link took the words right out of my mouth. :-)

I just want to add that I really do value consistency. In the long run it is a Big Win (TM). Also my background is in lisp-2's so I don't see the problem. :-)

If you want to convert there are 3 main modules you must work on, lfe_eval, lfe_lint and lfe_codegen. Shouldn't be too hard.

**Comment by yurrriq** [comment]
I've not looked into it much, but there's also [kapok](https://github.com/kapok-lang/kapok), which might be a Lisp-1.

**Comment by rvirding** [comment]
Dysfun should love it as it is heavily clojure influenced. :-)

**Comment by jjl** [comment]
Actually, I didn't like it, it goes way overboard :)

I like the minimalism of LFE in general, I just think we should be ever so slightly less minimal :)

**Comment by jjl** [comment]
Oh and I have given up on a lisp-1 on the BEAM. I have eventually concluded that there isn't much benefit once you take the limitations of the BEAM into account.

But I'm not giving up on slightly less minimalism yet :)
