### ISSUE TITLE
is_record/2 behaves unexpectedly

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#266]
In writing tests for the `clj:record?` macro, I believe I've discovered a bug in LFE.

See [this gist](https://gist.github.com/yurrriq/747c16da2e15b3cc7e913c5e10404ead) for details.

**tl;dr**

``` lfe
> (defrecord foo a b c d)
set-foo-d
> (is_record #(foo) 'foo)
true
```

... but `#(foo)` is not a `#foo{}`.

**Comment by yurrriq** [comment]
Same behaviour on lfe-1.1.1.

**Comment by rvirding** [comment]
This is not really a bug but a glitch in the interface between erlang and LFE.

When you define a record in LFE all the access forms are macros. There is an `is-XXX` macro for testing if something is a record of a specific type. So for the `foo` record there is an `(is-foo thing)` macro which tests if thing is foo record. There is no generic `(is-record thing foo)`.

Now `is_record/2` is an erlang BIF. If the erlang compiler knows about the named record type it expands to a test of both tag and size. If it does not know about the record it just becomes a test that the tag is correct. This occurs very early in the erlang compiler so the LFE compiler cannot use it. This is what happens in your example.

I have no obvious solution to this.

http://erlang.org/doc/man/erlang.html#is_record-2

**Comment by yurrriq** [comment]
Noted. Perhaps we can/should do the same, i.e. expand to `is-foo` in `clj:record?` and `cl:recordp`.

**Comment by yurrriq** [comment]
Closing as a non-issue, or at least an ignorable one. I've added a note in the clj.lfe docs.
