### ISSUE TITLE
[clj] Implement cycle

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#278]
``` clj
(defn cycle
  "Returns a lazy (infinite!) sequence of repetitions of the items in coll."
  {:added "1.0"
   :static true}
  [coll] (lazy-seq 
          (when-let [s (seq coll)] 
              (concat s (cycle s)))))
```

https://github.com/clojure/clojure/blob/clojure-1.6.0/src/clj/clojure/core.clj#L2683

https://github.com/lfex/clj/issues/1

**Comment by profitware** [comment]
Hi @yurrriq 

I'm newbie in the LFE community. Nevertheless I'd like to implement some features in the LFE for self-education purposes. I figured out that README at https://github.com/lfex/clj is a bit outdated (as it points out to a branch of @oubiwann ) and current development process on implementing Clojure in LFE lives at your branch https://github.com/yurrriq/lfe/tree/feature/add-clojure-lib - I'd like to join it by submitting PRs there and I'm willing to start from features tagged with [clj] like this one (or may be from something a bit simplier).

As for the feature itself I am interested in how should it be implemented - I had not found any mentions of lazy-seqs in LFE except clj:next in the way it returns function yielding sequence. Is there any documentation or thoughts about this issue? Should clj:cycle also return a function yielding an infinite sequence?

Thank you.

**Comment by yurrriq** [comment]
Hi @profitware! Thanks for your interest. That sounds awesome.

My branch you found has actually been merged into [rvirding/lfe@develop](https://github.com/rvirding/lfe/tree/develop) and is included in [lfe-1.2.0](https://hex.pm/packages/lfe/1.2.0). Rather that submit PRs there, I'd suggest you submit them here, to [rvirding/lfe](https://github.com/rvirding/lfe).

There's no lazy sequence in the Erlang [stdlib](https://github.com/erlang/otp/tree/maint/lib/stdlib), though there are a few libs out there in the community, e.g. [zlists](https://github.com/vjache/erlang-zlists).

There is some documentation about `clj`'s "lazy lists" [here](https://github.com/rvirding/lfe/blob/develop/doc/src/lfe_clj.3.md#sequence-functions), but it could definitely use some polishing.

I think the general idea for `cycle/1` is that it should return a "lazy list" (à la `next/{1,2,3}`) that behaves something like this:

``` lfe
> (set xs (clj:cycle '(1 2 3)))
#Fun<clj.3.141592653>
> (clj:take 7 xs)
(1 2 3 1 2 3 1)
```

**Comment by profitware** [comment]
Hi @yurrriq 

Should we close this issue? Or anything else should be done on it?

**Comment by yurrriq** [comment]
I think it's fine for now, but at some point we'll want to rethink the lazy lists in general and update `clj:cycle/1` accordingly. Thanks for your all your work on this.
