### ISSUE TITLE
Support importing macros

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#281]
Now that we can export macros, we ought to be able to import them too.

Rather than create a separate issue, I'd also like to be able to say `(import (from mod all))` or similar, along the lines of Clojure's `(:use namespace)`.

While that's a bit of an anti-pattern imo, it would be quite handy for modules like `cl` and `clj`, to name two. I've got a very hacky `#lang` macro floating around, but what it does shouldn't be spoken of and supporting importing macros and `all` would solve it.

**Comment by yurrriq** [comment]
Desired behaviour:

``` lfe
;;; ===================================================================== [ foo ]

(defmodule foo
  "This module exports the macro [[bar]]."
  (export-macro bar))

(defmacro bar () `'baz)

;;; ===================================================================== [ qux ]

(defmodule qux
  "This module imports the macro [[foo:bar]]
  and exports the function [[quux/0]], which calls it."
  (export (quux 0))
  (import-macro foo bar))

(defun quux ()
  "Call the macro [[foo:bar]], imported from `foo`."
  (bar))

;;; ===================================================================== [ EOF ]
```

``` lfe
> (qux:quux)
baz
```

**Comment by rvirding** [comment]
You can now do

```
(defun quux ()
  "Call the macro [[foo:bar]]."
  (foo:bar))
```

This works wherever you can use a macro even in patterns. So I don't quite see that this would give very much.

**Comment by yurrriq** [comment]
Yeah, really it just saves a few keystrokes and makes operator-like macros (e.g. `->` and `->>`) look a little better imo.

**Comment by yurrriq** [comment]
Closing because "saves a few keystrokes" is not motivating.

**Comment by lin7sh** [comment]
I agree with @rvirding conservative with adding feature. I just made a macro to "support" it.
```lisp
(define-macro import-macro
    ((doc "import marco from module"))
    (match-lambda
        (((cons (cons module-name (list macros)) _) $ENV)
            (cons 'progn (lists:foldr
                (lambda (macro sum)
                    (cons 
                    `(define-macro ,macro
                        () (lambda (args _)
        `(,',(list_to_atom (++
            (atom_to_list module-name)
            ":"
            (atom_to_list macro))) ,@args))) sum))
                '() macros)))))
```

usage:

`(import-macro (utils (eq?)))` will expand to `(define-macro eq? () (lambda (args _) `(,'utils:eq? ,@args)))`

and the consequent `(eq? 'a 'b)` will expand to `(utils:eq? 'a 'b)`

btw through making the macro I've discovered the brain twisted nesting backquote.  😂
