### ISSUE TITLE
Document (doc ...)

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#286]
In recent versions of LFE, and certainly in [1.2.0](https://hex.pm/packages/lfe/1.2.0), we have the built-in shell function, [`doc/1`](https://github.com/rvirding/lfe/blob/1.2.0/src/lfe_shell.erl#L829-L846), but I can't seem to find a description of it in [the documentation](https://github.com/rvirding/lfe/blob/develop/doc/lfe.txt).

**Comment by yurrriq** [comment]
A few examples:

**Module**

```
> (doc clj)
____________________________________________________________
clj

LFE Clojure interface library.
```

**Exported Macro**

```
> (doc clj:zero?)
____________________________________________________________
zero?
Return `'true` if `x` is zero.
```

**Exported Function**

```
> (doc clj:comp/2)
____________________________________________________________
comp/2
Function composition.
If the second argument is a function, compose `f` and `g`.
Otherwise, compose a list of functions `fs` and apply the result to `x`.
```

**Comment by yurrriq** [comment]
I will do this tomorrow, for real. I've been deep down an Idris rabbit hole of late...

**Comment by rvirding** [comment]
No rush, I have to make the new release today. We will just push it to 1.2.2.

There is also one issue I have been thinking about. The doc command is really a shell macro (so it doesn't evaluate its argument) which means it can be redefined away and used in other functions/macros. Which is good but maybe over powerful. I have been thinking of making it a shell command instead which means that it cannot be redefined and only called from the shell.

Wel not quite, the actual work work is done in an exported function`lfe_shell:doc/1` which you can call from anywhere.
