### ISSUE TITLE
Issue on website tutorial

### ISSUE THREAD

**Issue by edescourtis** [lfe/lfe#288]
On page [LFE Quick Start](https://lfe.gitbooks.io/quick-start/content/1.html)
Command "docker run -i -t lfex/openssue lfe" does not work. Did you mean "docker run -i -t lfex/opensuse lfe"?

**Comment by oubiwann** [comment]
Yes, that's definitely a typo.

**Comment by oubiwann** [comment]
Fixed.

**Comment by oubiwann** [comment]
OpenSuSE Docker image has also been updated with latest Erlang + LFE.

Closing ...

**Comment by oubiwann** [comment]
@rvirding Actually, I can't close this -- could you do that for me?

**Comment by olleolleolle** [comment]
@edescourtis Perhaps you, the original poster, can close this issue, which has been fixed now.
