### ISSUE TITLE
[clj] Implement lazy sequences

### ISSUE THREAD

**Issue by profitware** [lfe/lfe#289]
Implement lazy sequences constructor (and may be its own datatype).
Issue is created based on #287 - `cycle/1` requires finite lazy sequence for testing.

Proposal has three features to be implemented:
1. `lazy-seq` constructor that takes `lazy-seq` or `list` data and returns lazy sequence generated from its elements.
2. Infinite lazy sequence datatype may be implemented as it is now: a `function` which returns a `list` with head containing data and tail containing `function` which returns next iteration of sequence is treated as lazy.
3. As for finite lazy sequences there are some ways to implement iterator-like behaviour: sequence is ended when some element is returned from tail `function` - it may be empty `list` or an `atom` with special meaning. The second way is to throw exceptions like Python's `StopIteration` and handle them at the top function which gathers elements from lazy sequence.

All these are opened for discussion.

**Comment by rvirding** [comment]
My only question is that as this is going in the clj module is it "clojure compatible"? Or at least compatible enough?

**Comment by yurrriq** [comment]
I think it's "compatible enough" and follows the same general design philosophy as our `cycle`, `drop` and `take`.

**Comment by rvirding** [comment]
Can we close this one?

**Comment by yurrriq** [comment]
I think so. @profitware?

**Comment by profitware** [comment]
I agree. Thank you.
