### ISSUE TITLE
Come up with a release process for packaging LFE and lfex community libraries

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#300]
Taken from the conversation on ticket #296:

There seems to be a growing consensus that we should start making LFE releases -- start small, using one or two libraries, package them with lfe and offer them as a download, etc. 

We can see how that goes. Iron out process and release issues. As more libraries are deemed ready for inclusion or generally useful by the community, they can be added to the release. We can also document our release process such that anyone can create their own releases, with as much or as little of the community libraries as they prefer.

This would not only provide the same familiar approach as used by the Erlang world, it would also make creating specialized (and general), pre-packaged development environments and VMs wonderfully trivial.

**Comment by rvirding** [comment]
I think this is the issue we need to resolve before the others. We currently don't handle releases in the same way as erlang/otp does. So far we have distributed everything we have. They have everything in one whopping repo, src, data files, docs, test files, everything. Then they extract from that to build a release containing what is necessary for the distribution. This is why for example while the distribution contains both eunit and common test it doesn't contain the system test files so there is never any problems about having to run tests on itself.

We could do that as well. Things added to the system would have to be their own otp applications as this is how things are packaged. So their would be a core LFE application, a test application, maybe a clj application. Everything would be in separate applications. Whether all these applications need to be in the same build tree as with erlang/otp or not I don't know, probably not if we don't want. We could fix it so all the parts are downloaded and compiled when you build LFE or we pre-build a source release which users download and compile.

This would affect documentation as well. We could do it the same way as erlang/otp in that you separately download the documentation.

These are just some thoughts around building releases. We need to think this through and decide what we want to do. Until then I am going to be restrictive in pulling down stuff, only crucial stuff. I will still push 1.2.1 next week.

Interestingly the otp team have decided to split the complete erlang/otp release into a number of releases. How this is going to work I don't know but it is definitely worth keeping an eye on it.

**Comment by oubiwann** [comment]
I think we should definitely keep repos separate ... but here's a thought:
- since an LFE+libs release is a meta-level above LFE itself, we could make a new repo (e.g., lfe/release)
- the new repo could use git submodules to pull in anything we wanted to create in a release
- the only source code it would track in the repo would be scripts and build tools, etc.

This would keep LFE nice and clean and allow us to experiment with a release process, scripting, etc., in a way that wouldn't impact the LFE repo (rvirding/lfe) at all ...

We could call it OLP ;-)

**Comment by oubiwann** [comment]
I couldn't resist ...

https://github.com/lfe/olp

**Comment by oubiwann** [comment]
Okay, in the repo linked above, I have created an LFE submodule that gets put in `./lfe` (a la the `erts` directory in the OTP setup) and a `lib` directory that contains library submodules -- right now, just `ltest` and `lutil` (a la the `lib` directory in the OTP setup). I'll continue playing with this in the various tickets that I (or others) create here:
- https://github.com/lfe/olp/issues/1

That ticket is intended to track a first release of OLP as an exploration of _one_ possible way to do an OTP-like LFE release with bundled lfex libraries. If that effort is successful, it will satisfy the goals of this ticket (#300). If it is unsuccessful, it should at the very least inform us on how to precede in a better way.

**Comment by oubiwann** [comment]
Okay, so I guess I made some time for this tonight :-)

Gentle progress is underway -- up to and including a very, very early build of OLP using rebar3/relx. The README on the project has all the details (which are few so far).

I've created a bunch of tickets to track work and plan forthcoming tasks.

**Comment by yurrriq** [comment]
Awesome! We should create a branch of exemplar that builds on OLP soon, since it only needs lutil and then ltest for testing.

**Comment by oubiwann** [comment]
Yeah, I would suspect that once we have a release-building mechanism in place, we'll be adding libs like wildfire :-) (I'm designing this such that all we should have to do is add a submodule for a new library in `./lib` and the rest will be automatic ... barring special things like libraries which create executables, etc.)

**Comment by oubiwann** [comment]
So, the olp project where this is being tracked seems like a good approach. I haven't run into any issues with it, others have tried it, and it closely follows the Erlang Way. I think that we can close this ticket, given that a way has indeed been come up with (of course being open to change/adaptation/etc).
