### ISSUE TITLE
[clj] Conj is not actually variadic for lists

### ISSUE THREAD

**Issue by skovsgaard** [lfe/lfe#308]
Given enough arguments, `conj` fails for lists with errors like `clj:conj/8 is not defined`.

I'll get to work on fixing this and adding better tests for `conj` with many arguments as soon as I can, but just putting it out there that it's an issue.

**Comment by yurrriq** [comment]
You should PR into [my `feature/clj/fixes` branch](https://github.com/yurrriq/lfe/tree/feature/clj/fixes) so we can bake this fix into #304, if you get to it before @rvirding merges #304, that is.

**Comment by skovsgaard** [comment]
I'll try. I don't have the time right now but with any luck I'll look at it later today.

**Comment by yurrriq** [comment]
Sounds good. I'm going to bed soon anyway :smile:. I'll take a quick look though any see if anything jumps out.

**Comment by yurrriq** [comment]
I've had some possibly related issues with `clj:str` btw. I think I have a failing case in my local [lfe-rebar3/lodox](https://github.com/lfe-rebar3/lodox) clone. I'll see if I can find it tomorrow.

**Comment by skovsgaard** [comment]
Cool. The sooner we catch these the better.

**Comment by yurrriq** [comment]
Agreed. Nothing jumps out right away :confused:. Good luck!
