### ISSUE TITLE
[clj] Handle additional patterns in if{,f}-let

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#311]
See discussion on #305.

- [x] Add catch all clauses to prevent `case_clause` errors as discussed [below](https://github.com/rvirding/lfe/issues/311#issuecomment-282511971)
  - [x] `if-let`
  - [x] `iff-let`

**Comment by rvirding** [comment]
Can this be closed?

**Comment by yurrriq** [comment]
Yeah.

**Comment by yurrriq** [comment]
Well, it looks like we aren't handling the `#(ok ...) | error` idiom as discussed. I think I'd rather not support that directly. We should, however, probably add a catch-all clause so if I do something like this:

```clj
(if-let [`#(ok ,val) (progn 'error)]
  val
  'oh-no)
```

... then I don't get a case clause error.

**Comment by yurrriq** [comment]
https://github.com/yurrriq/lfe/commit/e231e8325765cde4ec3faa73d57bb5064a35620b
