### ISSUE TITLE
Emacs support - sp-bacward-up-sexp is inconsistent with paredit's paredit-backward-up

### ISSUE THREAD

**Issue by bigos** [lfe/lfe#313]
I have discovered strange problem playing with the following code from  
`examples/gps1.lfe`
I was experimenting with finding opening bracket and noticed that paredit and smartparens give different results when the code is in the *.lfe file. The same code copied and pasted to the scratch buffer didn't show the inconsistency.

In the code example that you can see at the bottom of the post, when you go to the (: io fwrite) and try to use sp-backward-up-sexp the cursor will jump to the (progn . With the same code copied to scratch buffer sp-backward-up-sexp behaves the same as paredit equivalent and jumps to (:.

```
;; Print a message and update *state* if op is applicable.
(defun apply-op (op)
  (if (every (fun achieve 1) (op-preconds op))
    (progn
      (: io fwrite '"executing ~p\n" (list (op-action op)))
      (setvar *state* (set-difference (getvar *state*) (op-del-list op)))
      (setvar *state* (union (getvar *state*) (op-add-list op)))
      'true)))
```

**Comment by rvirding** [comment]
Sorry, I don't use smartparens or paredit but the standard emacs with just `lfe-mode` will jump to `(: ` when doing `backward-up-list` from inside the `(: ...)` form. And then up to `(progn ` and `(if ` and finally `(defun `. To me this feels natural.

**Comment by bigos** [comment]
That is what I was looking for. Thank you. :-)
