### ISSUE TITLE
Reuse variable in pattern matches for equality

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#314]
This discussion comes up once in a while with newcomers, i.e. "why can't I write this?"

```lfe
(defun equal?
  ([x x] 'true)
  ([_ _] 'false))
```

For now, we have to do something like this:

```lfe
(defun equal?
  ([x y] (when (=:= x y))
   'true)
  ([_ _]
   'false))
```

It might be nice to reuse variables in pattern matches for equality as [this related issue on Alpaca](https://github.com/alpaca-lang/alpaca/issues/86) suggests.

**Comment by rvirding** [comment]
This felt more "functional" but I have any strong objections to this. It would not create any compatibility issues though I would not allow it in a `lambda` only in a `match-lambda`.

**Comment by yurrriq** [comment]
:+1: for allowing variable reuse (for matching) in `match-lambda`!

**Comment by rvirding** [comment]
We can do this. In the next push to develop.

**Comment by yurrriq** [comment]
I'd like this behaviour in `case` as well, but I (think I) want the compiler to complain if I try to, e.g.

```lfe
(defun foo (y)
  (let ((x 42))
    (case y
      (x 'forty-two)
      (_ 'not-forty-two))))
```

**Comment by rvirding** [comment]
I am looking at adding implicit equality testing of variables in patterns I intend to leave the variable scoping as it is. This means that variables occurring in a pattern are new fresh variables and if you want to test them against variables outside the scope then you will need to do that explicitly. So @yurrriq in your case you are stuck with:

    (defun foo (y)
      (let ((x 42))
         (case y
           (x1 (when (=:= x1 x)) 'forty-two)
           (_ 'not-forty-two))))

**Comment by yurrriq** [comment]
Perfect!

**Comment by rvirding** [comment]
I have just pushed a first version of this into 'develop'. It seems to work but needs testing.

Variable scoping is still observed so explicit tests need to be added for variables already bound before the match. This differs from Erlang but we have kept importing variables into bitseg lengths.
