### ISSUE TITLE
Local Function Names Clashing With Core forms and Auto-Imported BIFs

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#318]
Another issue is how to handle defining a local function with the same name/arity as a BIF, specifically auto-imported BIFs which don't need the `erlang:` module prefix when calling them. This is handled differently in Erlang and Common Lisp, partly because of how syntax works.

In Erlang it is legal and well-defined what happens if you do this. "If a local function has the same name as an auto-imported BIF, the semantics is that implicitly qualified function calls are directed to the locally defined function, not to the BIF. The rationale behind this is to avoid that future additions to the set of auto-imported BIFs do not silently change the behavior of old code." [Erlang Expressions](http://erlang.org/doc/reference_manual/expressions.html#id80481)

In CL defining a function with the same name as one of the functions/macros in the book is undefined. This is basically saying don't do it, you are on your own if you do. There are other properties of the defined names which you should not try to change either.

What complicates the matter in LFE and lisp is that there is no syntactic difference between core forms and auto-imported BIFs so it is harder to differentiate between them. What happens now is that they have the same handling. While it is legal to define a function with the same name as a BIF or core form making an implicitly qualified call will always get the core form or BIF, never the local function.

One reasonable change would be to make it behave like Erlang for the auto-imported BIFs and keep the current behaviour for core forms.This would be reasonable. The only problem I see with this is that some core forms are "BIF-like" like cons and car while some have more "standard" names like call and maybe case.

What do you think?

**Comment by deadtrickster** [comment]
In CL you can shadow the symbol. And what complicates thing in CL is that you can use the same package in different files/project. So default no-no behavior makes sense. 
In Erlang module occupies only one file so it's easy to comprehend. I think LFE could stick with Erlang behavior - non-qualified call resolves to "nearest" form. Same for core forms.

Question: module A exports 'get'. Module B imports A. somewhere in B: `(get <Arg>)`. How get would be resolved?

**Comment by yurrriq** [comment]
@deadtrickster iirc the compiler will complain about `get/1` already being defined when you try to `(defun get (arg) ...)` after importing it.

It definitely works this way for `include-{file,lib}` not sure about `import`.

**Comment by yurrriq** [comment]
My main goal here is to be able to `(export (do 1))` in rebar3 providers. Beyond that, so long as the behaviour is well-defined and documented, I don't have strong opinions as of now.

**Comment by rvirding** [comment]
Looking over my compiler I think I am partially on the way to doing what I suggest, I just didn't realise it. :-) Need to clean up a bit internally.

**Comment by rvirding** [comment]
To be clear the order in which a call without an explicit module is resolved is:

1. Core forms, these cannot be shadowed
2. Flet/fletrec
3. Imported functions, these are translated to fully qualified calls
4. Local functions
5. Erlang BIFs
6. LFE BIFs

2 and 3 can never clash and 4 and 5 will never overlap. Maybe I should flip 5 and so that LFE bifs take precedence in case we do want to overlap in the future?

I have cleaned up the code now. :smile:

**Comment by rvirding** [comment]
LFE bifs now take precedence if they ever overlap in the future.
