### ISSUE TITLE
Possble error(s) parsing RabbitMQ Client .hrl in the LFE REPL

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#322]
Here's what I've run into:

```cl
lfe> (include-lib "amqp_client/include/amqp_client.hrl")
1: Warning: unable to translate record exchange
1: Warning: unable to translate record amqqueue
RESOURCE_LOCKED
lfe> 
```

Here's the source file:
 * https://github.com/lfe-support/rabbitmq-erlang-client/blob/master/include/amqp_client.hrl

That file includes two other `.hrl` files:
 * `rabbit_common/include/rabbit.hrl`
 * `rabbit_common/include/rabbit_framing.hrl`

When I try to include them in the REPL:

```cl
lfe> (include-lib "rabbit_common/include/rabbit.hrl") 
1: Warning: unable to translate record exchange
1: Warning: unable to translate record amqqueue
store_proc_name
```

```cl
lfe> (include-lib "rabbit_common/include/rabbit_framing.hrl")
RESOURCE_LOCKED
```
I don't *think* that last one isn't a problem -- but I would expect that `RESOURCE_LOCKED` would be the last thing defined in that include ... since that's what's displayed on stdout ... but it's not the last one defined.

**Comment by rvirding** [comment]
I use the erlang module epp to parse, load and expand the macros in the .hrl files. With some undocumented calls you can get it to return not only all the expand forms but also all the macro definitions it has found. It is from these I generate the corresponding LFE forms.

The first one is easy: these two records contain default values which are maps and the LFE <-> erlang translator doesn't yet handle maps. Don't why I never added that code but this is first time it has resulted in an error. I will fix it.

The second one is also easy: epp uses a map to store the macro definitions and just does a maps:to_list call to return the list of macros, hence the undefined order.

**Comment by oubiwann** [comment]
Oh, nice! Easy answers all around :-)

Thanks!

**Comment by rvirding** [comment]
I have added a patch to the LFE <-> erlang translator (in lfe_trans) so it can handle maps in expressions but not yet in patterns. This solves the immediate problem.

I also noticed I need to fix the variable handling. Properly going between scoped and unscoped  is not always as simple as it seems.

**Comment by rvirding** [comment]
This has been fixed with 2 commits about handling maps when translating code LFE <-> erlang. The variable scoping has been improved but it cannot handle all cases. Yet.
