### ISSUE TITLE
Beginner question about lambda-match

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#325]
Hi, I'm using LFE to learn the Litter Schemer book. I'm trying to write the `member?` function:
```
(defun member?
    ((E L) (when (and (is_atom E) (is_list L)))
        (lists:any 
            (match-lambda ((E2) (when (is_atom E2))) (=:= E2 E)) L)))
```
but the compiler punish me with:

```
lfe> (slurp "scheme")
scheme:23: head arity mismatch
scheme:23: illegal pattern: =:=
scheme:23: unbound symbol: E2
```

I think I did something wrong with the closure, Can anyone help me to figure it out?

Thank you guys for this alien technology 👽

**Comment by yurrriq** [comment]
I'm typing on my phone, but this should work:

```lfe
(defun member?
  ([e l] (when (and (is_atom e) (is_list l)))
    (lists:any
      (match-lambda
        ([e2] (when (is_atom e2))
          (=:= e2 e)))
      l)))
```

You indeed had some parens slightly out of place.

**Comment by yurrriq** [comment]
I would suggest to capitalize on (Lisp Flavoured) Erlang's pattern matching and avoid the built-in `lists:any/2`, though, and start with a template like this:

```lfe
(defun member?
  ([_e ()] ; match when the given list is the empty list.
   ...)
  ([e (cons e2 l)] (when ...) ; bind the head to e2 and the tail to l
   ...)
  ([_e _l]
   'false))
```

**Comment by lin7sh** [comment]
@yurrriq thank you. It works, it's difficult to familiarise with the LFE semantic without a Lisp experience. Thank for your help

**Comment by yurrriq** [comment]
You're welcome. I'm glad I could help. I can definitely see how it's tricky and the error messages aren't so helpful to newcomers...

Maybe this general pattern will help:

```lfe
(defun foo
  ([arg args ...] (when guard guards ...)
   body))
```

There should be some better general shapes in the docs. I'll find a link and paste it here.

**Comment by yurrriq** [comment]
https://github.com/rvirding/lfe/blob/develop/doc/src/lfe_guide.7.md
