### ISSUE TITLE
What's the meta-data in the define-macro form?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#327]
Hi, awesome lfe community!
I have 2 beginner questions:

1. I know how to use `defmacro` to do something like
```
(defmacro plus (arg1 arg2) `(+ ,arg1 ,arg2))
```
but soon I learned from the [lfe_guide](https://github.com/rvirding/lfe/blob/develop/doc/src/lfe_guide.7.md#core-forms), **defmacro** is a common lisp macro form, so I assume it defined in term of the core form **define-macro**. But I don't know what's the meta-data mean in the define-macro defination
```
(define-macro name meta-data lambda|match-lambda)
```
Can somebody show me how to write the a simple macro(like the **plus**) by using define-macro and where all these common lisp macro defined in the source code?

2. And I found out there a way in the language guide to get the macro definition at the run time
```
macroexpand-1 expr {{environment}})
```
but I failed to make it work
```
(macroexpand-1 plus)
exception error: #(unbound_symb plus)
```
Can somebody tell me how to do it correctly? So I figure out the macro definition myself without peeking into the source code
thank you

**Comment by lin7sh** [comment]
I close this, because people here might busy, I should find out other way to get involve with the LFE community, like mailing list or IRC

**Comment by yurrriq** [comment]
It's a placeholder for a future feature similar to Clojure's IMeta. IIRC we're also using it internally for storing docstrings. It's similar to an alist from Common Lisp except that each key/value entry is just a list, not a dotted pair. It works very similarly to how the optional metadata in the `defmodule` form works.

**Comment by yurrriq** [comment]
IIRC we're also using it internally for storing docstrings.

**Comment by lin7sh** [comment]
@yurrriq thanks for answering my question again. That's make sense now. However for my 2nd question, I still can't figure out that why `macroexpand-1` doesn't work, I tried both `(macroexpand-1 plus)` and `(macroexpand-1 plus $ENV)` in repl. it gives me an error :exception error: #(unbound_symb plus).

**Comment by yurrriq** [comment]
The `expr` there must be quoted, e.g.

```lfe
> (macroexpand-1 '(plus 1 2) $ENV) 
(+ 1 2)
> (plus 1 2)
3
```

**Comment by lin7sh** [comment]
@yurrriq   😅 thank you
