### ISSUE TITLE
How does the shiny OTP 20 affect LFE?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#328]
Hello guy,
I'm pretty exciting about [new OTP release](http://erlang.org/download/otp_src_20.0-rc1.readme). After reading through the release note, I found out some features might affect LFE like new dialyzer. Any one have some suggestion about it?

**Comment by arpunk** [comment]
I'm not sure about dialyzer but the modernized strings API works pretty neat with LFE (UTF-8) strings.

**Comment by yurrriq** [comment]
Does dialyzer finally support Core Erlang directly?? I'll have to read the release notes later. Thanks for the tip. @rvirding, where are you at with ldialyzer these days?

**Comment by arpunk** [comment]
From the release notes:

>  OTP-14369    Application(s): compiler, dialyzer, stdlib
>               Related Id(s): PR-1367
>
>               The format of debug information that is stored in BEAM
>               files (when debug_info is used) has been changed. The
>               purpose of the change is to better support other
>               BEAM-based languages such as Elixir or LFE.
>
>               All tools included in OTP (dialyzer, debugger, cover,
>               and so on) will handle both the new format and the
>               previous format. Tools that retrieve the debug
>               information using beam_lib:chunk(Beam, [abstract_code])
>               will continue to work with both the new and old format.
>               Tools that call beam_lib:chunk(Beam, ["Abst"]) will not
>               work with the new format.
>
>               For more information, see the description of debug_info
>               in the documentation for beam_lib and the description
>               of the {debug_info,{Backend,Data}} option in the
>               documentation for compile.

And the [PR](https://github.com/erlang/otp/pull/1367).

**Comment by yurrriq** [comment]
Awesome! Thanks, @arpunk and @josevalim!

**Comment by lin7sh** [comment]
@arpunk @yurrriq Sound good, but as a newbie, I still don't know how to write spec and type annotation and run dialyzer on lfe file, hope someone could write a short tutorial to show people like me the way to do it

**Comment by lin7sh** [comment]
@yurrriq I think @rvirding and all the other cool guys are on the way to a new erlang conference

**Comment by josevalim** [comment]
Please give the new chunk a try while in RC period so we can provide feedback before final is out. If you have any questions please let me know and I will be glad to help!

**Comment by yurrriq** [comment]
@josevalim, will do. I'll collect my thoughts/findings here.

**Comment by yurrriq** [comment]
@mko-io right now it's very much a WIP but this new chunk could change the game. Once we get it sorted I'd be happy to help write a tutorial.

**Comment by lin7sh** [comment]
Awesome

**Comment by rvirding** [comment]
When 20 comes out I will try it and fix it.
