### ISSUE TITLE
Necessary to double quote lambdas?

### ISSUE THREAD

**Issue by useronym** [lfe/lfe#329]
```
lfe> (defmacro test (var) `(lambda (x) '(x ,var)))
test
lfe> (macroexpand (test 5))                       
#Fun<lfe_eval.14.34076088>

lfe> (defmacro test (var) `'(lambda (x) '(x ,var)))
test
lfe> (macroexpand (test 5))                        
(lambda (x) '(x 5))
```

Is this normal?

**Comment by useronym** [comment]
Dysfun has pointed out that I don't quote the macro in macroexpand, however if I do, I can't get it to expand at all:
```
lfe> (defmacro test (var) `(lambda (x) '(x ,var)))
test
lfe> (macroexpand '(test 5))
(test 5)
```

**Comment by rvirding** [comment]
Sorry, what is it exactly you want to the lambda you return to do? Seeing you quote the list in the body you are generating a lambda which will ignore its argument and just return the list `(x <macro-arg>)`, in your example `(x 5)`. Do you want it to call the function `x` or the function passed as an argument in the variable `x`?

The reason the `macroexpand` doesn't work properly in your 2nd entry is that by default `macroexpand` only uses the predefined and exported macros. If you want it to handle local macros you need to pass in the environment containing the macro definitions which in the shell is the variables `$ENV`. So

```
lfe> (defmacro test (var) `(lambda (x) '(x ,var)))
test
lfe> (macroexpand '(test 5) $ENV)
(lambda (x) '(x 5))
```

**Comment by useronym** [comment]
The body of the lambda was just a stupid example, it wasn't supposed to do anything meaningful — I just wanted to see what it expands to.

Can I ask why macroexpand doesn't expand user-defined macros in the shell? It seems like a useful thing to have on by default when prototyping new macros. Also it contributed greatly to my confusion. Of course I only notice it now in the docs…

In any case this clears up my issue, so I'll mark it as resolved.
