### ISSUE TITLE
Bitstring types are not supported

### ISSUE THREAD

**Issue by KrzysiekJ** [lfe/lfe#330]
Let’s say we have a `.hrl` file containing:

```erlang
-type foo() :: <<>>.
```

Then including this file gives the following compilation error:

```
./foo.lfe:3: unknown type: (binary 2)
```

The same happens for the following:

```erlang
-type foo() :: <<_:256>>.
```

However, the following can be compiled:

```erlang
-type foo() :: <<_>>.
```

**Comment by rvirding** [comment]
No, these haven't been defined yet. I will fix them for the next version.

Note that the syntax
```
-type foo() :: <<_>>.
```
is illegal so you should be getting a parse error there.

**Comment by rvirding** [comment]
The latest push to develop contains support for the bitstring types. Check the documentation for syntax. Please test.

**Comment by KrzysiekJ** [comment]
Thank you, the compilation now passes.
