### ISSUE TITLE
Range types are not supported

### ISSUE THREAD

**Issue by KrzysiekJ** [lfe/lfe#331]
Let’s say we have the following `.hrl` file:

```erlang
-type foo() :: 1..10.
```

Then including this file gives the following compilation error:

```
./foo.lfe:3: unknown type: (range 2)
```

**Comment by rvirding** [comment]
The latest push to develop contains support for the range types. Check the documentation for syntax. Please test.

**Comment by KrzysiekJ** [comment]
Thank you, it seems to work (at least no compilation errors are raised).
