### ISSUE TITLE
how to write named lambda in LFE?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#333]
Hi, I'm still learning the mighty LFE by following the little schemer.
I'm writing `rember_f` in LFE
```
(defun rember-f (test?)
    (letrec-function ((rember-rec (match-lambda
        ((_ '()) '())
        ((a (cons h t)) (if (funcall test? a h)
            (rember-rec a t)
            (cons h (rember-rec a t)))))))
        (lambda (a t) (rember-rec a t)))) ; Can I return rember-rec without construct a "wrapper lambda"?
```
The last line I'm not sure about, In order to return the recursive lambda, I have to construct another "wrapper" lambda which works but seems not quite right for me, Is there a better way to write this?

**Comment by yurrriq** [comment]
This is not an answer to your question, but why not do the following instead:

```lfe
(defun rember-f (test?) ()
  (match-lambda
    ([_ ()] ())
    ([a (cons h t)]
     (if (funcall test? h a)
       t
       (cons h (funcall (rember-f test?) a t))))))
```

N.B. I'm looking at my fourth edition book as I write this.

**Comment by yurrriq** [comment]
Here's a really contrived example that should answer your question:

```lfe
(defmodule example
  (export (max 1)))

(defun max (x)
  (fletrec ((-max (y) (erlang:max x y)))
    (function -max 1)))
```

@rvirding, we're supposed to use `function` instead of `fun` these days, right?

**Comment by lin7sh** [comment]
@yurrriq help me again thank you. What's your fourth edition book? I'm willing to buy one if it's about LFE

**Comment by yurrriq** [comment]
I'm glad I could help! I meant my fourth edition copy of The Little Schemer.

**Comment by lin7sh** [comment]
@yurrriq I just tried your version that using function reference instead of construct "wrapper" lambda, I   compile both version into core erlang, they turn out to be the same:
```
'rember-f'/1 =
    %% Line 371
    fun (_test?) ->
    letrec
        'rember-rec'/2 =
        fun (_ 1 ,_ 0 ) ->
            case <_ 1 ,_ 0 > of
              <_ 2 ,[]> when 'true' ->
              []
              <_a,[_h|_t]> when 'true' ->
              case apply _test?
                   (_a, _h) of
                <'true'> when 'true' ->
                apply 'rember-rec'/2
                    (_a, _t)
                <'false'> when 'true' ->
                let <_ 3 > =
                    apply 'rember-rec'/2
                    (_a, _t)
                in  [_h|_ 3 ]
                ( <_omega> when 'true' ->
                  primop 'match_fail'
                      ('if_clause')
                  -| ['compiler_generated'] )
              end
( <_ 5 ,_ 4 > when 'true' ->
                ( primop 'match_fail'
                  ({'function_clause',_ 5 ,_ 4 })
                  -| [{'function_name',{'rember-f',1}}] )
            -| ['compiler_generated'] )
            end
    in  fun (_a,_t) ->
        apply 'rember-rec'/2
            (_a, _t)

```
So I guess the core form of function reference is internally constructing the "wrapper" lambda, so besides the aesthetic reason, what are the other reasons to choose `function`  over `fun`?

**Comment by yurrriq** [comment]
Interesting. That makes sense, though. What about the first approach I posted? That seems to more closely mirror the Scheme solution from the book, for better or for worse.

**Comment by lin7sh** [comment]
@yurrriq The first solution seems to construct a match-lambda for each recursion. I don't know whether this has the same cost as using `letrec-function`
