### ISSUE TITLE
Map constructor does not expand variables

### ISSUE THREAD

**Issue by KrzysiekJ** [lfe/lfe#335]
```lfe
(let ((foo 'bar)) (map foo 'bar))
```

leads to

```
exception error: #(illegal_mapkey foo)
```

It should however return `#{bar=>bar}`.

**Comment by yurrriq** [comment]
IIRC this is a known issue on certain releases of Erlang/OTP. For reference, which version are you on?

**Comment by KrzysiekJ** [comment]
19.3

```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
```

**Comment by yurrriq** [comment]
Hmm.. I want to say it was ~~19.1.x~~ 17.1.x. Also, I'm on 19.3 with LFE v1.2.1 and I get the following:

```lfe
lfe> (let ((foo 'bar)) (map foo 'bar))
#M(bar bar)
```

**Update**: I'm seeing the same behaviour when I compile it in contrived module:

```lfe
%%% example.lfe
(defmodule example
  (export (baz 0)))

(defun baz ()
  (let ((foo 'bar))
    (map foo 'bar)))
```

```bash
$ lfec example.lfe
$ lfe -e '(io:format "~p~n" (list (example:baz)))'
```

```erlang
#{bar => bar}
```

**Comment by KrzysiekJ** [comment]
Strangely, I’m not able to reproduce the bug now, neither on `develop` (  22b30a15af861b680d1ae607252195c384a7682a ) nor on `v1.2.1` and neither on `19.3` nor on `18.x`. Also it looks like map values in REPL have now correct form `#M(bar bar)` instead of the one I reported, `#{bar=>bar}`. Closing the issue then, assuming it has been some version issue on my side.
