### ISSUE TITLE
Pattern matching in case doesn't behave like the one in erlang

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#336]
The erlang code:
```
X = foo.
Y = bar.
T = bar.

case T of
    X -> io:format("X:~p T:~p ", [X, T]);
    Y -> io:format("Y:~p T:~p ", [Y, T])
end.

Y:bar T:bar ok
```

I can't make it work in LFE:
```
(set X 'foo)
(set Y 'bar)
(set T 'bar)

(case T (X (io:format "X:~p T:~p " `(,X ,T)))
(Y (io:format "Y:~p T:~p " `(,Y ,T))))       
X:bar T:bar ok ;;not Y:bar in erlang code

(case T (`,X (io:format "X:~p T:~p " `(,X ,T)))
(`,Y (io:format "Y:~p T:~p " `(,Y ,T)))) ;; backquote doesn't help either   
X:bar T:bar ok
```

The pattern matching in the lfe example seems to always shadow the binding T in the outer scope instead of do a symbol to symbol comparison like I intend to do in erlang case example. Any suggustion?

**Comment by rvirding** [comment]
Variables are scoped in LFE, which they are not in Erlang, they behave pretty much as they do in funs in erlang. So in a case variables occurring in the patterns are new, fresh variables which inside the case clause shadow variables bound before it. Same in let.

So you need to do:

```
lfe> (set x 'foo)
foo
lfe> (set y 'bar)
bar
lfe> (set t 'bar)
bar
lfe> (case t
lfe>   (x1 (when (=:= x1 x)) (io:format "x:~p t:~p " (list x1 t))) 
lfe>   (y1 (when (=:= y1 y)) (io:format "y:~p t:~p " (list y1 t))))
y:bar t:bar ok
```

**Comment by lin7sh** [comment]
@rvirding thanks for explaining this to me, I like the consistency of your design
