### ISSUE TITLE
Does all the core form start with # use eval when reading?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#348]
I just found a behaviour seems strange to me
`'(#(foo bar))` eval to '(#(foo bar))'
but
`'((tuple 'foo 'bar)) eval to ((tuple 'foo 'bar))

the I understand the 2nd case, because the quote makes the whole thing a list, but the 1st case seems strange, since I also put quote in the beginning, it should prevent all the evaluation.

The only explanation I can find is the `#` behave like  `#.(...)` in the doc Evaluation While Reading section. Am I correct about this? and Does all the other # started form like #M and #B behave the same?  
If there is a distinction between read time and macro expansion time, how does the following expression execute, I'm confused because backquote in LFE implemented as macro, so backquote should expand after #..., I can't wrap my head around this
(set `#(,a ,b) #(1 2))

----------
just read something about read macro, is '#' a read macro? If so how can I use this feature is LFE

**Comment by lin7sh** [comment]
I've search this issue in the common lisp books and found the the topic of read macro to explore. so close this

**Comment by yurrriq** [comment]
We don’t have reader macros in LFE. #(...) is the syntax for tuple literals, which can be thought of as auto-quoted. The ` and , syntax is for quoting and unquoting, respectively.

**Comment by lin7sh** [comment]
@yurrriq thanks for the explanation. Lisp is really deep
