### ISSUE TITLE
Call to non-existent function

### ISSUE THREAD

**Issue by KrzysiekJ** [lfe/lfe#350]
Dialyzer complains:

```
lfe_trans.erl:376: Call to missing or unexported function erl_parse:package_segments/1
```

From reading the comment I guess that this function used to exist before R16.

**Comment by rvirding** [comment]
Yes, it's from the bad old days when we still had the package experiment. There are no operational problems as the the pattern which would cause it to be called will never be generated now.

**Comment by KrzysiekJ** [comment]
The problem for me is that I get this warning on a fresh installation in a dependant project. See the job at https://gitlab.com/KrzysiekJ/ercoin/-/jobs/46933221 for an example. An interesting fact is that subsequent invocations of `make check` or `make dialyze` don’t yield the warning.

**Comment by KrzysiekJ** [comment]
So the actual problem is that Dialyzer returns non-zero status code when building PLT and warnings are emitted (despite the PLT being successfully built). Guess this is an issue on the Dialyzer side then.

Refs ninenines/erlang.mk#501.

**Comment by rvirding** [comment]
If you include the `compiler` and `syntax_tools` applications in the PLT then the `cerl`  and `erl_syntax` modules will known. I will work out a way to remove the call to the unknown function.

**Comment by rvirding** [comment]
Just checked the package handling disappeared in R16 so maybe we can skip supporting R15, though it might break it for someone 😄

**Comment by oubiwann** [comment]
I think I'd be okay not supporting R15 anymore ;-) I've tended to be the advocate for supporting old versions, but R15 was Dec 2011 and R15B03-1 was a year later; that's ages for software. R16B03-1 was Jan 2014; 4 years of compatibility seems generous. As a comparison, Ubuntu provides 5 years of support for their LTS releases ...

**Comment by oubiwann** [comment]
Btw, the official Erlang Docker images don't go past 17.5 ...

**Comment by oubiwann** [comment]
We do still run TravisCI against R16B03-1 ... but that's the oldest.

**Comment by oubiwann** [comment]
Okay, I see the code now -- I'm going to submit a PR that removes the pre-16 support ...
