### ISSUE TITLE
How to make export_type work for dialyzer?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#351]
LFE 1.3 dev branch works well with dialyzer in OTP 20, but I can't make the export_type attributes works
mod1.lfe
```
(defmodule mod1
    (export all))
    

(defspec (test 0)
    (() (mod2:t1)))
    
(defun test () 1)
```
mod2.lfe
```
(defmodule mod2
    (export_type (t1 0)))

(deftype t1
    (integer))
```

then I run the dialyzer with the following command
`dialyzer  -pa ~/repo/lfe/ebin mod2.beam mod1.beam`

and I got the warning:
```
 Proceeding with analysis...
Unknown types:
  'mod2':t1/0
 done in 0m0.22s
done (passed successfully)
```

It would be great, if someone can help me to make it work

**Comment by rvirding** [comment]
Will check this and see what is happening. You are compiling the files with the debug-info option otherwise no type information is saved?

**Comment by lin7sh** [comment]
@rvirding I do use the debug-info flag as you told me before. I think this is a bug due to the core_erlang code generation

**Comment by lin7sh** [comment]
@rvirding nice! thanks again
