### ISSUE TITLE
Bug report: bitstring concatenation in lfe_shell

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#352]
Hi, all
the following code works:
```
(defun test-bit ()
    (let ((a (binary (3 (size 2))))
        (b (binary (1 (size 1))))
        (c (binary (15 (size 4)))))
        (binary (a bitstring) (b bitstring) (c bitstring))))
lfe> (utils:test-bit)
#B((127 (size 7)))
```
but it fails to work in lfe_shell
```
lfe> (set a (binary (3 (size 2))))
#B((3 (size 2)))
lfe> (set b (binary (1 (size 1))))
#B((1 (size 1)))
lfe> (set c (binary (15 (size 4))))
#B((15 (size 4)))
lfe> (set d (binary (a bitstring) (b bitstring) (c bitstring)))
exception error: #(undefined_bittype 'lfe_shell)
```

**Comment by rvirding** [comment]
It has to do with c/1 being being a shell macro so it is expanded to "(call 'lfe_shell 'c bitstring)" when building the bitstring expression. Your function test-bit/0 was defined inside the module utils where there is no c macro defined so there is no expansion.

**Comment by lin7sh** [comment]
@rvirding aha! That's the reason. thanks for the explanation
