### ISSUE TITLE
Publish more current version to Hex

### ISSUE THREAD

**Issue by filmor** [lfe/lfe#358]
The version currently on Hex is 1.2.0 which is a bit dated, can you publish a newer one?

**Comment by arpunk** [comment]
@rvirding seems that @yurrriq might know more about this: https://hex.pm/packages/lfe

**Comment by yurrriq** [comment]
Both of us are owners of the package. Let me know how I can help.

**Comment by filmor** [comment]
Seeing that 2.0.1 is published now, I'd count this as fixed. Thanks a lot :)
