### ISSUE TITLE
OTP 21 dialyzer warning:  Call to missing or unexported function erl_parse:package_segments/1

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#360]
Just build PLT for recompiled LFE in OTP 21, the dialyzer throws me the following warning:
```
mko_io@Yorda.local:$ dialyzer --add_to_plt --apps lfe      
  Compiling some key modules to native code... done in 0m0.48s
  Adding information to /Users/mko_io/Repo/.dialyzer_plt...
lfe_trans.erl:404: Call to missing or unexported function erl_parse:package_segments/1
Unknown functions:
  packages:concat/1
 done in 0m4.71s
done (warnings were emitted)
```

**Comment by rvirding** [comment]
The issue here is the same as in #357, these were used in an experimental package feature which survived for many releases but disappeared in R16. Maybe we could just drop guaranteed pre-R16 support?

**Comment by lin7sh** [comment]
Vote for dropping the unused feature before R6.
