### ISSUE TITLE
macro fails to expand inside function/2 and function/3 core form

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#362]
I just found this weird behaviour, I think it might be a bug:

```
cat test.lfe

(defmodule test
     (export all))

(defmacro m1 () 'mod1)
(defmacro f1 () 'fun1)

(defun get-fun ()
    (function (f1) 0))

(defun get-mfa ()
    (function (m1) (f1) 0))
    
(defun test ()
    (foo (m1) (f1) 0))
```

and after use `lfec +to-expand test.lfe`, get-fun and get-mfa don't expand, but the test has expanded as expected
```
 #((define-macro m1 () (match-lambda (((list) $ENV) 'mod1))) 35)
 #((define-macro f1 () (match-lambda (((list) $ENV) 'fun1))) 36)
 #((define-function get-fun () (lambda () (function (f1) 0))) 38)
 #((define-function get-mfa () (lambda () (function (m1) (f1) 0))) 41)
 #((define-function test () (lambda () (foo mod1 fun1 0))) 44)
```

**Comment by rvirding** [comment]
It is not really a bug but maybe slightly confusing. The `function/2/3` forms are actually literal values for references to functions so it is `(function mod foo 3)` and `(function bar 2)`. Looks similar to `fun/2/3` which are actually macros and expanded to lambdas while the `function` forms are not macros and are handled by the compiler. That is why there is no macro-expansion in them.

Perhaps they should have a different more "literal" syntax like `#f(mod foo 3)`?

**Comment by rvirding** [comment]
It is taken loosely from CL and there is the abbreviation `#'` which can be used and expands to `function`. So
```
#'foo/2     ==> (function foo 2)
#'foo:bar/3 ==> (function foo bar 3)
```

**Comment by lin7sh** [comment]
Now it makes sense, so literal means the term constructed in the parsing(reading time), like #(a b c), so the macro expand comes later than that. But I still think it could be useful to use macro to construct it like the module name expansion.

**Comment by lin7sh** [comment]
wow that's interesting. I think there still some magic I need to explore in your `lfe_macro` module
