### ISSUE TITLE
How does the foo:bar macro expand to : foo bar?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#364]
Hi guys,
After digging into the macro stuff and source code of lfe_macro.lfe, I still can't figure out how `foo:bar` macro works, for me the only solution is to use a macro to match anything and filter it down to the symbol contains the `:` in between, but it seems terribly inefficient. Can anyone give me an idea?

thank you

**Comment by rvirding** [comment]
To put it mildly it is a bit of a hack. The last clause which does something in `lfe_macro:exp_predef/3` which tests if the first element of the list is an atom and tests whether it contains ONE `:` and if so splits the atom into 2 and returns a `(: mod fun ...)`. This will be caught the next time as a form is continually expanded until it expands no more.

```
exp_predef([Fun|As], _, St) when is_atom(Fun) ->
    case string:tokens(atom_to_list(Fun), ":") of
        [M,F] ->
            {yes,[':',list_to_atom(M),list_to_atom(F)|As],St};
        _ -> no                                 %This will also catch a:b:c
    end;
```

This was really the only way I could do it. An alternative would have been to handle `foo:bar` when parsing but that doesn't feel right. It could still be done but it mightn't be backwards compatible.

**Comment by lin7sh** [comment]
@rvirding thanks for explaining the detail, so as I thought` foo:bar` does have some performance cost, comparing to` : foo bar`. I think this is an unsolvable issue, from erlang perspective `foo:bar` is the "correct way", but doesn't fit very well in lfe, but if we adapt to prefix notation, `: foo bar` even feel natural for me and syntactically looks good, it's like Forth colon definition :-)
