### ISSUE TITLE
Weird compiler warning about record match

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#365]
Hi,
trying to compile the following code:
```
(defrecord rec
    (x (1 2))  y)
        
(defun test1
    ((n r)
        (let (((match-rec x v) r))
            (set-rec r x (cons n v)))))

(defun test2
    ((n r)
        (let (((tuple 'rec v _) r));; this throws the same warning too even without record match
            (set-rec r x (cons n v)))))
```
both test1 and test2 gives me a warning
```
this clause cannot match because a previous clause at line 11 always matches 
```
Any idea where I did wrong?
Thank you

**Comment by rvirding** [comment]
Your definition of `rec` has the field `x` twice. I don't quite know why this should give the warning you got though and will check it out.

**Comment by lin7sh** [comment]
@rvirding It's a typo, I've fixed it in the post

**Comment by oubiwann** [comment]
I'm going to close this; we can always create a new ticket for better error messages around duplicate field entries in records, if anyone so desires ...
