### ISSUE TITLE
no logger present error is OTP21

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#367]
I've found this error after I upgrade in OTP21 on a freebsd 12 machine, you can reproduce the error by first get into lfe shell, then load any module ```(l 'crypto)``` then exit lfe using ```(q)```. the the console console generates thousand lines of identical errors:

```> (no logger present) unexpected logger message: {log,error,"Error in process ~p with exit value:~n~p~n",[<0.76.0>,{undef,[{io,format_error,[terminated],[]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]}]}],#{error_logger=>#{emulator=>true,tag=>error},gl=><0.64.0>,pid=><0.76.0>,time=>1548992990703775}}```

the erlang shell doesn't have this problem though.

I thought it was Erlang's installation problem at first, so I delete /usr/local/lib/erlang* and reinstall through package manger(pkg on FreeBSD), and recompile lfe, then the error's still there, then I reinstall the freebsd vm, and reinstall everything back, and error persists.

any ideas?

**Comment by haetze** [comment]
Did you install the `erlang` package or the `erlang-runtime21-21.2` package? The former installs version 19 and has the described error, version 21 doesn't. (At least in my tests)
Note: I tested both versions through a install with ports but I expect the package to behave similarly.

**Comment by lin7sh** [comment]
@haetze I do install the erlang-runtime21 package, I have several freebsd-12 machines(raspberry like small computer) running, none of them have the problem, this error only appear in a VPS

**Comment by oubiwann** [comment]
I have no idea about this issue, but I did do some Googling around and came across these:
 * https://groups.google.com/forum/#!topic/erlang-programming/zFfB7qc3oa4
 * https://gist.github.com/robertoaloi/1184144#gistcomment-48488
 * https://github.com/erlang/rebar3/issues/1982

I get the sense from these that this isn't an LFE bug ... I'm going to update the ticket tag accordingly, until we know better.

**Comment by lin7sh** [comment]
@oubiwann It is indeed an erlang vm related bug, and it only occurs on my qcloud VPS server, so I close this issue as it doesn't relate to LFE
