### ISSUE TITLE
Disable rendering of banner with CLI flags

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#369]
* [x] When passed `-noshell`, LFE should not render the banner
* [x] When passed `-nobanner`, LFE should not render the banner

Note that this should address the concerns expressed in #312.

**Comment by oubiwann** [comment]
Work being done in this branch: https://github.com/oubiwann/lfe/tree/enhancement/369/optional-banner

**Comment by oubiwann** [comment]
Okay, this is done now. With `-noshell`:
```
$ ./bin/lfe -noshell
```
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

lfe> 
```

With `-nobanner`:
```
$ ./bin/lfe -nobanner
```
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

lfe> 
```

Business as usual:

```
$ ./bin/lfe
```
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

   ..-~.~_~---..
  (      \\     )    |   A Lisp-2+ on the Erlang VM
  |`-.._/_\\_.-':    |   Type (help) for usage info.
  |         g |_ \   |
  |        n    | |  |   Docs: http://docs.lfe.io/
  |       a    / /   |   Source: http://github.com/rvirding/lfe
   \     l    |_/    |
    \   r     /      |   LFE v1.3-dev (abort with ^G)
     `-E___.-'

lfe> 
```

**Comment by oubiwann** [comment]
Since this branch is based upon one that updates TravisCI, I'll wait until #374 is merged before submitting this PR.

**Comment by lin7sh** [comment]
I think @rvirding  would like to embed his Ascii Art in every LFE shell :-)

**Comment by oubiwann** [comment]
Hehehe ... well, full-disclosure: that's my ASCII art ;-)

**Comment by oubiwann** [comment]
@rvirding (or anyone, really): one of the things I'd like feedback on in this PR is the nested `case` I used here:
 * https://github.com/oubiwann/lfe/blob/enhancement/369/optional-banner/src/lfe_shell.erl#L233

It's been years since I've written Erlang, and I feel sooo rusty; I feel certain there's a better (possibly pattern-matching) idiom I would have used when my Erlang was fresh ...

**Comment by lin7sh** [comment]
@oubiwann please reveal more  secret history of how LFE made

**Comment by oubiwann** [comment]
Hehehe -- well, @mko-io, I happened to be reading through old entries in the mail list today, and came across this thread:
 * https://groups.google.com/d/msg/lisp-flavoured-erlang/XA5HeLbQQDk/Jdbf0KJV7dUJ

Note that one of the links in that thread has changed, and is now here:
  * http://docs.lfe.io/current/history.html

**Comment by oubiwann** [comment]
It might be nice to do this simultaneously with support for this from `rebar.config` ... See #103
