### ISSUE TITLE
Where can I try out the latest features that haven't been merged into the LFE develop branch?

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#379]
The LFE project tends to have a backlog of unmerged PRs, since the core contributors have many other responsibilities. However, a `bleeding-edge` branch is maintained, which includes all PRs that 1) seem sane, and 2) pass the LFE build and test suite in TravisCI.

That branch is currently maintained here:
 * https://github.com/lfe/lfe/tree/bleeding-edge

Any issues you uncover, please report to [the appropriate PR](https://github.com/rvirding/lfe/pulls) -- thanks!

Enjoy :-)

**Comment by rvirding** [comment]
We will have to work out how to manage the LFE repo. There are a number of things I have to try and merge in. I haven't had much time to work on it lately, but I will try and better myself.
