### ISSUE TITLE
Regression: Can't compile records from YAWS on Erlang 17.5 when upgrading from LFE 1.2.1 to 1.3

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#380]
**LFE versions affected**: the transition from 1.2.1 to 1.3-dev (commit 59165a0 to the merge of commit 4c8732f)
**Erlang**: Only seen in 17.5 so far
**YAWS**: for LFE 1.3, issues shows up in all tested versions of YAWS (2.0.1 through 2.0.6)
**Impact/Urgency**: low

I've spent the greater part of today trying to narrow this down (needed to determine if the error was in lfest, YAWS, or LFE). Finally found that the difference was between LFE v1.2 and v1.3. When I have more time, I can `git bisect` to find the exact commit that causes the issue.

What I found out last night, though, was I coldn't upgrade the lfest web-app routing project from LFE 1.2 to 1.3 due to an error in the tests (see https://github.com/lfex/lfest/issues/4).

This error shows up in all commits after the v1.3 release and for all versions of YAWS since 2.0.1 (didn't go back any further than that, since that was the last version that I worked with a few years ago). The most recent version of YAWS (2.0.6) works just fine with LFE v1.2, though (as, in fact, do all tested versions of YAWS). 

The strack trace reported by `rebar3` is as follows:

```
===> Uncaught error: {case_clause,
                             {error,
                              {undef,
                               [{erl_internal,is_type,[frag_type,0],[]},
                                {lfe_lint,check_type_name,3,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,357}]},
                                {lfe_lint,check_type_def,4,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,339}]},
                                {lfe_lint,collect_form,2,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,208}]},
                                {lists,foldl,3,
                                 [{file,"lists.erl"},{line,1261}]},
                                {lfe_lint,collect_module,2,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,192}]},
                                {lfe_lint,check_module,2,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,176}]},
                                {lfe_lint,module,2,
                                 [{file,
                                   "/Users/dmcgreggor/lab/lfe/lfest/_build/test/plugins/lfe/src/lfe_lint.erl"},
                                  {line,163}]}]}}}
===> Stack trace to the error location:
[{lr3_comp,compile,3,
           [{file,"/Users/dmcgreggor/lab/lfe/lfest/_build/default/plugins/lfe-compile/src/lr3_comp.erl"},
            {line,27}]},
 {rebar_base_compiler,compile_each,3,
                      [{file,"/opt/rebar3-3.10.0/src/rebar_base_compiler.erl"},
                       {line,185}]},
 {lr3_comp,'-compile_normal_app/1-lc$^0/1-0-',4,
           [{file,"/Users/dmcgreggor/lab/lfe/lfest/_build/default/plugins/lfe-compile/src/lr3_comp.erl"},
            {line,65}]},
 {lr3_comp,compile_normal_app,1,
           [{file,"/Users/dmcgreggor/lab/lfe/lfest/_build/default/plugins/lfe-compile/src/lr3_comp.erl"},
            {line,65}]},
 {lr3_comp,'-compile_normal_apps/1-lc$^0/1-0-',1,
           [{file,"/Users/dmcgreggor/lab/lfe/lfest/_build/default/plugins/lfe-compile/src/lr3_comp.erl"},
            {line,47}]},
 {lr3_comp,compile_normal_apps,1,
           [{file,"/Users/dmcgreggor/lab/lfe/lfest/_build/default/plugins/lfe-compile/src/lr3_comp.erl"},
            {line,47}]},
 {rebar_core,do,2,[{file,"/opt/rebar3-3.10.0/src/rebar_core.erl"},{line,154}]},
 {rebar_hooks,run_provider_hooks_,6,
              [{file,"/opt/rebar3-3.10.0/src/rebar_hooks.erl"},{line,48}]}]
```

This stack trace happens when testing [this file in the lfest project](https://github.com/lfex/lfest/blob/master/src/lfest.lfe).

To narrow things down, I commented out all the calls to the generated record functions as well as the actual `include-lib`, and then the file compiles correctly. Even with `include-lib` only, and no calls to the record functions, I still get the stacktrace above.

**Comment by oubiwann** [comment]
This is the YAWS file that LFE 1.3 can't handle right now: 
 * https://github.com/klacke/yaws/blob/master/include/yaws_api.hrl

**Comment by oubiwann** [comment]
Oh dear -- I should have specified: I only see this on Erlang 17.5, not anything higher (and I haven't tested against anything lower).

I'll update the ticket description with that info ...

**Comment by oubiwann** [comment]
1.2.1 is okay ...

**Comment by oubiwann** [comment]
Finally narrowed it down:
 * The issue popped up between 59165a0 and 4c8732f
 * I've confirmed this after multiple checks (since it's late and I'm sleepy, I might have missed something)
 * Change 59165a0 is just three commits after the releases for 1.2.1
 * Here's the diff: `git diff 59165a0..4c8732f` where something broke the LFE compiler's ability to work with the YAWS include file 

I keep falling asleep at the keyboard, waking up to gibberish in this text area; definitely not going to try to debug anything else tonight ...

**Comment by oubiwann** [comment]
Little more awake now ...
* `59165a0` - "Make even #'=:=/2 generate (function =:= 2)" (last working commit)
* `4c8732f` - "Merge branch 'dev-types' into develop" (the commit where the break occurs)

Looks like the `dev-types` branch is gone from Github, and it seems that I don't have a local copy of it, so I can't dig into which specific change in that branch caused the problem ... unless ... 

Ah-ha! Git's graphing log output to the rescue:

```
* aa1c7fe 2 years, 5 months ago Fix error message for {illegal_literal,Lit} error <Robert Virding>
*   4c8732f 2 years, 5 months ago (HEAD, unstable/regression) Merge branch 'dev-types' into develop <Robert Virding>
|\  
| * 8ab0bb7 2 years, 6 months ago Improve checking/reporting of errors in function definitions <Robert Virding>
| * d2ef7dc 2 years, 6 months ago Fix handling of new old record type formats <Robert Virding>
| * 42096b9 2 years, 6 months ago Make checking of type vars behave the same as in erlang <Robert Virding>
| * a3b0bc7 2 years, 6 months ago Improve spec docs definitions and examples <Robert Virding>
| * 29ae52b 2 years, 6 months ago Add type/spec macros <Robert Virding>
| * b3cf1f5 2 years, 6 months ago Improve checking of functione metadata <Robert Virding>
| * f258247 2 years, 6 months ago Add function specifications <Robert Virding>
| * 098115e 2 years, 6 months ago Add checking of type definitions <Robert Virding>
| * 88f7381 2 years, 7 months ago Add rudimentary type documentation <Robert Virding>
| * 97b5eba 2 years, 7 months ago Fix handling of record types to be more consistent. <Robert Virding>
| * 1f8cb50 2 years, 7 months ago Add generation of type and record attributes in core erlang <Robert Virding>
| * f49bec0 2 years, 7 months ago Add maps <Robert Virding>
| * 87141ed 2 years, 7 months ago Add union and function types <Robert Virding>
| * 9092674 2 years, 7 months ago Add handling of records <Robert Virding>
| * 1d945ac 2 years, 7 months ago (refs/bisect/bad) First save commit <Robert Virding>
* 59165a0 2 years, 6 months ago Make even #'=:=/2 generate (function =:= 2) <Robert Virding>
* d722d36 2 years, 6 months ago (tag: v1.2.1, tag: 1.2.1, regression, refs/bisect/good-d722d3662b191b61310dc9bba78f9a77f512b742) Merge branch 'develop', this is v1.2.1 <Robert Virding>
```

I'll dig through those sub-commits later, and see which commit in the branch introduced ther regression with 17.5.

Oh, it looks like in my sleep-depraved haze last night, I missed that `git bisect` has already done that for me: the above is showing that the first commit of that branch is the one that introduced the regression. The files for that commit:

```
1d945ac 2016-10-02 (refs/bisect/bad) First save commit <Robert Virding>
3       0       src/lfe_macro.erl
43      6       src/lfe_macro_include.erl
131     0       src/lfe_types.erl
```

If we take a guess thjat the `src/lfe_macro_include.erl` file is responsible here ... the diff for that file is, well a little too big to paste here, so I'll just share this: `git diff 59165a0..1d945ac src/lfe_macro_include.erl`.

**Comment by oubiwann** [comment]
Also, I should say that this is not a big deal :-) It only affects the oldest version of Erlang, of all the versions I care about (I no longer support 16 in my LFE projects). Mostly I'm doing this out of curiosity .... and the off chance that the fix would be straight-forward.

This only affects LFE YAWS/web app projects, and for all of those that I still use, if I upgrade to the latest LFE, I will also upgrade to the latest Erlang.

I'll add a note to the description that indicates that this is no biggie ...

**Comment by rvirding** [comment]
The reason for this is that later versions of the compiler generate type information which the erlang compiler can use to generate type information which is used by dialyzer, amongst other things. It uses the function `erl_internal:is_type/2` which wasn't defined until Erlang 18.0. Hence the problem running later versions of LFE with older versions of Erlang.

I don't really know how I should solve this problem. Until now I have tried make all versions of LFE runnable on Erlang R16 and later. This has failed here. Maybe I should change my goal and for each version of LFE specify which versions of Erlang it can run on.

It would make it easier but be a bit more limiting for users.

**Comment by oubiwann** [comment]
I'm comfortable with that, really. This is how I've been releasing Erlang/Jinterface/Clojure libs (each release tied specifically to a set of versions). I provide a table in the README letting users know which is safe to use, e.g.:
* https://github.com/clojang/jiface#dependencies-

**Comment by oubiwann** [comment]
We're no longer supporting versions of Erlang older than 19.

Closing ...
