### ISSUE TITLE
Fix -lfe_eval in lfe command

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#382]
I am looking at fixing up the lfe command. It currently handles the -lfe_eval flag completely wrong, to be more precise not at all. I have it working but would like some feedback. If you write lfe -lfe_eval "<something>" "<more>" "<even more>" what should it do?  One thing would be to evaluate each of the strings one after the other.

**Comment by starbelly** [comment]
@rvirding I would expect this to evaluate each string in sequential order.

**Comment by oubiwann** [comment]
yeah, I would expect something similar ... basically each additional string arg would represent newline-separated string values in an `.lfe` file. This is the same behaviour that `git commit -m "line" -m "line" -m "line"` has, btw ...

**Comment by rvirding** [comment]
That's pretty much where I am now. You can have multiple strings and they are evaluated in an LFE repl one after the other so you can "pass along" values. However each is parsed separately so you can't have them split into parts. If a script name and args come afterwards then the script is evaluated in the same shell.

If you have neither strings nor script then you enter into the normal LFE repl.

**Comment by rvirding** [comment]
I have pushed a commit to `develop` which handles this.

**Comment by oubiwann** [comment]
I'm assuming that 1) this is done, and 2) I am safe adding this to the 2.0 milestone?
