### ISSUE TITLE
Don't allow variable rebound in let* form?

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#383]
I'm writing some tests in common_test style for my lfe code. I found the let* behaviour is not consistent with Erlang semantic

```erlang
test_x_y_equal(_) ->
    X = 1,
    Y = 2,
    X = Y. %%throw a expected error
```

```lfe
(defun test_x_y_equal (_)
    (let* ((x 1)
              (y 2)
              (x y)))) ;;x is reboud to y which is 2, so it's not an assertion
```
I could make the test case less readable just write

```lfe
(defun test_x_y_equal (_)
    (let* ((y 2)
              (1 y)))) ;;now this line throw as expected exception error: no match of value 2
```
of course I can use some macrolet trick to get around that, but I'm not sure If I can just do it with normal let* form

btw I really like the erlang way to write test cases, every `=/2` is already an assertion, no extra assertion library need as other test frameworks in other languages, so I want this feature in lfe.

any ideas?

**Comment by rvirding** [comment]
When I designed LFE I decided to go with lisp and have scoped variables, which I personally prefer. That means that while you can have patterns and guards in function clauses and lets they will not allow to do an implicit match of variables from an outside scope. You have to give the inner variable a different name and then use an explicit equality test in a guard. Basically the same as you have to do in Erlang for a `fun` if you want to match on a variable in the head.

Also `let*` is defined to behave with nested bindings. In fact it is a macro which expands to nested `let`s.

    lfe> (macroexpand '(let* ((x 1) (y 2) (x y)) x))
    (let ((x 1))
      (let ((y 2))
        (let ((x y))
          (progn x))))

When we were designing/implementing Erlang we had a long discussion whether to have variable scoping or not. We finally decided to just leave it as it was but we weren't really convinced. That is why `let` is a reserved word in Erlang, just in case we would add lets later.

**Comment by lin7sh** [comment]
Hi Robert,
Your explanation on let* expansion make sense to me now, so every "sub let form" create a new scope according to the let scope rule. That's consistent design, great

I think the solution to mimic the erlang "=" operator in common_test matching would be using some macro tricks to expand the value not variable on the left side of the let form
