### ISSUE TITLE
Rebar3 bare compile fails

### ISSUE THREAD

**Issue by filmor** [lfe/lfe#384]
I'm not quite sure whether this is a bug on lfe or rebar3, but I'll start here :)

The lfe build process has a compile hook that runs

    bin/lfe bin/lfec -o $REBAR_DEPS_DIR/ebin src/*.lfe

When rebar3 is run in "bare" mode (in particular when lfe is used as a dependency of an Elixir project), `REBAR_DEPS_DIR` points to a wrong directory which makes the compile as it can't locate `lfe_comp` (or other modules).

Manually overwriting the output path in `rebar.config` as `-o ./ebin` fixes the issue.

**Comment by robinhilliard** [comment]
Thanks for the work-around @filmor :-).

**Comment by oubiwann** [comment]
This doesn't actually surprise me -- I've only recently seen the env var `REBAR_DEPS_DIR` in the LFE `rebar.config` (it was put there after I worked on the original rebar3 integration with LFE) and it felt fairly fragile to me. I've been wondering what a safer solution would be ... might end up pinging the rebar3 team about this ...

**Comment by filmor** [comment]
@tsloughter Do you have an idea what to do here? Is it expected that `REBAR_DEPS_DIR` is empty for bare compiles?
