### ISSUE TITLE
LFE fails to run all tests on Erlang 22

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#386]
Error message during build:
```
test/guard_SUITE.lfe: function basic_andalso_orelse/1+29:
  Internal consistency check failed - please report this bug.
  Instruction: {get_tuple_element,{x,0},3,{x,0}}
  Error:       {bad_type,{needed,{tuple_element,4}},{actual,{tuple,[3],#{}}}}:
...
===> Hook for ct failed!
```

**Comment by rvirding** [comment]
This works with Erlang 21 and 23 but not for 22. This is a weird one I don't know if I can fix as it is in the Erlang part.

**Comment by oubiwann** [comment]
Gonna do some reading and take some notes here in this ticket. Maybe by the end of that, we'll have an idea of what to do :-)

**Comment by oubiwann** [comment]
From http://blog.erlang.org/OTP-22-Highlights/:

> OTP 21:
```erlang
    {test,is_tagged_tuple,{f,9},[{x,0},2,{atom,myrecord}]}.
    {get_tuple_element,{x,0},0,{x,1}}.
    {get_tuple_element,{x,0},1,{x,2}}.
    {gc_bif,'+',{f,0},3,[{x,2},{integer,1}],{x,0}}.
    {test_heap,3,1}.
```
> OTP 22:
```erlang
    {get_tuple_element,{x,0},1,{x,0}}.
    {gc_bif,'+',{f,0},1,[{x,0},{integer,1}],{x,0}}.
    {test_heap,3,1}.
```
> The `is_tagged_tuple` instruction has been completely eliminated and as an added bonus one `get_tuple_element` was also removed.

**Comment by oubiwann** [comment]
Through a process of trial and error, I found that the error in the test first occurs in this part of the `let` block:

```lisp
     (line (test-pat 65 (case ()
                          (() (andalso (=:= (element 1 t) 'type)
                                       (=:= (tuple_size t) 4)
                                       (=:= (element 2 t) 'integers))
                           (+ (element 3 t) (element 4 t))))))
```

To be honest, though ... I'm not even sure why that test is structured the way it is? Isn't `(case () (() ...))`  functionally identical to `progn`? Oh ... just took a look at the `eif` macro, and the test may be trying to establish a similarity with the `case` in that macro? Hard to read for me ...

**Comment by oubiwann** [comment]
Okay, that PR I submitted (#412) comments out that one code block and the tests all pass now for all supported versions of Erlang.

**Comment by oubiwann** [comment]
Now that we've got improved support for Erlang 19-21 and 22-24, I'm going to take another look at this ...

**Comment by oubiwann** [comment]
Update: all tests are now passing!

So this should be fixed ... (unless a test has been commented out somewhere?)
