### ISSUE TITLE
Proper 1.1.1-beta is no longer available

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#387]
This is causing Erlang 17 (and maybe 16) TravisCI test runs to fail.

**Comment by oubiwann** [comment]
I've done a series of builds that add the latest proper (1.3.0), and I haven't yet gotten a successful test run yet :-(

**Comment by yurrriq** [comment]
I might be able to have a look in the next week or so.

**Comment by oubiwann** [comment]
We've got proper working again.
