### ISSUE TITLE
How to handle building LFE on different versions of Erlang

### ISSUE THREAD

**Issue by rvirding** [lfe/lfe#389]
As most have noticed it is getting rather messy to build LFE on different versions of Erlang. While it has worked with testing at compile time which version of Erlang we are using and then defining macros to indicate when something in the system has changed, for example NEW_RAND, now some of the alternate handling is getting pretty difficult. The stacktrace handling will not be trivial.

One idea I have is for me to make separate releases for the different versions which are then pre-packaged and ready for downloading and building. This should not be difficult to do **EXCEPT** for updating old versions. So if I do this it might mean that once a release has been made for an older version of Erlang maybe once an "old" release has been built then it will no longer be upgraded.

What do people think of this? Is anyone running LFE on older versions of Erlang?

**Comment by oubiwann** [comment]
I would vote for the option that is the least burden on you :-) Technically, I have absolutely no objections to you proposal!

**Comment by prokopiy** [comment]
It would be nice to have an LFE version for the latest Erlang. Older LFE releases could be frozen.

**Comment by oubiwann** [comment]
@prokopiy most BEAM projects provide a little more backwards compatibility than that. `rebar3`, for instance, runs their tests in CI/CD against 19, 20, 21, 22, and 23.

The new/updated LFE `rebar3` plugin is not supporting anything older than 19 for the simple matter that the rebar project isn't ... but that's a nice spread of versions, so I feel okay about it :-) 

But I do think we should do something similar to what you suggest: 
1. support some minimal set of Erlang versions
1. make sure we have CI/CD set up to use a test matrix against all of these
1. freeze the LFE -> Erlang version for older releases
1. provide all LFE versions in a table showing the corresponding Erlang versions supported for each

**Comment by oubiwann** [comment]
We're doing the build part of this with our CI/CD build setup using Github Actions:
* https://github.com/rvirding/lfe/actions

I'll leave the packaging part in Robert's capable hands! (but I gave his idea a thumbs-up).
