### ISSUE TITLE
[lfetool] [new library] generates warnings and linker errors

### ISSUE THREAD

**Issue by rprimus** [lfe/lfe#399]
Mon Aug 10 16:23:09 BST 2020

<details>
<summary>System details</summary>

- **OS**:
  - ProductName:	Mac OS X
  - ProductVersion:	10.15.6
  - BuildVersion:	19G73
- **erlang**: Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
- **lfe**: LFE v1.3
- **lfetool**: version=1.4.0
</details>

<details>
<summary>Output</summary>

: ; lfetool new library my-lib
Setting up starter library project my-lib ...
Initialized empty Git repository in /private/tmp/my-lib/.git/
Removing EUnit test files ...
rm: ./.eunit/*.beam: No such file or directory
make: [clean-eunit] Error 1 (ignored)
Getting dependencies ...
==> my-lib (get-deps)
Pulling lfe from {git,"git://github.com/rvirding/lfe.git",{tag,"v0.9.0"}}
Cloning into 'lfe'...
Pulling lutil from {git,"https://github.com/lfex/lutil.git",{tag,"0.5.1"}}
Cloning into 'lutil'...
Pulling ltest from {git,"git://github.com/lfex/ltest.git",{tag,"0.4.1"}}
Cloning into 'ltest'...
==> lfe (get-deps)
==> ltest (get-deps)
==> lutil (get-deps)
Cleaning ebin dir ...
Compiling project code and dependencies ...
==> lfe (compile)
Compiled src/lfe_scan.xrl
Compiled src/lfe_lib.erl
Compiled src/lfe_env.erl
Compiled src/lfe_pmod.erl
/private/tmp/my-lib/deps/lfe/src/lfe_shell.erl:116: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
/private/tmp/my-lib/deps/lfe/src/lfe_shell.erl:139: Warning: function new_state/2 is unused
Compiled src/lfe_shell.erl
/private/tmp/my-lib/deps/lfe/src/lfescript.erl:59: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
/private/tmp/my-lib/deps/lfe/src/lfescript.erl:179: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
Compiled src/lfescript.erl
Compiled src/lfe_comp.erl
Compiled src/lfe_gen.erl
Compiled src/lfe_io_format.erl
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:225: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:232: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:237: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:288: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:288: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:295: Warning: variable 'Env' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:295: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:295: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:359: Warning: function lambda_arity/1 is unused
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:730: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:786: Warning: variable 'Env' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:786: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:885: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:903: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:910: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:915: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:939: Warning: variable 'Env' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:939: Warning: variable 'L' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:939: Warning: variable 'St' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:1084: Warning: core_lib:set_anno/2 is removed; use cerl:set_ann/2 instead
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:1084: Warning: core_lib:set_anno/2 is removed; use cerl:set_ann/2 instead
/private/tmp/my-lib/deps/lfe/src/lfe_codegen.erl:1214: Warning: the guard for this clause evaluates to 'false'
Compiled src/lfe_codegen.erl
Compiled src/lfe_macro_record.erl
Compiled src/lfe_bits.erl
Compiled src/lfe_lint.erl
/private/tmp/my-lib/deps/lfe/src/lfe_init.erl:73: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
Compiled src/lfe_init.erl
Compiled src/lfe_scan.erl
/private/tmp/my-lib/deps/lfe/src/lfe_io_pretty.erl:23: Warning: export_all flag enabled - all functions will be exported
/private/tmp/my-lib/deps/lfe/src/lfe_io_pretty.erl:86: Warning: the guard for this clause evaluates to 'false'
Compiled src/lfe_io_pretty.erl
/private/tmp/my-lib/deps/lfe/src/lfe_macro_include.erl:28: Warning: export_all flag enabled - all functions will be exported
Compiled src/lfe_macro_include.erl
/private/tmp/my-lib/deps/lfe/src/lfe_ms.erl:302: Warning: function fetch_binding/2 is unused
Compiled src/lfe_ms.erl
Compiled src/lfe_trans.erl
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:128: Warning: variable 'M' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:132: Warning: variable 'M' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:485: Warning: function init_letrec_env/1 is unused
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:491: Warning: function extend_letrec_env/3 is unused
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:491: Warning: variable 'Fbs0' is unused
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:674: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:760: Warning: variable 'M' shadowed in 'fun'
/private/tmp/my-lib/deps/lfe/src/lfe_eval.erl:764: Warning: variable 'M' shadowed in 'fun'
Compiled src/lfe_eval.erl
/private/tmp/my-lib/deps/lfe/src/lfe_parse.erl:129: Warning: the guard for this clause evaluates to 'false'
Compiled src/lfe_parse.erl
/private/tmp/my-lib/deps/lfe/src/lfe_io.erl:165: Warning: the guard for this clause evaluates to 'false'
Compiled src/lfe_io.erl
/private/tmp/my-lib/deps/lfe/src/lfe_macro.erl:24: Warning: export_all flag enabled - all functions will be exported
/private/tmp/my-lib/deps/lfe/src/lfe_macro.erl:529: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
/private/tmp/my-lib/deps/lfe/src/lfe_macro.erl:542: Warning: erlang:get_stacktrace/0 is deprecated and will be removed in OTP 24; use use the new try/catch syntax for retrieving the stack backtrace
Compiled src/lfe_macro.erl
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:282: Warning: erl_lint:modify_line/2 is removed; use erl_parse:map_anno/2 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:372: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:439: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2470: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2473: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2476: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2651: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2680: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2682: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2694: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2696: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2711: Warning: erl_parse:set_line/2 is removed; use erl_anno:set_line/2
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2715: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2722: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
/private/tmp/my-lib/deps/lfe/src/lfe_qlc.erl:2726: Warning: erl_parse:get_attribute/2 is removed; erl_anno:{column,line,location,text}/1 instead
Compiled src/lfe_qlc.erl
Compiling c_src/lfeexec.c
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: sh(cc c_src/lfeexec.o $LDFLAGS -bundle -flat_namespace -undefined suppress  -L"/usr/local/Cellar/erlang/23.0.3/lib/erlang/lib/erl_interface-4.0/lib" -lerl_interface -lei -o priv/lfe_drv.so)
failed with return code 1 and the following output:
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)

ERROR: compile failed while processing /private/tmp/my-lib/deps/lfe: rebar_abort
make: *** [compile] Error 1
➜  /tmp
: ; cd my-lib
➜  my-lib git:(master) ✗
: ; ls -la
total 24
drwx------ 13 rprimus wheel 416 Aug 10 16:12 .
drwxrwxrwt  8 root    wheel 256 Aug 10 16:12 ..
drwx------ 10 rprimus wheel 320 Aug 10 16:12 .git
-rw-------  1 rprimus wheel 102 Aug 10 16:12 .gitignore
-rw-------  1 rprimus wheel 216 Aug 10 16:12 .travis.yml
-rw-------  1 rprimus wheel  51 Aug 10 16:12 Makefile
-rw-------  1 rprimus wheel 352 Aug 10 16:12 README.md
drwx------  5 rprimus wheel 160 Aug 10 16:13 deps
-rw-------  1 rprimus wheel 258 Aug 10 16:12 package.exs
-rw-------  1 rprimus wheel 394 Aug 10 16:12 rebar.config
drwx------  3 rprimus wheel  96 Aug 10 16:12 resources
drwx------  5 rprimus wheel 160 Aug 10 16:12 src
drwx------  3 rprimus wheel  96 Aug 10 16:12 test

</details>

Been watching @oubiwann 's talk: https://www.youtube.com/watch?v=Dgbm3BRmzuI and tried out
`lfetool new library my-lib`.

### Questions
1.  Has `lfetool` been updated to use `rebar3`
2.  The generated `rebar.config` lists dependency `lfe-0.9.0` - shouldn't it be listing the latest version?
3.  Has it been updated to use the latest `erlang/OTP` versions?
4.  How much work would be needed to update `lfetool`?

If I can help in some way, let me know.

**Comment by oubiwann** [comment]
Hey, @rprimus! You've been doing some digging! Here are some notes, thoughts, and answers:

* So, `lfetool` is long-deprecated (there's a note on the repo here https://github.com/lfex/lfetool but the recent change to Github layout makes it much harder to see)
* Try out the most recent LFE Quick Start (linked on the main webpage: https://lfe.io/books/rebar3-quick-start/
* There is a new plugin with simplified usage, dependencies, etc., and is introduced in the Quick Start
   * repo: https://github.com/lfe-rebar3/rebar3_lfe/
   * command reference: https://lfe.io/reference/lfe-rebar3/current/
* `rebar3_lfe` supports (and is tested against, in CI/CD) versions 19-23
* `lfetool` will never be updated! Use `rebar3` and the new plugin, instead :-)

**Comment by rprimus** [comment]
Mon Aug 10 18:04:15 BST 2020

Hi @oubiwann - thanks for the quick update.

It might be worth `archiving` https://github.com/lfex/lfetool. 

See: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository

**Comment by oubiwann** [comment]
Oh, thanks for the heads-up! I thought I had archived it (I got all the other old LFE / rebar3 repos archived, once their features were brought into the new plugin ... looks like I missed the big one!)
