### ISSUE TITLE
Release 1.3 retagged?

### ISSUE THREAD

**Issue by gromgit** [lfe/lfe#404]
Hi! The SHA256 checksum for the `lfe` 1.3 source tarball that Homebrew has on record doesn't match what's currently published on GitHub. This issue surfaced when I tried to update the `erlang` Homebrew formula (https://github.com/Homebrew/homebrew-core/pull/60965), which triggered a CI rebuild of `lfe`:
```
==> Downloading https://github.com/rvirding/lfe/archive/v1.3.tar.gz
==> Downloading from https://codeload.github.com/rvirding/lfe/tar.gz/v1.3
Error: SHA256 mismatch
Expected: 1946c0df595ae49ac33fe583f359812dec6349da6acf43c1458534de3267036b
  Actual: 04634f2c700ecedb55f4369962837792669e6be809dba90d81974198fc2b7b72
```
Was v1.3 retagged against a different commit, especially after Jun 4 2017? Thanks much!

**Comment by oubiwann** [comment]
Hey @gromgit, yes it was (we sent out an email to the mail list, notified the two main channels on the LFE Slack, and posted a tweet thread about this on the LFE Twitter account). This happened just this week.

As such, the old checksums will (of course, and as you have noted) no longer be valid. Apologies for the inconvenience ... we had some git history issues that needed to be cleaned up before the 2.0 release of LFE.

**Comment by gromgit** [comment]
Thanks much for the quick response, @oubiwann! Just to confirm, is any _content_ in the new 1.3 tarball different from the old one? This would affect how we'll update the `lfe` Homebrew formula. Thanks again!

**Comment by oubiwann** [comment]
@gromgit none of the content has changed; the only differences are 1) some of the commit ids for the release, and 2) the commit id of the tag.

**Comment by gromgit** [comment]
Cool, that simplifies things from the Homebrew side of things. Thanks much!
