### ISSUE TITLE
Strategies for WISP <-> LFE?

### ISSUE THREAD

**Issue by fire** [lfe/lfe#406]
Would wisp support be a separate project or can it be done in this project?

https://archive.fosdem.org/2019/schedule/event/experiencewithwisp/attachments/slides/2979/export/events/attachments/experiencewithwisp/slides/2979/wisp_fosdem_2019.pdf

**Comment by oubiwann** [comment]
I'd recommend a new project. 

Even if was something as simple as a minor tweak in syntax that removed the majority of parens and substituted them with syntactic whitespace, you'd be presenting a very confusing story for users, with syntax that would tend to draw from two very different backgrounds/proclivities/whathaveyou, to a project that's already struggling to keep up documentation with just _one_ syntax ;-) 

It might be a good exercise to fork LFE, examine the reader functionality, and explore a means of translating from whitespace syntax to LFE's syntax. For now, forking would be required; however, Robert and I have been talking about doing some more abstraction around the reader and evaluator functionality that would essentially transform LFE into a language laboratory for _any_ conceivable syntax ;-) That's a ways off, though ...

**Comment by oubiwann** [comment]
I labeled this as "answered" and am going to close it -- but feel free to ask any additional questions either here in the ticket, on the LFE mail list, or on our Slack!
