### ISSUE TITLE
typo in https://github.com/rvirding/lfe/blob/develop/doc/user_guide.txt#L25 ?

### ISSUE THREAD

**Issue by zeroexcuses** [lfe/lfe#421]
The given line states:

```
#*0 #b*10101 #*-1100
```

when I type it into a lfe repl, I get:

```
lfe> #b*10101
1: illegal based number
```

should the middle term be #*10101 instead ?

**Comment by rvirding** [comment]
Yes, this is a typo. It will be fixed in the next commit.
