### ISSUE TITLE
Is there any advantage to installing lfe via Make or rebar?

### ISSUE THREAD

**Issue by jgarte** [lfe/lfe#441]
Is there any advantage to installing lfe via Make or rebar?

The reason is that I'm making an lfe package for [Guix](guix.gnu.org).

I have a WIP guix package for lfe here in the `Guix 'R Us` channel using Guix's new `rebar-build-system`:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/lfe.scm#L28

It currently doesn't copy the `lfe` binary to the [store](https://guix.gnu.org/manual/en/html_node/The-Store.html). It might need a custom `phase`. But, I was wondering if I should just package `lfe` with the `gnu-build-system` which calls the `Makefile` or using rebar?

**Comment by rvirding** [comment]
Sorry I can't help you here, I just don't know. @oubiwann do you have any idea about this?

**Comment by oubiwann** [comment]
Oof ... I don't know anything about Guix.

I don't know if this helps you, or not ... but: when building LFE for other systems, I keep it bare-bones as possible, using only LFE and `make`. However, when I have to build LFE as part of an OTP release, that's when I use `rebar3`. 

As such, I would venture a _guess_ that you just want to use `make` in your case? Again, though: I know nothing about Guix.

**Comment by jgarte** [comment]
@oubiwann I think that using `make` makes sense here. Using the `rebar-build-system` seems only necessary when packaging erlang libraries that absolutely require `rebar3`.

We could use some help making sure that the `rebar-build-system` is doing the right thing. It is brand new and we might [not know entirely what it is that we are doing yet](https://lists.gnu.org/archive/html/help-guix/2022-06/msg00109.html) ;)

Here's the complete implementation of the `rebar-build-system` in Guile Scheme as part of Guix:

https://github.com/guix-mirror/guix/blob/master/guix/build/rebar-build-system.scm
https://github.com/guix-mirror/guix/blob/master/guix/build-system/rebar.scm

The entire logic for any build system in Guix is retrieved from a scheme [record](https://www.scheme.com/tspl4/records.html) at a higher level of abstraction.

It's a bit complicated/nested because a [build-system](https://github.com/guix-mirror/guix/blob/13c4a377f5a2e1240790679f3d5643385b6d7635/guix/build-system.scm#L45) is a [record](https://lepiller.eu/en/a-deep-dive-into-guix-records.html) contained in another record called a [package](https://github.com/guix-mirror/guix/blob/master/guix/packages.scm#L537).

Guix defines it's own record called [define-record-type*](https://github.com/guix-mirror/guix/blob/8b9a5641bc1b6acb62e0e0467ee03cefde2d1757/guix/records.scm#L272) that is not part of standard Guile.

**Comment by jgarte** [comment]
https://lepiller.eu/en/a-deep-dive-into-guix-records.html
