### ISSUE TITLE
== macro expansion is incorrect

### ISSUE THREAD

**Issue by mjkalyan** [lfe/lfe#445]
For example:
```lisp
(== 1 1) => true
(== 1 1 1) => false
```
This is because the macro expansion for `(== 1 1 1)` is
```lisp
(== (== 1 1) 1)
```
which won't be `true` because the inner `(== 1 1)` is `true` which is not equal to `1`. i.e. `(== 'true 1) => false`.

This is also the case for `=:=`.

**Comment by rvirding** [comment]
Whoops, I will fix this.
