### ISSUE TITLE
Run tests without rebar3

### ISSUE THREAD

**Issue by jgarte** [lfe/lfe#450]
Hi, is there a way to run the tests without `rebar3`?

**Comment by oubiwann** [comment]
Not easily. We have several types of tests, all of which are supported by rebar3 (or rebar3 plugins):
* Erlang Common Test Suites
* Property tests
* eunit / ltest (tests written in LFE)

If you want to run these without rebar3, you'll need to read up on the Erlang docs for running them by themselves (I haven't done that in over 10 years, so I'm not much help).

Note, though, that rebar3 is the default build tool for both Erlang as well as LFE ... so it's not a bad thing to get to know.

**Comment by jgarte** [comment]
Sounds good, I'll go with rebar then and do my homework. Thanks!

**Comment by rvirding** [comment]
I just want to point out that there is a bug in the ms_transform_SUITE.lfe. I am still trying to work out a better of way handling match specifications, in this case transforming them from a lambda to a match spec. There are no problems with the match specs themselves.

**Comment by oubiwann** [comment]
@jgarte I should add some `make` targets for testing, just for convenience ... but until then, you can see how to run the tests by looking at our CI/CD config here:
* https://github.com/lfe/lfe/blob/develop/.github/workflows/cicd.yml
