### ISSUE TITLE
README: Run tests with Makefile

### ISSUE THREAD

**Issue by jgarte** [lfe/lfe#459]
I love that we have explicit instructions on how to [build](https://github.com/lfe/lfe#building) and [install](https://github.com/lfe/lfe#installation) lfe in the README.

Would a PR be accepted to add explicit instructions for how to run the tests via the Makefile?

@rvirding @oubiwann Which one of the following tests should GNU/Linux package maintainers run?

```make
# XXX for some reason, the first pass of eunit doesn't run the tests?!
eunit:
	@rebar3 as test do compile,eunit,eunit

# XXX We've had to limit 'n' to 20, since the default count of 100 was
# causing VM crashes due to atom-table filling. Note, however:
#  * 'prop_lfe_docs:prop_define_lambda' works just fine with 100 tests
#  * 'prop_lfe_docs:prop_define_match' is the one that crashes the VM
proper:
	@rebar3 as test do compile,proper -n 20

common-test:
	@rebar3 as test do compile,ct

ct: common-test

tests:
	@rebar3 as test do compile,eunit,eunit,proper -n 20,ct
```

**Comment by oubiwann** [comment]
Check out the new make targets I've added (#452). CI/CD uses these now too. Adding a note for those new to the project indicating they should run `make tests` would be good (no need to show all the test targets -- you can point the reader to the `Makefile` for those).

**Comment by oubiwann** [comment]
Sorry -- was reading on phone (hard to see full context); i see now that you're referencing the new targets.

The `tests` target runs them all -- that's the most convenient one for maintainers.

**Comment by oubiwann** [comment]
Okay, I've updated the README with a "testing" section!
