### ISSUE TITLE
v2.1.1 tagged but not marked as latest

### ISSUE THREAD

**Issue by p-linnane** [lfe/lfe#463]
Hello. I was wondering if v2.1.1 will be marked as the latest release on GitHub. We have packaged v2.1.1 for [Homebrew](https://github.com/Homebrew/homebrew-core/pull/119700), but are waiting to merge until we get clarification. Thanks!

**Comment by rvirding** [comment]
Sorry, here I must expose my ignorance with GitHub. 😄 How do I do that? Tell me and I will fix it.

**Comment by p-linnane** [comment]
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by oubiwann** [comment]
Done!

**Comment by p-linnane** [comment]
Thank you!

**Comment by rvirding** [comment]
Thank you!
