### ISSUE TITLE
lc/2 not defined

### ISSUE THREAD

**Issue by muswawir** [lfe/lfe#465]
I was implementing a list comprehension following the this example in the user guide. I am running OTP-24.3.4 and LFE-v2.1.1
```
(lc
    ((<- x '(0 1 2 3)))
    (trunc
      (: math pow 3 x)))
```
I am getting this
```
** exception error: function lc/2 undefined
```

Some help.

**Comment by muswawir** [comment]
This issue exists for v2.1.0 and v2.1.1. v2.0.1 works fine. I didn't test lower versions.

**Comment by oubiwann** [comment]
I wonder if Robert removed `lc`? Try `list-comp`?

**Comment by oubiwann** [comment]
Hrm, no -- they're both there: https://github.com/lfe/lfe/blob/f333690822f696c4884726038dee3ce446c1c016/src/lfe_codelift.erl#L180

I'll pull down the latest and take a look ...

**Comment by oubiwann** [comment]
Yeah, I'm getting the same error with `list-comp` ...

**Comment by oubiwann** [comment]
Just checked against the example given in `lfe_guide.txt` just in case the usage had changed.

@rvirding either @lamuswawir has discovered a bug, or the usage has changed for `lc` and the docs in the guide haven't been updated?

Or ... something else? 😉

**Comment by mjkalyan** [comment]
@rvirding addressed this issue here https://github.com/lfe/lfe/issues/442#issuecomment-1296864612

**Comment by muswawir** [comment]
Thanks.

**Comment by oubiwann** [comment]
Quick update: @rvirding's working on an implementation of `lc`/`list-comp` that will add it back to the REPL for us :-) Should be in `develop` soon.
