### ISSUE TITLE
Type definitions and specifications do not accept empty list syntax

### ISSUE THREAD

**Issue by mjkalyan** [lfe/lfe#473]
Using either empty list shorthand, `()`/`[]`, in a `deftype` or `defspec` will cause the compiler to emit the `bad () type definition` error. The similar shorthand notations for the empty map `#m()` and tuple `#()` work just fine.

Here's an example:

```lisp
;; Fails to compile with:
;; bad () type definition
(deftype emptylist [])

;; Also:
;; bad () type definition
[defspec (test 1)
  (((integer))
   [])]
```

**Comment by rvirding** [comment]
OK, the reason for this is that `( )` is used for wrapping a type and is not usable as a literal empty list, `nil`. This can however be done using `(nil)` for the type empty list, maybe not the clearest but it does work. So you would write:

```
(deftype empty_list (nil))
```

Note that using `[ ]` is just some syntactic sugar and is always equivalent to `( )`. Always!

Note also in both Erlang and LFE `nil` is just a normal atom it has no special meaning as such. In fact in LFE it can also be used as a variable. LFE is closer to Erlang than to lisp wrt to data.

I need to work a bit more on the type documentation in lfe_types.txt.
