### ISSUE TITLE
Pattern matching on nested literals with underscore.

### ISSUE THREAD

**Issue by jaccarmac** [lfe/lfe#485]
This is a question, and probably a relatively simple one, but also one I ran into headfirst a few times without figuring out what's going on. The code in context comes from [here](https://github.com/jaccarmac/adventofcode/blob/88b198d99f2dc4b9d0599884560058a4bd5791bb/2023/src/day-3.lfe#L28-L30), but the minimal case follows:

```lfe
(funcall (match-lambda
  (((tuple _ (list l r))) 'matched)
  ((_) 'fell-through))
  (1 2)))
```

I want to match a tuple with an ignored first element and a two-element list; I can operate on said elements and everything else gets a default value. The `(tuple _ (list l r))` is something I'd like to reduce, but I can't figure out how to do it by quoting the equivalent tuple literal. That is, I can prune it slightly, but everything except the first form below fails to match (I forget all the variations I've tried.

```lfe
(tuple _ `(,l ,r))

#(_ `(,l ,r))
`#(_ ,(list l r))
`#(_ ,(l r))
...
```

This may be intended; I've come to the conclusion that one can more or less not do backquoted binary literals. But I haven't found the definitive documentation as to what works and what doesn't on the left-hand side of patterns.

Thanks to all for the work on LFE, though! Paren fatigue aside (which is why I want to figure out how to do this shortly/idiomatically), I've finally picked up the language for Advent of Code after watching it from very far and can say Lisp on the BEAM is a delight.

**Comment by rvirding** [comment]
The issue here is that in a literal everything is literal so there is no expansion or handing of the backquote. So ```#(_ `(,l ,r))``` becomes ```#(_ (backquote ((comma l) (comma r)))``` which is not quite what you wanted. To use the backquote in your function would have to write

```
(funcall (match-lambda
	   ((`#(,_ (,l ,r))) 'matched)
	   ((_) 'fell-through))
	 (1 2)))
```
You need to do `,_` as the `_` is just a normal atom which in patterns is interpreted to match anything and ignore the value, otherwise it will expand to `'_`. This is taken directly from Erlang.

Let me know if you have more questions. After a while you get used to the parens and finally stop counting them. You just see that it is right. :smile:

**Comment by jaccarmac** [comment]
Brilliant, thanks. It's funny, I totally missed the possibility of unquoting underscore while drafting this issue, but ran into it in a simpler case yesterday. Still didn't think of connecting it to this.

> After a while you get used to the parens

Indeed; I've just been away from Lisp for a little long. The extra layer necessary for pattern matching is well worth it, I'm finding.

**Comment by jaccarmac** [comment]
Closed this and then got curious about what I alluded to at the end of the question: Is there a way to use backquote with binary literals? So far my string-matching code has involved lots of expressions of the form

```lfe
(binary "header: " (rest binary))
```

And while I can construct a matching literal with the literal syntax, minimally:

```lfe
#B("header: " ("" binary))
```

backquote and comma appear to cause `bad binary` when I use them in combination with a symbol in that empty string's position.

**Comment by rvirding** [comment]
@jaccarmac could you please open another issue about backquotes in binaries? As this is already closed it disappears.
