### ISSUE TITLE
Test Failures with rebar3 3.23.0

### ISSUE THREAD

**Issue by VlkrS** [lfe/lfe#488]
With rebar3 3.23.0, the following tests fail for lfe 2.1.4:

```
===> Testing prop_lfe_docs:prop_define_lambda()
Error: Unrecognized option: {task,[50,48,44,99,116]}.
===> Testing prop_lfe_docs:prop_define_match()
Error: Unrecognized option: {task,[50,48,44,99,116]}.
===>
0/2 properties passed, 2 failed
===> Failed test cases:
prop_lfe_docs:prop_define_lambda() -> {error,
                                       {unrecognized_option,{task,"20,ct"}}}
prop_lfe_docs:prop_define_match() -> {error,
                                      {unrecognized_option,{task,"20,ct"}}}
```

Both tests pass when using rebar3 3.22.1.

**Comment by VlkrS** [comment]
The problem is in the Makefile in 

https://github.com/lfe/lfe/blob/b54a121fbe1ba53393745c0607bb0f1b81066081/Makefile#L199

Reordering this as 

```@rebar3 as test do compile,eunit,eunit,ct,proper -n 20```

makes all tests pass again.

**Comment by delitrem** [comment]
Oops. I'm very sorry, have noticed this bugreport only after PR submission (#491). I can cancel it or do whatever more appricated.

BTW, it seems to be related to: https://github.com/erlang/rebar3/pull/2813.

**Comment by VlkrS** [comment]
Not sure if this is addressed to me, but in case it is: I'm happy with any kind of fix.

**Comment by oubiwann** [comment]
Thanks, @delitrem! (both for the PR and for your comments here, including the link to the breaking change in rebar3).
