### ISSUE TITLE
Build failure on OTP 19

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#497]
This _looks_ like it's due to the older version of the Github "checkout" tool (written in Node), but not sure why it's failing on 19 but passing on 20 and 21?

```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
```

This first showed up on the scheduled CI/CD runs, starting July 3rd of this year.

**Comment by oubiwann** [comment]
I've updated to checkout, v4 ... let's see how this goes.

**Comment by oubiwann** [comment]
Still failing for OTP 19. This is due to the following:
* Github is forcing newer Node versions for its tooling
* Newer versions of Node do not support older versions of glibc
* New versions of Ubuntu do not support OTP 19

I'm going to try some forced down-grading of Node in the "older builds" OS images ...

**Comment by oubiwann** [comment]
Nope. Had to comment out OTP 19 in the CI/CD config :-(

**Comment by oubiwann** [comment]
Okay, we've got green builds again -- just no more OTP 19 in our automated builds.

**Comment by rvirding** [comment]
OK, thanks. Not much to do about it then, a bit hard to fight github. 😉 Fortunately OTP 19 is old 😄
