### ISSUE TITLE
Add support for (describe ...) in the REPL

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#67]
So, I know that when we talked about adding support for docstrings, we agreed to simply discard the docstring data. In fact, I advised that, iirc ;-)

Now that our REPL is getting much cooler, I was hoping we could add support for `(describe ...)` :-)

Questions, of course, would be things like these:
- where do we store docstrings?
- how do we treat Erlang-style docs? (e.g., what happens when we `(describe #'lists:map/2)`?
- what about parsing docstings for `edoc` markup?

**Comment by oubiwann** [comment]
With regard to @rvirding's second point, I guess we could just do this:

``` cl
> (describe 'mod 'func n)
```

where `n` is the arity. We could also provide a sane default for this:

``` cl
> (describe 'mod 'func)
```

where perhaps the default arity selected would be the one with the longest docstring ...

**Comment by oubiwann** [comment]
As to the docstring storage ... what about this:
- put it in the module's attributes
- make the key the atom `docstrings`
- make the value a list of key/value tuples where each key would be `#(func n)` and the value would be the docstring for that function + arity.
- look-ups would then be done like this: `(lists:keyfind #(func n) 1 (mod:module_info 'docstrings))` (which, of course, would be wrappted by a REPL `describe` or `help` function (I kind of like the idea of re-using the `help` name with arities 2 and 3)

**Comment by yurrriq** [comment]
Sounds good to me!

**Comment by yurrriq** [comment]
[Lodox](https://github.com/lfex/lodox) might be of some use. I'd be down to make changes if it helps achieve the goals described here. An interesting feature to note is that [`lodox-parse:docs/1`](https://github.com/quasiquoting/lodox/blob/0.12.4/src/lodox-parse.lfe#L31) produces a giant map of parsed metadata, including docstrings and arglists/patterns.

For reference, parsed function (and macro) maps look like this:

``` lfe
'#m(name     func
    arity    2
    patterns ((x y))
    doc      "func/2 does something really cool.")
```

**Comment by yurrriq** [comment]
Relevant project: https://github.com/erszcz/docsh

**Comment by yurrriq** [comment]
As for `(describe #'foo:bar/1)`, couldn't we use `fun_info/2` to extract the `name` and `arity` and then do the lookup in `module_info` as previously described?

**Comment by yurrriq** [comment]
See [my comment](https://github.com/rvirding/lfe/issues/211#issuecomment-205158462) on #211. I'm working on it [here](https://github.com/yurrriq/ldoc) for the time being.

**Comment by yurrriq** [comment]
I think this can be closed now that we have the built-in shell function, `(doc ...)`.
