### ISSUE TITLE
LFE and hygenic macros?

### ISSUE THREAD

**Issue by AeroNotix** [lfe/lfe#80]
Hi,

After an interesting talk with @rvirding in #erlang, it's clear that LFE does not have the utilities to create hygenic macros.

Take the following situation (Common Lisp):

``` lisp
(defmacro for (var start stop &body body)
 `(progn
    (format t "stopping at: ~d" ,stop)
    (do
    ((,var ,start (1+, var)))
    ((> ,var ,stop))
    ,@body)))
```

This works fine when we call it as such:

``` lisp
(for i 1 5
  (print i))
;;
stopping at: 5
1 
2 
3 
4 
5 
NIL
```

However, calling this macro with a call to another side-effecting function yields strange results:

``` lisp
CL-USER> (for i 1 (random 10) (print i))
stopping at: 9
1 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 3
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 7
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 1
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 8
1 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 7
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 5
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 2
1 
2 
3 
4 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 0
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 2
1 
2 
3 
4 
5 
```

Which is _most definitely_ incorrect.

Ok, so how about we bind the stop call _before_ making the do block? Okay!

``` lisp
(defmacro for (var start stop &body body)
 `(let ((real-stop ,stop))
    (progn
      (format t "stopping at: ~d" real-stop)
      (do
       ((,var ,start (1+, var)))
       ((> ,var real-stop))
        ,@body))))
```

Yields:

``` lisp
CL-USER> (for i 1 (random 10) (print i))
stopping at: 6
1 
2 
3 
4 
5 
6 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 3
1 
2 
3 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 2
1 
2 
NIL
CL-USER> (for i 1 (random 10) (print i))
stopping at: 9
1 
2 
3 
4 
5 
6 
7 
8 
9 
NIL
```

Which is what we want! But wait...

What if the body of the macro was used as such:

``` lisp
(for i 1 (random 10) (setq real-stop :banana))
```

Yields (SBCL):

```
The value :BANANA is not of type REAL.
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {10036D8063}>)

Backtrace:
  0: ((LAMBDA ()))
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (FOR I 1 (RANDOM 10) (SETQ REAL-STOP :BANANA)) #<NULL-LEXENV>)
  2: (EVAL (FOR I 1 (RANDOM 10) (SETQ REAL-STOP :BANANA)))
 --more--
```

Whoooops.

What about the wholly more insidious:

``` lisp
(for i 1 (random 10) (setq real-stop (random 100000)))
```

Which means the iteration stops on a random basis entirely.

Lisps get around this usually by using a call to `(gensym)` which creates a symbol which is _guaranteed_ to be unique, this means we can bind forms to a generated symbol thereby ensuring that the form is evaluated once and that the symbol will not clash with any captured body.

@rvirding mentioned to me that `(gensym)` would create atoms in the atom table. Number one, I do not understand fully how LFE is implemented. However, I don't understand why atoms are needed in the creation of a Variable label? You would just need to generate a variable name which can be used in the body.

Am I missing some information here?

**Comment by arpunk** [comment]
I'm bumping this in order to clarify and update the current LFE documentation to get it ready for the release.

@rvirding, @AeroNotix  any final words on this?
