### ISSUE TITLE
to implement something like lfe-shell to avoid using bash to wrap the executable file "lfe"

### ISSUE THREAD

**Issue by xieyuheng** [lfe/lfe#96]
I would wish so :)

**Comment by oubiwann** [comment]
@xieyuheng I'm not sure what you're asking either ... but, just in case this help, did you know that you can now use `lfe -eval '(some expression ...)'`?

**Comment by rvirding** [comment]
@xieyuheng what did you mean by this? I was going through old issues and saw that we didn't get anywhere with this.

**Comment by xieyuheng** [comment]
:p so long ago ~
I forget why I am asking for this.
sorry to bug you.

may the development of lfs goes well :)
