### ISSUE TITLE
LFE's having a hard time including lager.hrl

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#99]
Here's the error in the REPL:

``` cl
> (include-file "deps/lager/include/lager.hrl")
1: Warning: unable to translate macro 'INT_LOG'
exception error: #(unbound_func #(extend-module 1))
```

Something similar happens when I try to include it in a file and then compile. In the code:

``` cl
(include-file "deps/lager/include/lager.hrl")
```

And the compile output:

```
Compiled src/sample-app-routes.lfe
Compiled src/sample-app-nav.lfe
src/sample-app-gae.lfe:5: Warning: unable to translate macro 'INT_LOG'
Compiled src/sample-app-gae.lfe
Compiled src/sample-app-content.lfe
```

[Here's a copy](https://github.com/basho/lager/blob/master/include/lager.hrl) of the `hrl` file.

**Comment by yurrriq** [comment]
Fixed with logjam, no?

**Comment by oubiwann** [comment]
@yurrriq Well, logjam offers what is essentially a work-around...

It would be nice if LFE was capable of addressing the two bullet points @rvirding outlined above (and I think it does now).

Maybe the other half of the problem to which Robert referred is the Erlang parse transforms (used by lager) which LFE can't do anything about?

**Comment by yurrriq** [comment]
Ah, right... I wonder how we might support parse transforms. I suppose we might have to transform the parse transforms first. 🙃

**Comment by oubiwann** [comment]
I just checked, and it's still a problem:

``` lisp
> (include-file "include/lager.hrl")
1: Warning: unable to translate macro 'INT_LOG'
LEVEL2NUM
```

**Comment by yurrriq** [comment]
:disappointed: Thanks for checking.

**Comment by oubiwann** [comment]
The logjam work-around uses older lager for logjam + older Erlang versions.

For newer versions of Erlang that support the new `logger` module, logjam just uses that.

Closing.
